#define _CRYPTO_PADLOCK_H
#define PADLOCK_ALIGNMENT 16
#define PFX	KBUILD_MODNAME ": "
#define PADLOCK_CRA_PRIORITY	300
#define PADLOCK_COMPOSITE_PRIORITY 400
#define STACK_ALIGN 16
#define STACK_ALIGN 4
