#define AVCODEC_ARM_IDCT_H
ff_j_rev_dct_arm;
ff_simple_idct_arm;
ff_simple_idct_armv5te;
ff_simple_idct_put_armv5te;
ff_simple_idct_add_armv5te;
ff_simple_idct_armv6;
ff_simple_idct_put_armv6;
ff_simple_idct_add_armv6;
ff_simple_idct_neon;
ff_simple_idct_put_neon;
ff_simple_idct_add_neon;
