#define SWRESAMPLE_VERSION_H
#define LIBSWRESAMPLE_VERSION_MAJOR   2
#define LIBSWRESAMPLE_VERSION_MINOR   3
#define LIBSWRESAMPLE_VERSION_MICRO 100
AV_VERSION_INT
AV_VERSION
#define LIBSWRESAMPLE_BUILD        LIBSWRESAMPLE_VERSION_INT
AV_STRINGIFY
