package org.apache.hadoop.yarn.server.api.protocolrecords.impl.pb;
import org.apache.hadoop.yarn.proto.YarnServerResourceManagerServiceProtos.RemoveFromClusterNodeLabelsResponseProto;
import org.apache.hadoop.yarn.server.api.protocolrecords.RemoveFromClusterNodeLabelsResponse;
import com.google.protobuf.TextFormat;
public class RemoveFromClusterNodeLabelsResponsePBImpl extends
RemoveFromClusterNodeLabelsResponse
