static unsigned int stack_maxrandom_size(void)
#define MIN_GAP (128*1024*1024UL + stack_maxrandom_size())
#define MAX_GAP (TASK_SIZE/6*5)
static int mmap_is_ia32(void)
static int mmap_is_legacy(void)
static unsigned long mmap_rnd(void)
static unsigned long mmap_base(void)
static unsigned long mmap_legacy_base(void)
void arch_pick_mmap_layout(struct mm_struct *mm)
