#define VIC_REG(off) (MSM_VIC_BASE + (off))
#define VIC_INT_SELECT0     VIC_REG(0x0000)
#define VIC_INT_SELECT1     VIC_REG(0x0004)
#define VIC_INT_EN0         VIC_REG(0x0010)
#define VIC_INT_EN1         VIC_REG(0x0014)
#define VIC_INT_ENCLEAR0    VIC_REG(0x0020)
#define VIC_INT_ENCLEAR1    VIC_REG(0x0024)
#define VIC_INT_ENSET0      VIC_REG(0x0030)
#define VIC_INT_ENSET1      VIC_REG(0x0034)
#define VIC_INT_TYPE0       VIC_REG(0x0040)
#define VIC_INT_TYPE1       VIC_REG(0x0044)
#define VIC_INT_POLARITY0   VIC_REG(0x0050)
#define VIC_INT_POLARITY1   VIC_REG(0x0054)
#define VIC_NO_PEND_VAL     VIC_REG(0x0060)
#define VIC_INT_MASTEREN    VIC_REG(0x0064)
#define VIC_PROTECTION      VIC_REG(0x006C)
#define VIC_CONFIG          VIC_REG(0x0068)
#define VIC_IRQ_STATUS0     VIC_REG(0x0080)
#define VIC_IRQ_STATUS1     VIC_REG(0x0084)
#define VIC_FIQ_STATUS0     VIC_REG(0x0090)
#define VIC_FIQ_STATUS1     VIC_REG(0x0094)
#define VIC_RAW_STATUS0     VIC_REG(0x00A0)
#define VIC_RAW_STATUS1     VIC_REG(0x00A4)
#define VIC_INT_CLEAR0      VIC_REG(0x00B0)
#define VIC_INT_CLEAR1      VIC_REG(0x00B4)
#define VIC_SOFTINT0        VIC_REG(0x00C0)
#define VIC_SOFTINT1        VIC_REG(0x00C4)
#define VIC_IRQ_VEC_RD      VIC_REG(0x00D0)
#define VIC_IRQ_VEC_PEND_RD VIC_REG(0x00D4)
#define VIC_IRQ_VEC_WR      VIC_REG(0x00D8)
#define VIC_IRQ_IN_SERVICE  VIC_REG(0x00E0)
#define VIC_IRQ_IN_STACK    VIC_REG(0x00E4)
#define VIC_TEST_BUS_SEL    VIC_REG(0x00E8)
#define VIC_VECTPRIORITY(n) VIC_REG(0x0200+((n) * 4))
#define VIC_VECTADDR(n)     VIC_REG(0x0400+((n) * 4))
static void msm_irq_ack(struct irq_data *d)
static void msm_irq_mask(struct irq_data *d)
static void msm_irq_unmask(struct irq_data *d)
static int msm_irq_set_wake(struct irq_data *d, unsigned int on)
static int msm_irq_set_type(struct irq_data *d, unsigned int flow_type)
static struct irq_chip msm_irq_chip = ;
void __init msm_init_irq(void)
