#define DECLARE_PRIMITIVE(name) \ \
int sctp_primitive_ ## name(struct sctp_association *asoc, \
void *arg)
DECLARE_PRIMITIVE(ASSOCIATE)
DECLARE_PRIMITIVE(SHUTDOWN);
DECLARE_PRIMITIVE(ABORT);
DECLARE_PRIMITIVE(SEND);
DECLARE_PRIMITIVE(REQUESTHEARTBEAT);
DECLARE_PRIMITIVE(ASCONF);
