static unsigned char pdacf_ak4117_read(void *private_data, unsigned char reg)
static void pdacf_ak4117_write(void *private_data, unsigned char reg, unsigned char val)
static int pdacf_reset(struct snd_pdacf *chip, int powerdown)
void pdacf_reinit(struct snd_pdacf *chip, int resume)
static void pdacf_proc_read(struct snd_info_entry * entry,
struct snd_info_buffer *buffer)
static void pdacf_proc_init(struct snd_pdacf *chip)
struct snd_pdacf *snd_pdacf_create(struct snd_card *card)
static void snd_pdacf_ak4117_change(struct ak4117 *ak4117, unsigned char c0, unsigned char c1)
int snd_pdacf_ak4117_create(struct snd_pdacf *chip)
void snd_pdacf_powerdown(struct snd_pdacf *chip)
int snd_pdacf_suspend(struct snd_pdacf *chip, pm_message_t state)
static inline int check_signal(struct snd_pdacf *chip)
int snd_pdacf_resume(struct snd_pdacf *chip)
