static inline port_id br_make_port_id(__u8 priority, __u16 port_no)
#define BR_MAX_PORT_PRIORITY ((u16)~0 >> BR_PORT_BITS)
void br_init_port(struct net_bridge_port *p)
void br_stp_enable_bridge(struct net_bridge *br)
void br_stp_disable_bridge(struct net_bridge *br)
void br_stp_enable_port(struct net_bridge_port *p)
void br_stp_disable_port(struct net_bridge_port *p)
static void br_stp_start(struct net_bridge *br)
static void br_stp_stop(struct net_bridge *br)
void br_stp_set_enabled(struct net_bridge *br, unsigned long val)
void br_stp_change_bridge_id(struct net_bridge *br, const unsigned char *addr)
static const unsigned short br_mac_zero_aligned[ETH_ALEN >> 1];
bool br_stp_recalculate_bridge_id(struct net_bridge *br)
void br_stp_set_bridge_priority(struct net_bridge *br, u16 newprio)
int br_stp_set_port_priority(struct net_bridge_port *p, unsigned long newprio)
int br_stp_set_path_cost(struct net_bridge_port *p, unsigned long path_cost)
ssize_t br_show_bridge_id(char *buf, const struct bridge_id *id)
