static inline void _int_mask_set(struct spu *spu, int class, u64 mask)
static inline u64 _int_mask_get(struct spu *spu, int class)
static void int_mask_set(struct spu *spu, int class, u64 mask)
static u64 int_mask_get(struct spu *spu, int class)
static void int_mask_and(struct spu *spu, int class, u64 mask)
static void int_mask_or(struct spu *spu, int class, u64 mask)
static void int_stat_clear(struct spu *spu, int class, u64 stat)
static u64 int_stat_get(struct spu *spu, int class)
static void cpu_affinity_set(struct spu *spu, int cpu)
static u64 mfc_dar_get(struct spu *spu)
static u64 mfc_dsisr_get(struct spu *spu)
static void mfc_dsisr_set(struct spu *spu, u64 dsisr)
static void mfc_sdr_setup(struct spu *spu)
static void mfc_sr1_set(struct spu *spu, u64 sr1)
static u64 mfc_sr1_get(struct spu *spu)
static void mfc_tclass_id_set(struct spu *spu, u64 tclass_id)
static u64 mfc_tclass_id_get(struct spu *spu)
static void tlb_invalidate(struct spu *spu)
static void resource_allocation_groupID_set(struct spu *spu, u64 id)
static u64 resource_allocation_groupID_get(struct spu *spu)
static void resource_allocation_enable_set(struct spu *spu, u64 enable)
static u64 resource_allocation_enable_get(struct spu *spu)
const struct spu_priv1_ops spu_priv1_beat_ops = ;
