#define CHIPC_INLINE_H
typedef enum  chipcHw_OPTYPE_e;
static inline void chipcHw_setClock(chipcHw_CLOCK_e clock,
chipcHw_OPTYPE_e type, int mode);
static inline uint32_t chipcHw_getChipId(void)
static inline void chipcHw_enableSpreadSpectrum(void)
static inline void chipcHw_disableSpreadSpectrum(void)
static inline uint32_t chipcHw_getChipProductId(void)
static inline chipcHw_REV_NUMBER_e chipcHw_getChipRevisionNumber(void)
static inline void chipcHw_busInterfaceClockEnable(uint32_t mask)
static inline void chipcHw_busInterfaceClockDisable(uint32_t mask)
static inline uint32_t chipcHw_getBusInterfaceClockStatus(void)
static inline void chipcHw_audioChannelEnable(uint32_t mask)
static inline void chipcHw_audioChannelDisable(uint32_t mask)
static inline void chipcHw_softReset(uint64_t mask)
static inline void chipcHw_softResetDisable(uint64_t mask)
static inline void chipcHw_softResetEnable(uint64_t mask)
static inline void chipcHw_miscControl(uint32_t mask)
static inline void chipcHw_miscControlDisable(uint32_t mask)
static inline void chipcHw_miscControlEnable(uint32_t mask)
static inline void chipcHw_setOTPOption(uint64_t mask)
static inline uint32_t chipcHw_getStickyBits(void)
static inline void chipcHw_setStickyBits(uint32_t mask)
static inline void chipcHw_clearStickyBits(uint32_t mask)
static inline uint32_t chipcHw_getSoftStraps(void)
static inline void chipcHw_setSoftStraps(uint32_t strapOptions)
static inline uint32_t chipcHw_getPinStraps(void)
static inline uint32_t chipcHw_getValidStraps(void)
static inline void chipcHw_initValidStraps(void)
static inline chipcHw_BOOT_DEVICE_e chipcHw_getBootDevice(void)
static inline chipcHw_BOOT_MODE_e chipcHw_getBootMode(void)
static inline chipcHw_NAND_PAGESIZE_e chipcHw_getNandPageSize(void)
static inline int chipcHw_getNandExtraCycle(void)
static inline void chipcHw_activatePifInterface(void)
static inline void chipcHw_activateLcdInterface(void)
static inline void chipcHw_deactivatePifLcdInterface(void)
static inline void chipcHw_selectGE2(void)
static inline void chipcHw_selectGE3(void)
static inline chipcHw_GPIO_FUNCTION_e chipcHw_getGpioPinFunction(int pin)
static inline void chipcHw_setGpioPinFunction(int pin,
chipcHw_GPIO_FUNCTION_e func)
static inline void chipcHw_setPinSlewRate(uint32_t pin,
chipcHw_PIN_SLEW_RATE_e slewRate)
static inline void chipcHw_setPinOutputCurrent(uint32_t pin,
chipcHw_PIN_CURRENT_STRENGTH_e
curr)
static inline void chipcHw_setPinPullup(uint32_t pin, chipcHw_PIN_PULL_e pullup)
static inline void chipcHw_setPinInputType(uint32_t pin,
chipcHw_PIN_INPUTTYPE_e inputType)
static inline void chipcHw_powerUpUsbPhy(void)
static inline void chipcHw_powerDownUsbPhy(void)
static inline void chipcHw_setUsbHost(void)
static inline void chipcHw_setUsbDevice(void)
static inline void chipcHw_setClock(chipcHw_CLOCK_e clock,
chipcHw_OPTYPE_e type, int mode)
static inline void chipcHw_setClockDisable(chipcHw_CLOCK_e clock)
static inline void chipcHw_setClockEnable(chipcHw_CLOCK_e clock)
static inline void chipcHw_bypassClockEnable(chipcHw_CLOCK_e clock)
static inline void chipcHw_bypassClockDisable(chipcHw_CLOCK_e clock)
static inline int chipcHw_isSoftwareStrapsEnable(void)
static inline void chipcHw_softwareStrapsEnable(void)
static inline void chipcHw_softwareStrapsDisable(void)
static inline void chipcHw_pllTestEnable(void)
static inline void chipcHw_pll2TestEnable(void)
static inline void chipcHw_pllTestDisable(void)
static inline void chipcHw_pll2TestDisable(void)
static inline int chipcHw_isPllTestEnable(void)
static inline int chipcHw_isPll2TestEnable(void)
static inline void chipcHw_pllTestSelect(uint32_t val)
static inline void chipcHw_pll2TestSelect(uint32_t val)
static inline uint8_t chipcHw_getPllTestSelected(void)
static inline uint8_t chipcHw_getPll2TestSelected(void)
static inline void chipcHw_pll1Disable(void)
static inline void chipcHw_pll2Disable(void)
static inline void chipcHw_ddrPhaseAlignInterruptEnable(void)
static inline void chipcHw_ddrPhaseAlignInterruptDisable(void)
static inline void
chipcHw_vpmPhaseAlignInterruptMode(chipcHw_VPM_HW_PHASE_INTR_e mode)
static inline void chipcHw_ddrSwPhaseAlignEnable(void)
static inline void chipcHw_ddrSwPhaseAlignDisable(void)
static inline void chipcHw_ddrHwPhaseAlignEnable(void)
static inline void chipcHw_ddrHwPhaseAlignDisable(void)
static inline void chipcHw_vpmSwPhaseAlignEnable(void)
static inline void chipcHw_vpmSwPhaseAlignDisable(void)
static inline void chipcHw_vpmHwPhaseAlignEnable(void)
static inline void chipcHw_vpmHwPhaseAlignDisable(void)
static inline void
chipcHw_setDdrHwPhaseAlignMargin(chipcHw_DDR_HW_PHASE_MARGIN_e margin)
static inline void
chipcHw_setVpmHwPhaseAlignMargin(chipcHw_VPM_HW_PHASE_MARGIN_e margin)
static inline uint32_t chipcHw_isDdrHwPhaseAligned(void)
static inline uint32_t chipcHw_isVpmHwPhaseAligned(void)
static inline uint32_t chipcHw_getDdrHwPhaseAlignStatus(void)
static inline uint32_t chipcHw_getVpmHwPhaseAlignStatus(void)
static inline uint32_t chipcHw_getDdrPhaseControl(void)
static inline uint32_t chipcHw_getVpmPhaseControl(void)
static inline void chipcHw_ddrHwPhaseAlignTimeout(uint32_t busCycle)
static inline void chipcHw_vpmHwPhaseAlignTimeout(uint32_t busCycle)
static inline void chipcHw_ddrHwPhaseAlignTimeoutInterruptClear(void)
static inline void chipcHw_vpmHwPhaseAlignTimeoutInterruptClear(void)
static inline void chipcHw_ddrHwPhaseAlignTimeoutInterruptEnable(void)
static inline void chipcHw_vpmHwPhaseAlignTimeoutInterruptEnable(void)
static inline void chipcHw_ddrHwPhaseAlignTimeoutInterruptDisable(void)
static inline void chipcHw_vpmHwPhaseAlignTimeoutInterruptDisable(void)
