#define _ASM_S390_SPARSEMEM_H
#define SECTION_SIZE_BITS	28
#define MAX_PHYSADDR_BITS	42
#define MAX_PHYSMEM_BITS	42
#define SECTION_SIZE_BITS	25
#define MAX_PHYSADDR_BITS	31
#define MAX_PHYSMEM_BITS	31
