struct tmComResHWDescr  __attribute__((packed));
struct tmComResInterfaceDescr ;
struct tmComResBusDescr ;
enum tmBusType ;
struct tmComResBusInfo ;
struct tmComResInfo  __attribute__((packed));
enum tmComResCmd ;
struct cmd ;
struct tmDescriptor ;
struct tmComResDescrHeader  __attribute__((packed));
struct tmComResExtDevDescrHeader  __attribute__((packed));
struct tmComResGPIO  __attribute__((packed));
struct tmComResPathDescrHeader  __attribute__((packed));
enum tmComResTermType ;
struct tmComResAntTermDescrHeader  __attribute__((packed));
struct tmComResTunerDescrHeader  __attribute__((packed));
enum tmBufferFlag ;
struct tmBuffer ;
struct tmHWStreamParameters ;
struct tmStreamParameters ;
struct tmComResDMATermDescrHeader  __attribute__((packed));
struct tmComResTSFormatDescrHeader  __attribute__((packed));
struct tmComResSelDescrHeader  __attribute__((packed));
struct tmComResProcDescrHeader  __attribute__((packed));
#define EU_VIDEO_BIT_RATE_MODE_CONSTANT		(0)
#define EU_VIDEO_BIT_RATE_MODE_VARIABLE_AVERAGE (1)
#define EU_VIDEO_BIT_RATE_MODE_VARIABLE_PEAK	(2)
struct tmComResEncVideoBitRate  __attribute__((packed));
struct tmComResEncVideoInputAspectRatio  __attribute__((packed));
#define SAA7164_ENCODER_DEFAULT_GOP_DIST (1)
#define SAA7164_ENCODER_DEFAULT_GOP_SIZE (15)
struct tmComResEncVideoGopStructure  __attribute__((packed));
struct tmComResEncoderDescrHeader  __attribute__((packed));
struct tmComResAFeatureDescrHeader  __attribute__((packed));
struct tmComResAudioDefaults  __attribute__((packed));
struct tmComResEncAudioBitRate  __attribute__((packed));
struct tmComResTunerStandard  __attribute__((packed));
struct tmComResTunerStandardAuto  __attribute__((packed));
struct tmComResPSFormatDescrHeader  __attribute__((packed));
struct tmComResVBIFormatDescrHeader  __attribute__((packed));
struct tmComResProbeCommit  __attribute__((packed));
struct tmComResDebugSetLevel  __attribute__((packed));
struct tmComResDebugGetData  __attribute__((packed));
struct tmFwInfoStruct  __attribute__((packed));
