#define AVCODEC_MIPS_H263DSP_MIPS_H
ff_h263_h_loop_filter_msa;
ff_h263_v_loop_filter_msa;
ff_dct_unquantize_mpeg2_inter_msa;
ff_dct_unquantize_h263_inter_msa;
ff_dct_unquantize_h263_intra_msa;
ff_pix_sum_msa;
