avc_wgt_4x2_msa
avc_wgt_4x4multiple_msa
avc_wgt_4width_msa
avc_wgt_8width_msa
avc_wgt_16width_msa
avc_biwgt_4x2_msa
avc_biwgt_4x4multiple_msa
avc_biwgt_4width_msa
avc_biwgt_8width_msa
avc_biwgt_16width_msa
AVC_LPF_P0P1P2_OR_Q0Q1Q2  \
AVC_LPF_P0_OR_Q0      \
AVC_LPF_P1_OR_Q1   \
AVC_LPF_P0Q0                \
AVC_LPF_H_CHROMA_422      \
TRANSPOSE2x4_B_UB  \
AVC_LPF_H_2BYTE_CHROMA_422  \
avc_loopfilter_luma_intra_edge_hor_msa
avc_loopfilter_luma_intra_edge_ver_msa
avc_h_loop_filter_luma_mbaff_intra_msa
avc_loopfilter_cb_or_cr_intra_edge_hor_msa
avc_loopfilter_cb_or_cr_intra_edge_ver_msa
avc_loopfilter_luma_inter_edge_ver_msa
avc_loopfilter_luma_inter_edge_hor_msa
avc_h_loop_filter_luma_mbaff_msa
avc_loopfilter_cb_or_cr_inter_edge_hor_msa
avc_loopfilter_cb_or_cr_inter_edge_ver_msa
avc_h_loop_filter_chroma422_msa
avc_h_loop_filter_chroma422_mbaff_msa
ff_h264_h_lpf_luma_inter_msa
ff_h264_v_lpf_luma_inter_msa
ff_h264_h_lpf_chroma_inter_msa
ff_h264_v_lpf_chroma_inter_msa
ff_h264_h_lpf_luma_intra_msa
ff_h264_v_lpf_luma_intra_msa
ff_h264_h_lpf_chroma_intra_msa
ff_h264_v_lpf_chroma_intra_msa
ff_h264_h_loop_filter_chroma422_msa
ff_h264_h_loop_filter_chroma422_mbaff_msa
ff_h264_h_loop_filter_luma_mbaff_msa
ff_h264_h_loop_filter_luma_mbaff_intra_msa
ff_weight_h264_pixels16_8_msa
ff_weight_h264_pixels8_8_msa
ff_weight_h264_pixels4_8_msa
ff_biweight_h264_pixels16_8_msa
ff_biweight_h264_pixels8_8_msa
ff_biweight_h264_pixels4_8_msa
