#define AVCODEC_MIPS_ME_CMP_MIPS_H
ff_hadamard8_diff8x8_msa;
ff_hadamard8_intra8x8_msa;
ff_hadamard8_diff16_msa;
ff_hadamard8_intra16_msa;
ff_pix_abs16_msa;
ff_pix_abs16_x2_msa;
ff_pix_abs16_y2_msa;
ff_pix_abs16_xy2_msa;
ff_pix_abs8_msa;
ff_pix_abs8_x2_msa;
ff_pix_abs8_y2_msa;
ff_pix_abs8_xy2_msa;
ff_sse16_msa;
ff_sse8_msa;
ff_sse4_msa;
ff_add_pixels8_msa;
