#define __XEN_PUBLIC_PHYSDEV_H__
#define PHYSDEVOP_eoi			12
struct physdev_eoi ;
#define PHYSDEVOP_irq_status_query	 5
struct physdev_irq_status_query ;
#define _XENIRQSTAT_needs_eoi	(0)
#define	 XENIRQSTAT_needs_eoi	(1U<<_XENIRQSTAT_needs_eoi)
#define _XENIRQSTAT_shared	(1)
#define	 XENIRQSTAT_shared	(1U<<_XENIRQSTAT_shared)
#define PHYSDEVOP_set_iopl		 6
struct physdev_set_iopl ;
#define PHYSDEVOP_set_iobitmap		 7
struct physdev_set_iobitmap ;
#define PHYSDEVOP_apic_read		 8
#define PHYSDEVOP_apic_write		 9
struct physdev_apic ;
#define PHYSDEVOP_alloc_irq_vector	10
#define PHYSDEVOP_free_irq_vector	11
struct physdev_irq ;
#define MAP_PIRQ_TYPE_MSI		0x0
#define MAP_PIRQ_TYPE_GSI		0x1
#define MAP_PIRQ_TYPE_UNKNOWN		0x2
#define PHYSDEVOP_map_pirq		13
struct physdev_map_pirq ;
#define PHYSDEVOP_unmap_pirq		14
struct physdev_unmap_pirq ;
#define PHYSDEVOP_manage_pci_add	15
#define PHYSDEVOP_manage_pci_remove	16
struct physdev_manage_pci ;
#define PHYSDEVOP_manage_pci_add_ext	20
struct physdev_manage_pci_ext ;
struct physdev_op ;
#define PHYSDEVOP_setup_gsi    21
struct physdev_setup_gsi ;
#define PHYSDEVOP_get_nr_pirqs    22
struct physdev_nr_pirqs ;
#define PHYSDEVOP_get_free_pirq    23
struct physdev_get_free_pirq ;
#define PHYSDEVOP_IRQ_UNMASK_NOTIFY	 4
#define PHYSDEVOP_IRQ_STATUS_QUERY	 PHYSDEVOP_irq_status_query
#define PHYSDEVOP_SET_IOPL		 PHYSDEVOP_set_iopl
#define PHYSDEVOP_SET_IOBITMAP		 PHYSDEVOP_set_iobitmap
#define PHYSDEVOP_APIC_READ		 PHYSDEVOP_apic_read
#define PHYSDEVOP_APIC_WRITE		 PHYSDEVOP_apic_write
#define PHYSDEVOP_ASSIGN_VECTOR		 PHYSDEVOP_alloc_irq_vector
#define PHYSDEVOP_FREE_VECTOR		 PHYSDEVOP_free_irq_vector
#define PHYSDEVOP_IRQ_NEEDS_UNMASK_NOTIFY XENIRQSTAT_needs_eoi
#define PHYSDEVOP_IRQ_SHARED		 XENIRQSTAT_shared
