#define __XEN_PUBLIC_XEN_H__
#define __HYPERVISOR_set_trap_table        0
#define __HYPERVISOR_mmu_update            1
#define __HYPERVISOR_set_gdt               2
#define __HYPERVISOR_stack_switch          3
#define __HYPERVISOR_set_callbacks         4
#define __HYPERVISOR_fpu_taskswitch        5
#define __HYPERVISOR_sched_op_compat       6
#define __HYPERVISOR_dom0_op               7
#define __HYPERVISOR_set_debugreg          8
#define __HYPERVISOR_get_debugreg          9
#define __HYPERVISOR_update_descriptor    10
#define __HYPERVISOR_memory_op            12
#define __HYPERVISOR_multicall            13
#define __HYPERVISOR_update_va_mapping    14
#define __HYPERVISOR_set_timer_op         15
#define __HYPERVISOR_event_channel_op_compat 16
#define __HYPERVISOR_xen_version          17
#define __HYPERVISOR_console_io           18
#define __HYPERVISOR_physdev_op_compat    19
#define __HYPERVISOR_grant_table_op       20
#define __HYPERVISOR_vm_assist            21
#define __HYPERVISOR_update_va_mapping_otherdomain 22
#define __HYPERVISOR_iret                 23
#define __HYPERVISOR_vcpu_op              24
#define __HYPERVISOR_set_segment_base     25
#define __HYPERVISOR_mmuext_op            26
#define __HYPERVISOR_acm_op               27
#define __HYPERVISOR_nmi_op               28
#define __HYPERVISOR_sched_op             29
#define __HYPERVISOR_callback_op          30
#define __HYPERVISOR_xenoprof_op          31
#define __HYPERVISOR_event_channel_op     32
#define __HYPERVISOR_physdev_op           33
#define __HYPERVISOR_hvm_op               34
#define __HYPERVISOR_tmem_op              38
#define __HYPERVISOR_arch_0               48
#define __HYPERVISOR_arch_1               49
#define __HYPERVISOR_arch_2               50
#define __HYPERVISOR_arch_3               51
#define __HYPERVISOR_arch_4               52
#define __HYPERVISOR_arch_5               53
#define __HYPERVISOR_arch_6               54
#define __HYPERVISOR_arch_7               55
#define VIRQ_TIMER      0
#define VIRQ_DEBUG      1
#define VIRQ_CONSOLE    2
#define VIRQ_DOM_EXC    3
#define VIRQ_DEBUGGER   6
#define VIRQ_ARCH_0    16
#define VIRQ_ARCH_1    17
#define VIRQ_ARCH_2    18
#define VIRQ_ARCH_3    19
#define VIRQ_ARCH_4    20
#define VIRQ_ARCH_5    21
#define VIRQ_ARCH_6    22
#define VIRQ_ARCH_7    23
#define NR_VIRQS       24
#define MMU_NORMAL_PT_UPDATE      0
#define MMU_MACHPHYS_UPDATE       1
#define MMU_PT_UPDATE_PRESERVE_AD 2
#define MMUEXT_PIN_L1_TABLE      0
#define MMUEXT_PIN_L2_TABLE      1
#define MMUEXT_PIN_L3_TABLE      2
#define MMUEXT_PIN_L4_TABLE      3
#define MMUEXT_UNPIN_TABLE       4
#define MMUEXT_NEW_BASEPTR       5
#define MMUEXT_TLB_FLUSH_LOCAL   6
#define MMUEXT_INVLPG_LOCAL      7
#define MMUEXT_TLB_FLUSH_MULTI   8
#define MMUEXT_INVLPG_MULTI      9
#define MMUEXT_TLB_FLUSH_ALL    10
#define MMUEXT_INVLPG_ALL       11
#define MMUEXT_FLUSH_CACHE      12
#define MMUEXT_SET_LDT          13
#define MMUEXT_NEW_USER_BASEPTR 15
struct mmuext_op ;
DEFINE_GUEST_HANDLE_STRUCT(mmuext_op);
#define UVMF_NONE               (0UL<<0)
#define UVMF_TLB_FLUSH          (1UL<<0)
#define UVMF_INVLPG             (2UL<<0)
#define UVMF_FLUSHTYPE_MASK     (3UL<<0)
#define UVMF_MULTI              (0UL<<2)
#define UVMF_LOCAL              (0UL<<2)
#define UVMF_ALL                (1UL<<2)
#define CONSOLEIO_write         0
#define CONSOLEIO_read          1
#define VMASST_CMD_enable                0
#define VMASST_CMD_disable               1
#define VMASST_TYPE_4gb_segments         0
#define VMASST_TYPE_4gb_segments_notify  1
#define VMASST_TYPE_writable_pagetables  2
#define VMASST_TYPE_pae_extended_cr3     3
#define MAX_VMASST_TYPE 3
typedef uint16_t domid_t;
#define DOMID_FIRST_RESERVED (0x7FF0U)
#define DOMID_SELF (0x7FF0U)
#define DOMID_IO   (0x7FF1U)
#define DOMID_XEN  (0x7FF2U)
struct mmu_update ;
DEFINE_GUEST_HANDLE_STRUCT(mmu_update);
struct multicall_entry ;
DEFINE_GUEST_HANDLE_STRUCT(multicall_entry);
#define NR_EVENT_CHANNELS (sizeof(unsigned long) * sizeof(unsigned long) * 64)
struct vcpu_time_info ;
struct vcpu_info ;
struct shared_info ;
#define MAX_GUEST_CMDLINE 1024
struct start_info ;
struct dom0_vga_console_info ;
#define SIF_PRIVILEGED    (1<<0)
#define SIF_INITDOMAIN    (1<<1)
typedef uint64_t cpumap_t;
typedef uint8_t xen_domain_handle_t[16];
#define __mk_unsigned_long(x) x ## UL
#define mk_unsigned_long(x) __mk_unsigned_long(x)
#define TMEM_SPEC_VERSION 1
struct tmem_op ;
#define mk_unsigned_long(x) x
