typedef struct yasm_objfmt_elf  yasm_objfmt_elf;
typedef struct  elf_objfmt_output_info;
typedef struct  build_symtab_info;
yasm_objfmt_module yasm_elf_LTX_objfmt;
yasm_objfmt_module yasm_elf32_LTX_objfmt;
yasm_objfmt_module yasm_elf64_LTX_objfmt;
yasm_objfmt_module yasm_elfx32_LTX_objfmt;
elf_objfmt_symtab_append
build_extern
struct elf_build_global_data ;
elf_global_helper_valparam
elf_global_helper_vis
build_global
build_common
elf_objfmt_build_symtab
elf_objfmt_create_common
elf_objfmt_create
elf32_objfmt_create
elf64_objfmt_create
elfx32_objfmt_create
elf_objfmt_output_align
elf_objfmt_output_reloc
elf_objfmt_output_value
elf_objfmt_output_bytecode
elf_objfmt_output_section
elf_objfmt_output_secthead
elf_objfmt_output
elf_objfmt_destroy
elf_objfmt_init_new_section
elf_objfmt_add_default_section
struct elf_section_switch_data ;
elf_helper_gasflags
elf_objfmt_section_switch
elf_objfmt_get_special_sym
dir_type
dir_size
dir_weak
dir_ident
static const char *elf_objfmt_dbgfmt_keywords[] = ;
static const yasm_directive elf_objfmt_directives[] = ;
static const char *elf_nasm_stdmac[] = ;
static const yasm_stdmac elf_objfmt_stdmacs[] = ;
yasm_objfmt_module yasm_elf_LTX_objfmt = ;
yasm_objfmt_module yasm_elf32_LTX_objfmt = ;
yasm_objfmt_module yasm_elf64_LTX_objfmt = ;
yasm_objfmt_module yasm_elfx32_LTX_objfmt = ;
