#define YASM_OBJFMT_ELF_INTERNAL
elf_section_data_destroy;
elf_secthead_print;
const yasm_assoc_data_callback elf_section_data = ;
elf_symrec_data_destroy;
elf_symtab_entry_print;
elf_ssym_symtab_entry_print;
const yasm_assoc_data_callback elf_symrec_data = ;
const yasm_assoc_data_callback elf_ssym_symrec_data = ;
extern elf_machine_handler
elf_machine_handler_x86_x86,
elf_machine_handler_x86_amd64,
elf_machine_handler_x86_x32;
static const elf_machine_handler *elf_machine_handlers[] =
;
static const elf_machine_handler elf_null_machine = ;
static elf_machine_handler const *elf_march = &elf_null_machine;
static yasm_symrec **elf_ssyms;
elf_set_arch
elf_get_special_sym
elf_ssym_has_flag;
elf_is_wrt_sym_relative
elf_is_wrt_pos_adjusted
elf_ssym_has_flag
elf_reloc_entry_create
elf_reloc_entry_destroy
elf_strtab_entry_create
elf_strtab_entry_set_str
elf_strtab_create
elf_strtab_append_str
elf_strtab_destroy
elf_strtab_output_to_file
elf_symtab_entry_create
elf_symtab_entry_destroy
elf_symrec_data_destroy
elf_symtab_entry_print
elf_ssym_symtab_entry_print
elf_symtab_create
elf_symtab_append_entry
elf_symtab_insert_local_sym
elf_symtab_destroy
elf_symtab_assign_indices
elf_symtab_write_to_file
elf_symtab_set_nonzero
elf_sym_set_visibility
elf_sym_set_type
elf_sym_set_size
elf_sym_in_table
elf_secthead_create
elf_secthead_destroy
elf_section_data_destroy
elf_secthead_print
elf_secthead_write_to_file
elf_secthead_append_reloc
elf_secthead_name_reloc_section
elf_handle_reloc_addend
elf_secthead_write_rel_to_file
elf_secthead_write_relocs_to_file
elf_secthead_get_type
elf_secthead_set_typeflags
elf_secthead_is_empty
elf_secthead_get_sym
elf_secthead_get_index
elf_secthead_get_align
elf_secthead_set_align
elf_secthead_set_info
elf_secthead_set_index
elf_secthead_set_link
elf_secthead_set_rel_index
elf_secthead_set_rel_name
elf_secthead_set_entsize
elf_secthead_set_sym
elf_secthead_add_size
elf_secthead_set_file_offset
elf_proghead_get_size
elf_proghead_write_to_file
