const char *empty_argv[] = ;
void argv_array_init(struct argv_array *array)
static void argv_array_push_nodup(struct argv_array *array, const char *value)
void argv_array_push(struct argv_array *array, const char *value)
void argv_array_pushf(struct argv_array *array, const char *fmt, ...)
void argv_array_pushl(struct argv_array *array, ...)
void argv_array_pop(struct argv_array *array)
void argv_array_clear(struct argv_array *array)
const char **argv_array_detach(struct argv_array *array, int *argc)
void argv_array_free_detached(const char **argv)
