static void flush(struct sha1file *f, const void *buf, unsigned int count)
void sha1flush(struct sha1file *f)
int sha1close(struct sha1file *f, unsigned char *result, unsigned int flags)
void sha1write(struct sha1file *f, const void *buf, unsigned int count)
struct sha1file *sha1fd(int fd, const char *name)
struct sha1file *sha1fd_check(const char *name)
struct sha1file *sha1fd_throughput(int fd, const char *name, struct progress *tp)
void sha1file_checkpoint(struct sha1file *f, struct sha1file_checkpoint *checkpoint)
int sha1file_truncate(struct sha1file *f, struct sha1file_checkpoint *checkpoint)
void crc32_begin(struct sha1file *f)
uint32_t crc32_end(struct sha1file *f)
