static int get_st_mode_bits(const char *path, int *mode)
static char bad_path[] = "/bad-path/";
static char *get_pathname(void)
static char *cleanup_path(char *path)
char *mksnpath(char *buf, size_t n, const char *fmt, ...)
static char *vsnpath(char *buf, size_t n, const char *fmt, va_list args)
char *git_snpath(char *buf, size_t n, const char *fmt, ...)
char *git_pathdup(const char *fmt, ...)
char *mkpathdup(const char *fmt, ...)
char *mkpath(const char *fmt, ...)
char *git_path(const char *fmt, ...)
void home_config_paths(char **global, char **xdg, char *file)
char *git_path_submodule(const char *path, const char *fmt, ...)
int validate_headref(const char *path)
static struct passwd *getpw_str(const char *username, size_t len)
char *expand_user_path(const char *path)
const char *enter_repo(const char *path, int strict)
static int calc_shared_perm(int mode)
int adjust_shared_perm(const char *path)
static int have_same_root(const char *path1, const char *path2)
const char *relative_path(const char *in, const char *prefix,
struct strbuf *sb)
const char *remove_leading_path(const char *in, const char *prefix)
int normalize_path_copy_len(char *dst, const char *src, int *prefix_len)
int normalize_path_copy(char *dst, const char *src)
int longest_ancestor_length(const char *path, struct string_list *prefixes)
static inline int chomp_trailing_dir_sep(const char *path, int len)
char *strip_path_suffix(const char *path, const char *suffix)
int daemon_avoid_alias(const char *p)
int offset_1st_component(const char *path)
static int only_spaces_and_periods(const char *path, size_t len, size_t skip)
int is_ntfs_dotgit(const char *name)
