static void do_nothing(size_t size)
static void (*try_to_free_routine)(size_t size) = do_nothing;
static void memory_limit_check(size_t size)
try_to_free_t set_try_to_free_routine(try_to_free_t routine)
char *xstrdup(const char *str)
void *xmalloc(size_t size)
void *xmallocz(size_t size)
void *xmemdupz(const void *data, size_t len)
char *xstrndup(const char *str, size_t len)
void *xrealloc(void *ptr, size_t size)
void *xcalloc(size_t nmemb, size_t size)
#define MAX_IO_SIZE (8*1024*1024)
ssize_t xread(int fd, void *buf, size_t len)
ssize_t xwrite(int fd, const void *buf, size_t len)
ssize_t xpread(int fd, void *buf, size_t len, off_t offset)
ssize_t read_in_full(int fd, void *buf, size_t count)
ssize_t write_in_full(int fd, const void *buf, size_t count)
ssize_t pread_in_full(int fd, void *buf, size_t count, off_t offset)
int xdup(int fd)
FILE *xfdopen(int fd, const char *mode)
int xmkstemp(char *template)
int git_mkstemp(char *path, size_t len, const char *template)
int git_mkstemps(char *path, size_t len, const char *template, int suffix_len)
#undef TMP_MAX
#define TMP_MAX 16384
int git_mkstemps_mode(char *pattern, int suffix_len, int mode)
int git_mkstemp_mode(char *pattern, int mode)
int gitmkstemps(char *pattern, int suffix_len)
int xmkstemp_mode(char *template, int mode)
static int warn_if_unremovable(const char *op, const char *file, int rc)
int unlink_or_warn(const char *file)
int rmdir_or_warn(const char *file)
int remove_or_warn(unsigned int mode, const char *file)
void warn_on_inaccessible(const char *path)
static int access_error_is_ok(int err, unsigned flag)
int access_or_warn(const char *path, int mode, unsigned flag)
int access_or_die(const char *path, int mode, unsigned flag)
struct passwd *xgetpwuid_self(void)
