#define PyMac_PRECHECK(rtn) do  while(0)
extern PyObject *_MenuObj_New(MenuHandle);
extern int _MenuObj_Convert(PyObject *, MenuHandle *);
#define MenuObj_New _MenuObj_New
#define MenuObj_Convert _MenuObj_Convert
#define as_Menu(h) ((MenuHandle)h)
#define as_Resource(h) ((Handle)h)
PyObject *OptMenuObj_New(MenuRef itself)
int OptMenuObj_Convert(PyObject *v, MenuRef *p_itself)
static PyObject *Menu_Error;
PyTypeObject Menu_Type;
#define MenuObj_Check(x) ((x)->ob_type == &Menu_Type || PyObject_TypeCheck((x), &Menu_Type))
typedef struct MenuObject  MenuObject;
PyObject *MenuObj_New(MenuHandle itself)
int MenuObj_Convert(PyObject *v, MenuHandle *p_itself)
static void MenuObj_dealloc(MenuObject *self)
static PyObject *MenuObj_DisposeMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_CalcMenuSize(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_CountMenuItems(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuFont(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuFont(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuExcludesMarkColumn(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuExcludesMarkColumn(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_IsValidMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuRetainCount(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_RetainMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_ReleaseMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_DuplicateMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_CopyMenuTitleAsCFString(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuTitleWithCFString(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_InvalidateMenuSize(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_IsMenuSizeInvalid(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_MacAppendMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_InsertResMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_AppendResMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_MacInsertMenuItem(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_DeleteMenuItem(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_InsertFontResMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_InsertIntlResMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_AppendMenuItemText(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_InsertMenuItemText(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_CopyMenuItems(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_DeleteMenuItems(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_AppendMenuItemTextWithCFString(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_InsertMenuItemTextWithCFString(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_PopUpMenuSelect(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_InvalidateMenuEnabling(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_IsMenuBarInvalid(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_MacInsertMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetRootMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_MacCheckMenuItem(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuItemText(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuItemText(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetItemMark(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetItemMark(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetItemCmd(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetItemCmd(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetItemIcon(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetItemIcon(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetItemStyle(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetItemStyle(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuItemCommandID(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuItemCommandID(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuItemModifiers(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuItemModifiers(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuItemIconHandle(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuItemIconHandle(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuItemTextEncoding(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuItemTextEncoding(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuItemHierarchicalID(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuItemHierarchicalID(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuItemFontID(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuItemFontID(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuItemRefCon(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuItemRefCon(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuItemKeyGlyph(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuItemKeyGlyph(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_MacEnableMenuItem(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_DisableMenuItem(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_IsMenuItemEnabled(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_EnableMenuItemIcon(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_DisableMenuItemIcon(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_IsMenuItemIconEnabled(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuItemHierarchicalMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuItemHierarchicalMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_CopyMenuItemTextAsCFString(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuItemTextWithCFString(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuItemIndent(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuItemIndent(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuItemCommandKey(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuItemCommandKey(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuItemPropertyAttributes(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_ChangeMenuItemPropertyAttributes(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuAttributes(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_ChangeMenuAttributes(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuItemAttributes(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_ChangeMenuItemAttributes(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_DisableAllMenuItems(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_EnableAllMenuItems(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_MenuHasEnabledItems(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuType(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_CountMenuItemsWithCommandID(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetIndMenuItemWithCommandID(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_EnableMenuCommand(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_DisableMenuCommand(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_IsMenuCommandEnabled(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuCommandMark(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuCommandMark(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuCommandPropertySize(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_RemoveMenuCommandProperty(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_IsMenuItemInvalid(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_InvalidateMenuItems(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_UpdateInvalidMenuItems(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_CreateStandardFontMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_UpdateStandardFontMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetFontFamilyFromMenuSelection(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuID(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuWidth(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_GetMenuHeight(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuID(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuWidth(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_SetMenuHeight(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_as_Resource(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_AppendMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_InsertMenu(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_InsertMenuItem(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_EnableMenuItem(MenuObject *_self, PyObject *_args)
static PyObject *MenuObj_CheckMenuItem(MenuObject *_self, PyObject *_args)
static PyMethodDef MenuObj_methods[] = ;
#define MenuObj_getsetlist NULL
#define MenuObj_compare NULL
#define MenuObj_repr NULL
#define MenuObj_hash NULL
#define MenuObj_tp_init 0
#define MenuObj_tp_alloc PyType_GenericAlloc
static PyObject *MenuObj_tp_new(PyTypeObject *type, PyObject *_args, PyObject *_kwds)
#define MenuObj_tp_free PyObject_Del
PyTypeObject Menu_Type = ;
static PyObject *Menu_NewMenu(PyObject *_self, PyObject *_args)
static PyObject *Menu_MacGetMenu(PyObject *_self, PyObject *_args)
static PyObject *Menu_CreateNewMenu(PyObject *_self, PyObject *_args)
static PyObject *Menu_MenuKey(PyObject *_self, PyObject *_args)
static PyObject *Menu_MenuSelect(PyObject *_self, PyObject *_args)
static PyObject *Menu_MenuChoice(PyObject *_self, PyObject *_args)
static PyObject *Menu_MenuEvent(PyObject *_self, PyObject *_args)
static PyObject *Menu_GetMBarHeight(PyObject *_self, PyObject *_args)
static PyObject *Menu_MacDrawMenuBar(PyObject *_self, PyObject *_args)
static PyObject *Menu_InvalMenuBar(PyObject *_self, PyObject *_args)
static PyObject *Menu_HiliteMenu(PyObject *_self, PyObject *_args)
static PyObject *Menu_GetNewMBar(PyObject *_self, PyObject *_args)
static PyObject *Menu_GetMenuBar(PyObject *_self, PyObject *_args)
static PyObject *Menu_SetMenuBar(PyObject *_self, PyObject *_args)
static PyObject *Menu_DuplicateMenuBar(PyObject *_self, PyObject *_args)
static PyObject *Menu_DisposeMenuBar(PyObject *_self, PyObject *_args)
static PyObject *Menu_GetMenuHandle(PyObject *_self, PyObject *_args)
static PyObject *Menu_MacDeleteMenu(PyObject *_self, PyObject *_args)
static PyObject *Menu_ClearMenuBar(PyObject *_self, PyObject *_args)
static PyObject *Menu_SetMenuFlashCount(PyObject *_self, PyObject *_args)
static PyObject *Menu_FlashMenuBar(PyObject *_self, PyObject *_args)
static PyObject *Menu_IsMenuBarVisible(PyObject *_self, PyObject *_args)
static PyObject *Menu_ShowMenuBar(PyObject *_self, PyObject *_args)
static PyObject *Menu_HideMenuBar(PyObject *_self, PyObject *_args)
static PyObject *Menu_AcquireRootMenu(PyObject *_self, PyObject *_args)
static PyObject *Menu_DeleteMCEntries(PyObject *_self, PyObject *_args)
static PyObject *Menu_InitContextualMenus(PyObject *_self, PyObject *_args)
static PyObject *Menu_IsShowContextualMenuClick(PyObject *_self, PyObject *_args)
static PyObject *Menu_LMGetTheMenu(PyObject *_self, PyObject *_args)
static PyObject *Menu_as_Menu(PyObject *_self, PyObject *_args)
static PyObject *Menu_GetMenu(PyObject *_self, PyObject *_args)
static PyObject *Menu_DeleteMenu(PyObject *_self, PyObject *_args)
static PyObject *Menu_DrawMenuBar(PyObject *_self, PyObject *_args)
static PyObject *Menu_CountMenuItemsWithCommandID(PyObject *_self, PyObject *_args)
static PyObject *Menu_GetIndMenuItemWithCommandID(PyObject *_self, PyObject *_args)
static PyObject *Menu_EnableMenuCommand(PyObject *_self, PyObject *_args)
static PyObject *Menu_DisableMenuCommand(PyObject *_self, PyObject *_args)
static PyObject *Menu_IsMenuCommandEnabled(PyObject *_self, PyObject *_args)
static PyObject *Menu_SetMenuCommandMark(PyObject *_self, PyObject *_args)
static PyObject *Menu_GetMenuCommandMark(PyObject *_self, PyObject *_args)
static PyObject *Menu_GetMenuCommandPropertySize(PyObject *_self, PyObject *_args)
static PyObject *Menu_RemoveMenuCommandProperty(PyObject *_self, PyObject *_args)
static PyMethodDef Menu_methods[] = ;
void init_Menu(void)
