#define inia100_REVID "Initio INI-A100U2W SCSI device driver; Revision: 1.02d"
#if 1
#define ORC_MAXQUEUE		245
#define ORC_MAXTAGS		64
#define ORC_MAXQUEUE		25
#define ORC_MAXTAGS		8
#define TOTAL_SG_ENTRY		32
#define MAX_TARGETS		16
#define IMAX_CDB			15
#define SENSE_SIZE		14
struct orc_sgent ;
#define DISC_NOT_ALLOW          0x80
#define DISC_ALLOW              0xC0
#define ORC_OFFSET_SCB			16
#define ORC_MAX_SCBS		    250
#define MAX_CHANNELS       2
#define MAX_ESCB_ELE				64
#define TCF_DRV_255_63     0x0400
#define ORC_CMD_NOP		0x00
#define ORC_CMD_VERSION		0x01
#define ORC_CMD_ECHO		0x02
#define ORC_CMD_SET_NVM		0x03
#define ORC_CMD_GET_NVM		0x04
#define ORC_CMD_GET_BUS_STATUS	0x05
#define ORC_CMD_ABORT_SCB	0x06
#define ORC_CMD_ISSUE_SCB	0x07
#define ORC_GINTS	0xA0
#define QINT		0x04
#define ORC_GIMSK	0xA1
#define MQINT		0x04
#define	ORC_GCFG	0xA2
#define EEPRG		0x01
#define	ORC_GSTAT	0xA3
#define WIDEBUS		0x10
#define ORC_HDATA	0xA4
#define ORC_HCTRL	0xA5
#define SCSIRST		0x80
#define HDO			0x40
#define HOSTSTOP		0x02
#define DEVRST		0x01
#define ORC_HSTUS	0xA6
#define HDI			0x02
#define RREADY		0x01
#define	ORC_NVRAM	0xA7
#define SE2CS		0x008
#define SE2CLK		0x004
#define SE2DO		0x002
#define SE2DI		0x001
#define ORC_PQUEUE	0xA8
#define ORC_PQCNT	0xA9
#define ORC_RQUEUE	0xAA
#define ORC_RQUEUECNT	0xAB
#define	ORC_FWBASEADR	0xAC
#define	ORC_EBIOSADR0 0xB0
#define	ORC_EBIOSADR1 0xB1
#define	ORC_EBIOSADR2 0xB2
#define	ORC_EBIOSDATA 0xB3
#define	ORC_SCBSIZE	0xB7
#define	ORC_SCBBASE0	0xB8
#define	ORC_SCBBASE1	0xBC
#define	ORC_RISCCTL	0xE0
#define PRGMRST		0x002
#define DOWNLOAD		0x001
#define	ORC_PRGMCTR0	0xE2
#define	ORC_PRGMCTR1	0xE3
#define	ORC_RISCRAM	0xEC
struct orc_extended_scb ;
struct orc_scb ;
#define ORC_EXECSCSI	0x00
#define ORC_BUSDEVRST	0x01
#define ORCSCB_COMPLETE	0x00
#define ORCSCB_POST	0x01
#define SCF_DISINT	0x01
#define SCF_DIR		0x18
#define SCF_NO_DCHK	0x00
#define SCF_DIN		0x08
#define SCF_DOUT	0x10
#define SCF_NO_XF	0x18
#define SCF_POLL   0x40
#define HOST_SEL_TOUT	0x11
#define HOST_DO_DU	0x12
#define HOST_BUS_FREE	0x13
#define HOST_BAD_PHAS	0x14
#define HOST_INV_CMD	0x16
#define HOST_SCSI_RST	0x1B
#define HOST_DEV_RST	0x1C
#define TARGET_CHK_COND	0x02
#define TARGET_BUSY	0x08
#define TARGET_TAG_FULL	0x28
struct orc_target ;
#define	TCS_DF_NODASD_SUPT	0x20
#define	TCS_DF_NOSCSI_SUPT	0x40
struct orc_host ;
#define HCF_SCSI_RESET	0x01
#define HCF_PARITY    	0x02
#define HCF_LVDS     	0x10
#define TCF_EN_255	    0x08
#define TCF_EN_TAG	    0x10
#define TCF_BUSY	      0x20
#define TCF_DISCONNECT	0x40
#define TCF_SPIN_UP	  0x80
#define	HCS_AF_IGNORE		0x01
#define	HCS_AF_DISABLE_RESET	0x10
#define	HCS_AF_DISABLE_ADPT	0x80
struct orc_nvram ;
#define NBC_BIOSENABLE  0x01
#define NBC_CDROM       0x02
#define NBC_REMOVABLE   0x04
#define NBB_TARGET_MASK 0x0F
#define NBB_CHANL_MASK  0xF0
#define NCC_BUSRESET    0x01
#define NCC_PARITYCHK   0x02
#define NCC_LVDS        0x10
#define NCC_ACTTERM1    0x20
#define NCC_ACTTERM2    0x40
#define NCC_AUTOTERM    0x80
#define NTC_PERIOD      0x07
#define NTC_1GIGA       0x08
#define NTC_NO_SYNC     0x10
#define NTC_NO_WIDESYNC 0x20
#define NTC_DISC_ENABLE 0x40
#define NTC_SPINUP      0x80
#define NBC_DEFAULT     (NBC_ENABLE)
#define NCC_DEFAULT     (NCC_BUSRESET | NCC_AUTOTERM | NCC_PARITYCHK)
#define NCC_MAX_TAGS    0x20
#define NCC_RESET_TIME  0x0A
#define NTC_DEFAULT     (NTC_1GIGA | NTC_NO_WIDESYNC | NTC_DISC_ENABLE)
