#define BOOT_BUF_SIZE   0x1000
#define CRYPT_FEEDTERM  0x8142
#define CRYPT_STARTTERM 0x81a5
#define POF_READY_TIME_OUT_SEC  10
#define POF_BOOT_LOADER_PAGE_SIZE   0x4000
#define POF_BOOT_LOADER_TOTAL_SIZE  (2U*POF_BOOT_LOADER_PAGE_SIZE)
#define POF_BOOT_LOADER_CODE_SIZE   0x0800
#define POF_BOOT_LOADER_OFF_IN_PAGE (POF_BOOT_LOADER_PAGE_SIZE-POF_BOOT_LOADER_CODE_SIZE)
typedef struct PofFileHdr_tag  tPofFileHdr;
typedef struct PofRecHdr_tag  tPofRecHdr;
typedef struct PofTimeStamp_tag  tPofTimeStamp;
#define TAGFILEMAGIC 0x464F501AUL
#define TAG_ABSDATA  0x1000
#define TAG_BOOTDTA  0x1001
#define TAG_COMMENT  0x0020
#define TAG_SYSCALL  0x0021
#define TAG_FLOWCTRL 0x0022
#define TAG_TIMESTMP 0x0010
#define TAG_CABSDATA 0x1100
#define TAG_CBOOTDTA 0x1101
