yasm_arch_module yasm_lc3b_LTX_arch;
lc3b_create
lc3b_destroy
lc3b_get_machine
lc3b_get_address_size
lc3b_set_var
lc3b_get_fill
lc3b_get_reg_size
lc3b_reggroup_get_reg
lc3b_reg_print
lc3b_floatnum_tobytes
lc3b_ea_create_expr
yasm_lc3b__ea_destroy
lc3b_ea_print
static yasm_arch_machine lc3b_machines[] = ;
yasm_arch_module yasm_lc3b_LTX_arch = ;
