static PyObject*
stringlib_isspace(PyObject *self)
static PyObject*
stringlib_isalpha(PyObject *self)
static PyObject*
stringlib_isalnum(PyObject *self)
static PyObject*
stringlib_isdigit(PyObject *self)
static PyObject*
stringlib_islower(PyObject *self)
static PyObject*
stringlib_isupper(PyObject *self)
static PyObject*
stringlib_istitle(PyObject *self)
static PyObject*
stringlib_lower(PyObject *self)
static PyObject*
stringlib_upper(PyObject *self)
static PyObject*
stringlib_title(PyObject *self)
static PyObject*
stringlib_capitalize(PyObject *self)
static PyObject*
stringlib_swapcase(PyObject *self)
