swri_oldapi_conv_flt_to_s16_neon;
swri_oldapi_conv_fltp_to_s16_2ch_neon;
swri_oldapi_conv_fltp_to_s16_nch_neon;
conv_flt_to_s16_neon
conv_fltp_to_s16_2ch_neon
conv_fltp_to_s16_nch_neon
swri_audio_convert_init_aarch64
