static void __init zap_identity_mappings(void)
static void __init clear_bss(void)
static void __init copy_bootdata(char *real_mode_data)
void __init x86_64_start_kernel(char * real_mode_data)
void __init x86_64_start_reservations(char *real_mode_data)
