#define _INCLUDED_CYANMEDIA_H_
#define cy_an_media_nand cy_as_media_nand
#define cy_an_media_sd_flash cy_as_media_sd_flash
#define cy_an_media_mmc_flash cy_as_media_mmc_flash
#define cy_an_media_ce_ata cy_as_media_ce_ata
#define cy_an_media_sdio cy_as_media_sdio
#define cy_an_media_max_media_value \
cy_as_media_max_media_value
typedef cy_as_media_type cy_an_media_type;
