#define __INCLUDED_CYASMISC_DEP_H__
EXTERN cy_as_return_status_t
cy_as_misc_acquire_resource_dep(cy_as_device_handle handle,
cy_as_resource_type resource,
cy_bool force);
EXTERN cy_as_return_status_t
cy_as_misc_get_firmware_version_dep(cy_as_device_handle handle,
uint16_t *major,
uint16_t *minor,
uint16_t *build,
uint8_t *media_type,
cy_bool *is_debug_mode);
EXTERN cy_as_return_status_t
cy_as_misc_set_trace_level_dep(cy_as_device_handle handle,
uint8_t level,
cy_as_media_type media,
uint32_t device,
uint32_t unit,
cy_as_function_callback cb,
uint32_t client);
