void FPU_pop(void)
int FPU_gettag0(void)
int FPU_gettagi(int stnr)
int FPU_gettag(int regnr)
void FPU_settag0(int tag)
void FPU_settagi(int stnr, int tag)
void FPU_settag(int regnr, int tag)
int FPU_Special(FPU_REG const *ptr)
int isNaN(FPU_REG const *ptr)
int FPU_empty_i(int stnr)
int FPU_stackoverflow(FPU_REG ** st_new_ptr)
void FPU_copy_to_regi(FPU_REG const *r, u_char tag, int stnr)
void FPU_copy_to_reg1(FPU_REG const *r, u_char tag)
void FPU_copy_to_reg0(FPU_REG const *r, u_char tag)
