static int compare(FPU_REG const *b, int tagb)
int FPU_compare_st_data(FPU_REG const *loaded_data, u_char loaded_tag)
static int compare_st_st(int nr)
static int compare_u_st_st(int nr)
void fcom_st(void)
void fcompst(void)
void fcompp(void)
void fucom_(void)
void fucomp(void)
void fucompp(void)
