void zfcp_unit_scsi_scan(struct zfcp_unit *unit)
static void zfcp_unit_scsi_scan_work(struct work_struct *work)
void zfcp_unit_queue_scsi_scan(struct zfcp_port *port)
static struct zfcp_unit *_zfcp_unit_find(struct zfcp_port *port, u64 fcp_lun)
struct zfcp_unit *zfcp_unit_find(struct zfcp_port *port, u64 fcp_lun)
static void zfcp_unit_release(struct device *dev)
int zfcp_unit_add(struct zfcp_port *port, u64 fcp_lun)
struct scsi_device *zfcp_unit_sdev(struct zfcp_unit *unit)
unsigned int zfcp_unit_sdev_status(struct zfcp_unit *unit)
int zfcp_unit_remove(struct zfcp_port *port, u64 fcp_lun)
