char unload_heads_path[64];
int set_unload_heads_path(char *device)
int valid_disk(void)
void write_int(char *path, int i)
void set_led(int on)
void protect(int seconds)
int on_ac(void)
int lid_open(void)
void ignore_me(void)
int main(int argc, char **argv)
