#define __ASM_ARM_W90X900_REGS_LDM_H
#define REG_LCM_DCCS			(0x00)
#define LCM_DCCS_ENG_RST		(1 << 0)
#define LCM_DCCS_VA_EN			(1 << 1)
#define LCM_DCCS_OSD_EN			(1 << 2)
#define LCM_DCCS_DISP_OUT_EN		(1 << 3)
#define LCM_DCCS_DISP_INT_EN		(1 << 4)
#define LCM_DCCS_CMD_ON			(1 << 5)
#define LCM_DCCS_FIELD_INTR		(1 << 6)
#define LCM_DCCS_SINGLE			(1 << 7)
enum LCM_DCCS_VA_SRC ;
#define REG_LCM_DEV_CTRL		(0x04)
enum LCM_DEV_CTRL_SWAP_YCbCr ;
enum LCM_DEV_CTRL_RGB_SHIFT ;
enum LCM_DEV_CTRL_DEVICE ;
#define LCM_DEV_CTRL_LCD_DDA		(8)
#define LCM_DEV_CTRL_YUV2CCIR		(16)
enum LCM_DEV_CTRL_LCD_SEL ;
enum LCM_DEV_CTRL_FAL_D ;
enum LCM_DEV_CTRL_H_POL ;
enum LCM_DEV_CTRL_V_POL ;
enum LCM_DEV_CTRL_VR_LACE ;
enum LCM_DEV_CTRL_LACE ;
enum LCM_DEV_CTRL_RGB_SCALE ;
enum LCM_DEV_CTRL_DBWORD ;
enum LCM_DEV_CTRL_MPU68 ;
enum LCM_DEV_CTRL_DE_POL ;
#define LCM_DEV_CTRL_CMD16		(29)
#define LCM_DEV_CTRL_CM16t18		(30)
#define LCM_DEV_CTRL_CMD_LOW		(31)
#define REG_LCM_MPU_CMD			(0x08)
#define REG_LCM_INT_CS			(0x0c)
#define LCM_INT_CS_DISP_F_EN		(1 << 0)
#define LCM_INT_CS_UNDERRUN_EN   	(1 << 1)
#define LCM_INT_CS_BUS_ERROR_INT 	(1 << 28)
#define LCM_INT_CS_UNDERRUN_INT  	(1 << 29)
#define LCM_INT_CS_DISP_F_STATUS 	(1 << 30)
#define LCM_INT_CS_DISP_F_INT		(1 << 31)
#define REG_LCM_CRTC_SIZE		(0x10)
#define LCM_CRTC_SIZE_VTTVAL(x)		((x) << 16)
#define LCM_CRTC_SIZE_HTTVAL(x)		((x) << 0)
#define REG_LCM_CRTC_DEND		(0x14)
#define LCM_CRTC_DEND_VDENDVAL(x)	((x) << 16)
#define LCM_CRTC_DEND_HDENDVAL(x)	((x) << 0)
#define REG_LCM_CRTC_HR			(0x18)
#define LCM_CRTC_HR_EVAL(x)		((x) << 16)
#define LCM_CRTC_HR_SVAL(x)		((x) << 0)
#define REG_LCM_CRTC_HSYNC		(0x1C)
#define LCM_CRTC_HSYNC_SHIFTVAL(x)	((x) << 30)
#define LCM_CRTC_HSYNC_EVAL(x)		((x) << 16)
#define LCM_CRTC_HSYNC_SVAL(x)		((x) << 0)
#define REG_LCM_CRTC_VR			(0x20)
#define LCM_CRTC_VR_EVAL(x)		((x) << 16)
#define LCM_CRTC_VR_SVAL(x)		((x) << 0)
#define REG_LCM_VA_BADDR0		(0x24)
#define REG_LCM_VA_BADDR1		(0x28)
#define REG_LCM_VA_FBCTRL		(0x2C)
#define LCM_VA_FBCTRL_IO_REGION_HALF	(1 << 28)
#define LCM_VA_FBCTRL_FIELD_DUAL  	(1 << 29)
#define LCM_VA_FBCTRL_START_BUF 	(1 << 30)
#define LCM_VA_FBCTRL_DB_EN		(1 << 31)
#define REG_LCM_VA_SCALE		(0x30)
#define LCM_VA_SCALE_XCOPY_INTERPOLATION (0 << 15)
#define LCM_VA_SCALE_XCOPY_DUPLICATION	 (1 << 15)
#define REG_LCM_VA_WIN			(0x38)
#define REG_LCM_VA_STUFF		(0x3C)
#define REG_LCM_OSD_WINS		(0x40)
#define REG_LCM_OSD_WINE		(0x44)
#define REG_LCM_OSD_BADDR		(0x48)
#define REG_LCM_OSD_FBCTRL		(0x4c)
#define REG_LCM_OSD_OVERLAY		(0x50)
#define REG_LCM_OSD_CKEY		(0x54)
#define REG_LCM_OSD_CMASK		(0x58)
#define REG_LCM_OSD_SKIP1		(0x5C)
#define REG_LCM_OSD_SKIP2		(0x60)
#define REG_LCM_OSD_SCALE		(0x64)
#define REG_LCM_MPU_VSYNC		(0x68)
#define REG_LCM_HC_CTRL			(0x6C)
#define REG_LCM_HC_POS			(0x70)
#define REG_LCM_HC_WBCTRL		(0x74)
#define REG_LCM_HC_BADDR		(0x78)
#define REG_LCM_HC_COLOR0		(0x7C)
#define REG_LCM_HC_COLOR1		(0x80)
#define REG_LCM_HC_COLOR2		(0x84)
#define REG_LCM_HC_COLOR3		(0x88)
