#if APPLE_SUPPORTS_QUICKTIME
#define PyMac_PRECHECK(rtn) do  while(0)
extern PyObject *_WinObj_New(WindowRef);
extern PyObject *_WinObj_WhichWindow(WindowRef);
extern int _WinObj_Convert(PyObject *, WindowRef *);
#define WinObj_New _WinObj_New
#define WinObj_WhichWindow _WinObj_WhichWindow
#define WinObj_Convert _WinObj_Convert
#define GetWindowUpdateRgn(win, rgn) GetWindowRegion((win), kWindowUpdateRgn, (rgn))
#define GetWindowStructureRgn(win, rgn) GetWindowRegion((win), kWindowStructureRgn, (rgn))
#define GetWindowContentRgn(win, rgn) GetWindowRegion((win), kWindowContentRgn, (rgn))
static void
PyMac_AutoDisposeWindow(WindowPtr w)
static PyObject *Win_Error;
PyTypeObject Window_Type;
#define WinObj_Check(x) ((x)->ob_type == &Window_Type || PyObject_TypeCheck((x), &Window_Type))
typedef struct WindowObject  WindowObject;
PyObject *WinObj_New(WindowPtr itself)
int WinObj_Convert(PyObject *v, WindowPtr *p_itself)
static void WinObj_dealloc(WindowObject *self)
static PyObject *WinObj_GetWindowOwnerCount(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_CloneWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowRetainCount(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_RetainWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_ReleaseWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_ReshapeCustomWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowWidgetHilite(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowClass(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowAttributes(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_ChangeWindowAttributes(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowClass(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowModality(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowModality(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowContentColor(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowContentColor(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowContentPattern(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowContentPattern(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_ScrollWindowRect(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_ScrollWindowRegion(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_ClipAbove(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_PaintOne(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_PaintBehind(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_CalcVis(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_CalcVisBehind(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_BringToFront(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SendBehind(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SelectWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetNextWindowOfClass(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowAlternateTitle(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_CopyWindowAlternateTitle(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_HiliteWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWRefCon(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWRefCon(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowPic(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowPic(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWVariant(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowFeatures(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowRegion(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowStructureWidths(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_BeginUpdate(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_EndUpdate(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_InvalWindowRgn(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_InvalWindowRect(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_ValidWindowRgn(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_ValidWindowRect(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_DrawGrowIcon(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWTitle(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWTitle(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowTitleWithCFString(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_CopyWindowTitleAsCFString(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowProxyFSSpec(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowProxyFSSpec(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowProxyAlias(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowProxyAlias(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowProxyCreatorAndType(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowProxyIcon(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowProxyIcon(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_RemoveWindowProxy(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_BeginWindowProxyDrag(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_EndWindowProxyDrag(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_TrackWindowProxyFromExistingDrag(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_TrackWindowProxyDrag(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_IsWindowModified(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowModified(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_IsWindowPathSelectClick(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_WindowPathSelect(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_HiliteWindowFrameForDrag(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_TransitionWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_TransitionWindowAndParent(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_MacMoveWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SizeWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GrowWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_DragWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_ZoomWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_IsWindowCollapsable(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_IsWindowCollapsed(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_CollapseWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowBounds(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_ResizeWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowBounds(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_RepositionWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_MoveWindowStructure(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_IsWindowInStandardState(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_ZoomWindowIdeal(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowIdealUserState(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowIdealUserState(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowGreatestAreaDevice(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_ConstrainWindowToScreen(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_HideWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_MacShowWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_ShowHide(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_MacIsWindowVisible(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_ShowSheetWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_HideSheetWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetSheetWindowParent(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowPropertyAttributes(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_ChangeWindowPropertyAttributes(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_TrackBox(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_TrackGoAway(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowPort(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowStructurePort(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowKind(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_IsWindowHilited(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_IsWindowUpdatePending(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_MacGetNextWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowStandardState(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowUserState(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowKind(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowStandardState(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetWindowUserState(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_SetPortWindowPort(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowPortBounds(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_IsWindowVisible(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowStructureRgn(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowContentRgn(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetWindowUpdateRgn(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_GetNextWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_MoveWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_ShowWindow(WindowObject *_self, PyObject *_args)
static PyObject *WinObj_AutoDispose(WindowObject *_self, PyObject *_args)
static PyMethodDef WinObj_methods[] = ;
#define WinObj_getsetlist NULL
static int WinObj_compare(WindowObject *self, WindowObject *other)
static PyObject * WinObj_repr(WindowObject *self)
static int WinObj_hash(WindowObject *self)
#define WinObj_tp_init 0
#define WinObj_tp_alloc PyType_GenericAlloc
static PyObject *WinObj_tp_new(PyTypeObject *type, PyObject *_args, PyObject *_kwds)
#define WinObj_tp_free PyObject_Del
PyTypeObject Window_Type = ;
static PyObject *Win_GetNewCWindow(PyObject *_self, PyObject *_args)
static PyObject *Win_NewWindow(PyObject *_self, PyObject *_args)
static PyObject *Win_GetNewWindow(PyObject *_self, PyObject *_args)
static PyObject *Win_NewCWindow(PyObject *_self, PyObject *_args)
static PyObject *Win_CreateNewWindow(PyObject *_self, PyObject *_args)
static PyObject *Win_CreateWindowFromResource(PyObject *_self, PyObject *_args)
static PyObject *Win_ShowFloatingWindows(PyObject *_self, PyObject *_args)
static PyObject *Win_HideFloatingWindows(PyObject *_self, PyObject *_args)
static PyObject *Win_AreFloatingWindowsVisible(PyObject *_self, PyObject *_args)
static PyObject *Win_CheckUpdate(PyObject *_self, PyObject *_args)
static PyObject *Win_MacFindWindow(PyObject *_self, PyObject *_args)
static PyObject *Win_FrontWindow(PyObject *_self, PyObject *_args)
static PyObject *Win_FrontNonFloatingWindow(PyObject *_self, PyObject *_args)
static PyObject *Win_GetFrontWindowOfClass(PyObject *_self, PyObject *_args)
static PyObject *Win_FindWindowOfClass(PyObject *_self, PyObject *_args)
static PyObject *Win_CreateStandardWindowMenu(PyObject *_self, PyObject *_args)
static PyObject *Win_CollapseAllWindows(PyObject *_self, PyObject *_args)
static PyObject *Win_GetAvailableWindowPositioningBounds(PyObject *_self, PyObject *_args)
static PyObject *Win_DisableScreenUpdates(PyObject *_self, PyObject *_args)
static PyObject *Win_EnableScreenUpdates(PyObject *_self, PyObject *_args)
static PyObject *Win_PinRect(PyObject *_self, PyObject *_args)
static PyObject *Win_GetGrayRgn(PyObject *_self, PyObject *_args)
static PyObject *Win_GetWindowFromPort(PyObject *_self, PyObject *_args)
static PyObject *Win_WhichWindow(PyObject *_self, PyObject *_args)
static PyObject *Win_FindWindow(PyObject *_self, PyObject *_args)
static PyMethodDef Win_methods[] = ;
#if APPLE_SUPPORTS_QUICKTIME
PyObject *
WinObj_WhichWindow(WindowPtr w)
void init_Win(void)
