int ql_unpause_mpi_risc(struct ql_adapter *qdev)
int ql_pause_mpi_risc(struct ql_adapter *qdev)
int ql_hard_reset_mpi_risc(struct ql_adapter *qdev)
int ql_read_mpi_reg(struct ql_adapter *qdev, u32 reg, u32 *data)
int ql_write_mpi_reg(struct ql_adapter *qdev, u32 reg, u32 data)
int ql_soft_reset_mpi_risc(struct ql_adapter *qdev)
int ql_own_firmware(struct ql_adapter *qdev)
static int ql_get_mb_sts(struct ql_adapter *qdev, struct mbox_params *mbcp)
static int ql_wait_mbx_cmd_cmplt(struct ql_adapter *qdev)
static int ql_exec_mb_cmd(struct ql_adapter *qdev, struct mbox_params *mbcp)
static int ql_idc_req_aen(struct ql_adapter *qdev)
static int ql_idc_cmplt_aen(struct ql_adapter *qdev)
static void ql_link_up(struct ql_adapter *qdev, struct mbox_params *mbcp)
static void ql_link_down(struct ql_adapter *qdev, struct mbox_params *mbcp)
static int ql_sfp_in(struct ql_adapter *qdev, struct mbox_params *mbcp)
static int ql_sfp_out(struct ql_adapter *qdev, struct mbox_params *mbcp)
static int ql_aen_lost(struct ql_adapter *qdev, struct mbox_params *mbcp)
static void ql_init_fw_done(struct ql_adapter *qdev, struct mbox_params *mbcp)
static int ql_mpi_handler(struct ql_adapter *qdev, struct mbox_params *mbcp)
static int ql_mailbox_command(struct ql_adapter *qdev, struct mbox_params *mbcp)
int ql_mb_about_fw(struct ql_adapter *qdev)
int ql_mb_get_fw_state(struct ql_adapter *qdev)
static int ql_mb_idc_ack(struct ql_adapter *qdev)
int ql_mb_set_port_cfg(struct ql_adapter *qdev)
static int ql_mb_dump_ram(struct ql_adapter *qdev, u64 req_dma, u32 addr,
u32 size)
int ql_dump_risc_ram_area(struct ql_adapter *qdev, void *buf,
u32 ram_addr, int word_count)
int ql_mb_get_port_cfg(struct ql_adapter *qdev)
int ql_mb_wol_mode(struct ql_adapter *qdev, u32 wol)
int ql_mb_wol_set_magic(struct ql_adapter *qdev, u32 enable_wol)
static int ql_idc_wait(struct ql_adapter *qdev)
int ql_mb_set_led_cfg(struct ql_adapter *qdev, u32 led_config)
int ql_mb_get_led_cfg(struct ql_adapter *qdev)
int ql_mb_set_mgmnt_traffic_ctl(struct ql_adapter *qdev, u32 control)
static int ql_mb_get_mgmnt_traffic_ctl(struct ql_adapter *qdev, u32 *control)
int ql_wait_fifo_empty(struct ql_adapter *qdev)
static int ql_set_port_cfg(struct ql_adapter *qdev)
void ql_mpi_port_cfg_work(struct work_struct *work)
void ql_mpi_idc_work(struct work_struct *work)
void ql_mpi_work(struct work_struct *work)
void ql_mpi_reset_work(struct work_struct *work)
