#define _ASM_IRC_REGS
#define __reg(ADDR) (*(volatile unsigned long *)(ADDR))
#define __get_TM0()	()
#define __get_TM1()	()
#define __set_TM1(V)	do  while(0)
#define __set_TM1x(XI,V)			\
do  while(0)
#define __get_RS(C)	()
#define __clr_RC(C)	do  while(0)
#define __get_MASK(C)	()
#define __set_MASK(C)	do  while(0)
#define __clr_MASK(C)	do  while(0)
#define __get_MASK_all() __get_MASK(0)
#define __set_MASK_all() __set_MASK(0)
#define __clr_MASK_all() __clr_MASK(0)
#define __get_IRL()	()
#define __clr_IRL()	do  while(0)
#define __get_IRR(N)	()
#define __set_IRR(N,V)	do  while(0)
#define __get_IITMR(N)	()
#define __set_IITMR(N,V) do  while(0)
