void * __init prom_early_alloc(unsigned long size)
static void __init sun4v_path_component(struct device_node *dp, char *tmp_buf)
static void __init sun4u_path_component(struct device_node *dp, char *tmp_buf)
static void __init sbus_path_component(struct device_node *dp, char *tmp_buf)
static void __init pci_path_component(struct device_node *dp, char *tmp_buf)
static void __init upa_path_component(struct device_node *dp, char *tmp_buf)
static void __init vdev_path_component(struct device_node *dp, char *tmp_buf)
static void __init ebus_path_component(struct device_node *dp, char *tmp_buf)
static void __init i2c_path_component(struct device_node *dp, char *tmp_buf)
static void __init usb_path_component(struct device_node *dp, char *tmp_buf)
static void __init ieee1394_path_component(struct device_node *dp, char *tmp_buf)
static void __init __build_path_component(struct device_node *dp, char *tmp_buf)
char * __init build_path_component(struct device_node *dp)
static const char *get_mid_prop(void)
static void *of_iterate_over_cpus(void *(*func)(struct device_node *, int, int), int arg)
static void *check_cpu_node(struct device_node *dp, int cpuid, int id)
struct device_node *of_find_node_by_cpuid(int cpuid)
static void *record_one_cpu(struct device_node *dp, int cpuid, int arg)
void __init of_populate_present_mask(void)
static void *fill_in_one_cpu(struct device_node *dp, int cpuid, int arg)
void __init of_fill_in_cpu_data(void)
void __init of_console_init(void)
