# define SQLITE_MAX_LENGTH 1000000000
# define SQLITE_MAX_COLUMN 2000
# define SQLITE_MAX_SQL_LENGTH 1000000000
# define SQLITE_MAX_EXPR_DEPTH 1000
# define SQLITE_MAX_COMPOUND_SELECT 500
# define SQLITE_MAX_VDBE_OP 25000
# define SQLITE_MAX_FUNCTION_ARG 100
# define SQLITE_DEFAULT_CACHE_SIZE  2000
# define SQLITE_DEFAULT_TEMP_CACHE_SIZE  500
# define SQLITE_MAX_ATTACHED 10
# define SQLITE_MAX_VARIABLE_NUMBER 999
# define SQLITE_MAX_PAGE_SIZE 32768
# define SQLITE_DEFAULT_PAGE_SIZE 1024
#if SQLITE_DEFAULT_PAGE_SIZE>SQLITE_MAX_PAGE_SIZE
# undef SQLITE_DEFAULT_PAGE_SIZE
# define SQLITE_DEFAULT_PAGE_SIZE SQLITE_MAX_PAGE_SIZE
# define SQLITE_MAX_DEFAULT_PAGE_SIZE 8192
#if SQLITE_MAX_DEFAULT_PAGE_SIZE>SQLITE_MAX_PAGE_SIZE
# undef SQLITE_MAX_DEFAULT_PAGE_SIZE
# define SQLITE_MAX_DEFAULT_PAGE_SIZE SQLITE_MAX_PAGE_SIZE
# define SQLITE_MAX_PAGE_COUNT 1073741823
# define SQLITE_MAX_LIKE_PATTERN_LENGTH 50000
