static void delay(int delay)
static void send_bit(unsigned char bit)
static void send_ack(void)
static void send_byte(unsigned char byte)
static void send_start(void)
static void send_stop(void)
static void do_idle(void)
static int recv_bit(void)
static unsigned char recv_byte(void)
static int recv_ack(void)
int read_eeprom(char *buffer, int eeprom_size, int size)
