ImageWindow::ImageWindow()
void ImageWindow::closeEvent(QCloseEvent *event)
void ImageWindow::open()
bool ImageWindow::save()
bool ImageWindow::saveAs()
void ImageWindow::flipHorizontally()
void ImageWindow::flipVertically()
void ImageWindow::resizeImage()
void ImageWindow::convertTo32Bit()
void ImageWindow::convertTo8Bit()
void ImageWindow::convertTo1Bit()
void ImageWindow::addTransaction(Transaction *transact)
void ImageWindow::about()
void ImageWindow::allTransactionsDone()
void ImageWindow::createActions()
void ImageWindow::createMenus()
bool ImageWindow::okToContinue()
void ImageWindow::loadFile(const QString &fileName)
void ImageWindow::saveFile(const QString &fileName)
void ImageWindow::setCurrentFile(const QString &fileName)
QString ImageWindow::strippedName(const QString &fullFileName)
