ff_scalarproduct_int16_mmxext;
ff_scalarproduct_int16_sse2;
ff_vector_clip_int32_mmx;
ff_vector_clip_int32_sse2;
ff_vector_clip_int32_int_sse2;
ff_vector_clip_int32_sse4;
ff_vector_clipf_sse;
ff_audiodsp_init_x86
