#define AVCODEC_X86_FPEL_H
ff_avg_pixels4_mmx;
ff_avg_pixels4_mmxext;
ff_avg_pixels8_mmx;
ff_avg_pixels8_mmxext;
ff_avg_pixels16_mmx;
ff_avg_pixels16_mmxext;
ff_avg_pixels16_sse2;
ff_put_pixels4_mmx;
ff_put_pixels8_mmx;
ff_put_pixels16_mmx;
ff_put_pixels16_sse2;
