#define AVCODEC_X86_IDCTDSP_H
ff_add_pixels_clamped_mmx;
ff_add_pixels_clamped_sse2;
ff_put_pixels_clamped_mmx;
ff_put_pixels_clamped_sse2;
ff_put_signed_pixels_clamped_mmx;
ff_put_signed_pixels_clamped_sse2;
