#if HAVE_MMX_INLINE
dct_unquantize_h263_intra_mmx
dct_unquantize_h263_inter_mmx
dct_unquantize_mpeg1_intra_mmx
dct_unquantize_mpeg1_inter_mmx
dct_unquantize_mpeg2_intra_mmx
dct_unquantize_mpeg2_inter_mmx
ff_mpv_common_init_x86
