#define AVCODEC_X86_SIMPLE_IDCT_H
ff_simple_idct_mmx;
ff_simple_idct_add_mmx;
ff_simple_idct_put_mmx;
ff_simple_idct10_sse2;
ff_simple_idct10_avx;
ff_simple_idct10_put_sse2;
ff_simple_idct10_put_avx;
ff_simple_idct12_sse2;
ff_simple_idct12_avx;
ff_simple_idct12_put_sse2;
ff_simple_idct12_put_avx;
