#define AVCODEC_X86_XVIDIDCT_H
ff_xvid_idct_mmx;
ff_xvid_idct_mmx_put;
ff_xvid_idct_mmx_add;
ff_xvid_idct_mmxext;
ff_xvid_idct_mmxext_put;
ff_xvid_idct_mmxext_add;
ff_xvid_idct_sse2;
ff_xvid_idct_put_sse2;
ff_xvid_idct_add_sse2;
