#define __IO_H
static inline int in_8(const volatile unsigned char *addr)
static inline void out_8(volatile unsigned char *addr, int val)
static inline unsigned in_le16(const volatile u16 *addr)
static inline unsigned in_be16(const volatile u16 *addr)
static inline void out_le16(volatile u16 *addr, int val)
static inline void out_be16(volatile u16 *addr, int val)
static inline unsigned in_le32(const volatile unsigned *addr)
static inline unsigned in_be32(const volatile unsigned *addr)
static inline void out_le32(volatile unsigned *addr, int val)
static inline void out_be32(volatile unsigned *addr, int val)
static inline void sync(void)
static inline void eieio(void)
static inline void barrier(void)
