static const struct ctrl pb0100_ctrl[] = ;
static struct v4l2_pix_format pb0100_mode[] = ;
static int pb0100_probe(struct sd *sd)
static int pb0100_start(struct sd *sd)
static int pb0100_stop(struct sd *sd)
static void pb0100_disconnect(struct sd *sd)
static int pb0100_init(struct sd *sd)
static int pb0100_dump(struct sd *sd)
static int pb0100_get_gain(struct gspca_dev *gspca_dev, __s32 *val)
static int pb0100_set_gain(struct gspca_dev *gspca_dev, __s32 val)
static int pb0100_get_red_balance(struct gspca_dev *gspca_dev, __s32 *val)
static int pb0100_set_red_balance(struct gspca_dev *gspca_dev, __s32 val)
static int pb0100_get_blue_balance(struct gspca_dev *gspca_dev, __s32 *val)
static int pb0100_set_blue_balance(struct gspca_dev *gspca_dev, __s32 val)
static int pb0100_get_exposure(struct gspca_dev *gspca_dev, __s32 *val)
static int pb0100_set_exposure(struct gspca_dev *gspca_dev, __s32 val)
static int pb0100_get_autogain(struct gspca_dev *gspca_dev, __s32 *val)
static int pb0100_set_autogain(struct gspca_dev *gspca_dev, __s32 val)
static int pb0100_get_autogain_target(struct gspca_dev *gspca_dev, __s32 *val)
static int pb0100_set_autogain_target(struct gspca_dev *gspca_dev, __s32 val)
static int pb0100_get_natural(struct gspca_dev *gspca_dev, __s32 *val)
static int pb0100_set_natural(struct gspca_dev *gspca_dev, __s32 val)
