static void pusher (void *ctx)
static void simult_conn (void *payload)
static void simult_bind (void *payload)
void test_bind_before_connect ()
void test_connect_before_bind ()
void test_connect_before_bind_pub_sub ()
void test_multiple_connects ()
void test_multiple_threads ()
void test_simultaneous_connect_bind_threads ()
void test_identity ()
void test_connect_only ()
void test_unbind ()
int main (void)
