#define AVFILTER_BUFFERSRC_H
enum ;
av_buffersrc_get_nb_failed_requests;
typedef struct AVBufferSrcParameters  AVBufferSrcParameters;
*av_buffersrc_parameters_alloc;
av_buffersrc_parameters_set;
av_warn_unused_result
av_buffersrc_write_frame;
av_warn_unused_result
av_buffersrc_add_frame;
av_warn_unused_result
av_buffersrc_add_frame_flags;
