#define AVFILTER_BUFFERSINK_H
av_buffersink_get_frame_flags;
#define AV_BUFFERSINK_FLAG_PEEK 1
#define AV_BUFFERSINK_FLAG_NO_REQUEST 2
typedef struct  AVBufferSinkParams;
*av_buffersink_params_alloc;
typedef struct  AVABufferSinkParams;
*av_abuffersink_params_alloc;
av_buffersink_set_frame_size;
av_buffersink_get_frame_rate;
av_buffersink_get_frame;
av_buffersink_get_samples;
