#define AVFILTER_DESHAKE_OPENCL_KERNEL_H
const char *ff_kernel_deshake_opencl = AV_OPENCL_KERNEL(
pixel
interpolate_nearest
interpolate_bilinear
interpolate_biquadratic
clipf
mirror
avfilter_transform_luma
avfilter_transform_chroma
);
