static struct str_node *str_node__new(const char *s, bool dupstr)
static void str_node__delete(struct str_node *self, bool dupstr)
int strlist__add(struct strlist *self, const char *new_entry)
int strlist__load(struct strlist *self, const char *filename)
void strlist__remove(struct strlist *self, struct str_node *sn)
struct str_node *strlist__find(struct strlist *self, const char *entry)
static int strlist__parse_list_entry(struct strlist *self, const char *s)
int strlist__parse_list(struct strlist *self, const char *s)
struct strlist *strlist__new(bool dupstr, const char *slist)
void strlist__delete(struct strlist *self)
struct str_node *strlist__entry(const struct strlist *self, unsigned int idx)
