static int filter(const struct dirent *dir)
struct thread_map *thread_map__new_by_pid(pid_t pid)
struct thread_map *thread_map__new_by_tid(pid_t tid)
struct thread_map *thread_map__new(pid_t pid, pid_t tid)
void thread_map__delete(struct thread_map *threads)
