static void add_ordered_member(struct dlm_ls *ls, struct dlm_member *new)
static int dlm_add_member(struct dlm_ls *ls, int nodeid)
static void dlm_remove_member(struct dlm_ls *ls, struct dlm_member *memb)
int dlm_is_member(struct dlm_ls *ls, int nodeid)
int dlm_is_removed(struct dlm_ls *ls, int nodeid)
static void clear_memb_list(struct list_head *head)
void dlm_clear_members(struct dlm_ls *ls)
void dlm_clear_members_gone(struct dlm_ls *ls)
static void make_member_array(struct dlm_ls *ls)
static int ping_members(struct dlm_ls *ls)
int dlm_recover_members(struct dlm_ls *ls, struct dlm_recover *rv, int *neg_out)
int dlm_ls_stop(struct dlm_ls *ls)
int dlm_ls_start(struct dlm_ls *ls)
