static int rcom_response(struct dlm_ls *ls)
static int create_rcom(struct dlm_ls *ls, int to_nodeid, int type, int len,
struct dlm_rcom **rc_ret, struct dlm_mhandle **mh_ret)
static void send_rcom(struct dlm_ls *ls, struct dlm_mhandle *mh,
struct dlm_rcom *rc)
static void make_config(struct dlm_ls *ls, struct rcom_config *rf)
static int check_config(struct dlm_ls *ls, struct dlm_rcom *rc, int nodeid)
static void allow_sync_reply(struct dlm_ls *ls, uint64_t *new_seq)
static void disallow_sync_reply(struct dlm_ls *ls)
int dlm_rcom_status(struct dlm_ls *ls, int nodeid)
static void receive_rcom_status(struct dlm_ls *ls, struct dlm_rcom *rc_in)
static void receive_sync_reply(struct dlm_ls *ls, struct dlm_rcom *rc_in)
int dlm_rcom_names(struct dlm_ls *ls, int nodeid, char *last_name, int last_len)
static void receive_rcom_names(struct dlm_ls *ls, struct dlm_rcom *rc_in)
int dlm_send_rcom_lookup(struct dlm_rsb *r, int dir_nodeid)
static void receive_rcom_lookup(struct dlm_ls *ls, struct dlm_rcom *rc_in)
static void receive_rcom_lookup_reply(struct dlm_ls *ls, struct dlm_rcom *rc_in)
static void pack_rcom_lock(struct dlm_rsb *r, struct dlm_lkb *lkb,
struct rcom_lock *rl)
int dlm_send_rcom_lock(struct dlm_rsb *r, struct dlm_lkb *lkb)
static void receive_rcom_lock(struct dlm_ls *ls, struct dlm_rcom *rc_in)
int dlm_send_ls_not_ready(int nodeid, struct dlm_rcom *rc_in)
static int is_old_reply(struct dlm_ls *ls, struct dlm_rcom *rc)
void dlm_receive_rcom(struct dlm_ls *ls, struct dlm_rcom *rc, int nodeid)
