static void dlm_wait_timer_fn(unsigned long data)
int dlm_wait_function(struct dlm_ls *ls, int (*testfn) (struct dlm_ls *ls))
uint32_t dlm_recover_status(struct dlm_ls *ls)
void dlm_set_recover_status(struct dlm_ls *ls, uint32_t status)
static int wait_status_all(struct dlm_ls *ls, uint32_t wait_status)
static int wait_status_low(struct dlm_ls *ls, uint32_t wait_status)
static int wait_status(struct dlm_ls *ls, uint32_t status)
int dlm_recover_members_wait(struct dlm_ls *ls)
int dlm_recover_directory_wait(struct dlm_ls *ls)
int dlm_recover_locks_wait(struct dlm_ls *ls)
int dlm_recover_done_wait(struct dlm_ls *ls)
static int recover_list_empty(struct dlm_ls *ls)
static void recover_list_add(struct dlm_rsb *r)
static void recover_list_del(struct dlm_rsb *r)
static struct dlm_rsb *recover_list_find(struct dlm_ls *ls, uint64_t id)
static void recover_list_clear(struct dlm_ls *ls)
static void set_lock_master(struct list_head *queue, int nodeid)
static void set_master_lkbs(struct dlm_rsb *r)
static void set_new_master(struct dlm_rsb *r, int nodeid)
static int recover_master(struct dlm_rsb *r)
static int recover_master_static(struct dlm_rsb *r)
int dlm_recover_masters(struct dlm_ls *ls)
int dlm_recover_master_reply(struct dlm_ls *ls, struct dlm_rcom *rc)
static int recover_locks_queue(struct dlm_rsb *r, struct list_head *head)
static int recover_locks(struct dlm_rsb *r)
int dlm_recover_locks(struct dlm_ls *ls)
void dlm_recovered_lock(struct dlm_rsb *r)
static void recover_lvb(struct dlm_rsb *r)
static void recover_conversion(struct dlm_rsb *r)
static void set_locks_purged(struct dlm_rsb *r)
void dlm_recover_rsbs(struct dlm_ls *ls)
int dlm_create_root_list(struct dlm_ls *ls)
void dlm_release_root_list(struct dlm_ls *ls)
void dlm_clear_toss_list(struct dlm_ls *ls)
