#define phy_version_h_
#define	PHY_MAJOR_VERSION		1
#define	PHY_MINOR_VERSION		82
#define	PHY_RC_NUMBER		8
#define	PHY_INCREMENTAL_NUMBER	0
#define	PHY_BUILD_NUMBER		0
#define	PHY_VERSION
#define	PHY_VERSION_NUM		0x01520800
#define	PHY_VERSION_STR		"1.82.8.0"
