x86_bc_insn_destroy;
x86_bc_insn_print;
x86_bc_insn_calc_len;
x86_bc_insn_expand;
x86_bc_insn_tobytes;
x86_bc_jmp_destroy;
x86_bc_jmp_print;
x86_bc_jmp_calc_len;
x86_bc_jmp_expand;
x86_bc_jmp_tobytes;
x86_bc_jmpfar_destroy;
x86_bc_jmpfar_print;
x86_bc_jmpfar_calc_len;
static int x86_bc_jmpfar_tobytes
(yasm_bytecode *bc, unsigned char **bufp, unsigned char *bufstart, void *d,
yasm_output_value_func output_value, yasm_output_reloc_func output_reloc);
static const yasm_bytecode_callback x86_bc_callback_insn = ;
static const yasm_bytecode_callback x86_bc_callback_jmp = ;
static const yasm_bytecode_callback x86_bc_callback_jmpfar = ;
yasm_x86__set_rex_from_reg
yasm_x86__bc_transform_insn
yasm_x86__bc_transform_jmp
yasm_x86__bc_transform_jmpfar
yasm_x86__ea_init
yasm_x86__ea_set_disponly
ea_create
yasm_x86__ea_create_reg
yasm_x86__ea_create_expr
yasm_x86__ea_create_imm
yasm_x86__bc_apply_prefixes
x86_bc_insn_destroy
x86_bc_jmp_destroy
x86_bc_jmpfar_destroy
yasm_x86__ea_destroy
yasm_x86__ea_print
x86_common_print
x86_opcode_print
x86_bc_insn_print
x86_bc_jmp_print
x86_bc_jmpfar_print
x86_common_calc_len
x86_bc_insn_calc_len
x86_bc_insn_expand
x86_bc_jmp_calc_len
x86_bc_jmp_expand
x86_bc_jmpfar_calc_len
x86_common_tobytes
x86_opcode_tobytes
x86_bc_insn_tobytes
x86_bc_jmp_tobytes
x86_bc_jmpfar_tobytes
yasm_x86__intnum_tobytes
