static void noop_init_apic_ldr(void)
static void noop_send_IPI_mask(const struct cpumask *cpumask, int vector)
static void noop_send_IPI_mask_allbutself(const struct cpumask *cpumask, int vector)
static void noop_send_IPI_allbutself(int vector)
static void noop_send_IPI_all(int vector)
static void noop_send_IPI_self(int vector)
static void noop_apic_wait_icr_idle(void)
static void noop_apic_icr_write(u32 low, u32 id)
static int noop_wakeup_secondary_cpu(int apicid, unsigned long start_eip)
static u32 noop_safe_apic_wait_icr_idle(void)
static u64 noop_apic_icr_read(void)
static int noop_phys_pkg_id(int cpuid_apic, int index_msb)
static unsigned int noop_get_apic_id(unsigned long x)
static int noop_probe(void)
static int noop_apic_id_registered(void)
static const struct cpumask *noop_target_cpus(void)
static unsigned long noop_check_apicid_used(physid_mask_t *map, int apicid)
static unsigned long noop_check_apicid_present(int bit)
static void noop_vector_allocation_domain(int cpu, struct cpumask *retmask)
static u32 noop_apic_read(u32 reg)
static void noop_apic_write(u32 reg, u32 v)
struct apic apic_noop = ;
