void user_enable_single_step(struct task_struct *child)
void user_disable_single_step(struct task_struct *child)
void ptrace_disable(struct task_struct *child)
int ptrace_getregs(struct task_struct *child, void __user *uregs)
int ptrace_setregs(struct task_struct *child, void __user *uregs)
int ptrace_getxregs(struct task_struct *child, void __user *uregs)
int ptrace_setxregs(struct task_struct *child, void __user *uregs)
int ptrace_peekusr(struct task_struct *child, long regno, long __user *ret)
int ptrace_pokeusr(struct task_struct *child, long regno, long val)
long arch_ptrace(struct task_struct *child, long request,
unsigned long addr, unsigned long data)
void do_syscall_trace(void)
void do_syscall_trace_enter(struct pt_regs *regs)
void do_syscall_trace_leave(struct pt_regs *regs)
