#define _RTL8712_CMD_C_
static void check_hw_pbc(struct _adapter *padapter)
static void query_fw_rx_phy_status(struct _adapter *padapter)
static void StatusWatchdogCallback(struct _adapter *padapter)
static void r871x_internal_cmd_hdl(struct _adapter *padapter, u8 *pbuf)
static u8 read_macreg_hdl(struct _adapter *padapter, u8 *pbuf)
static u8 write_macreg_hdl(struct _adapter *padapter, u8 *pbuf)
static u8 read_bbreg_hdl(struct _adapter *padapter, u8 *pbuf)
static u8 write_bbreg_hdl(struct _adapter *padapter, u8 *pbuf)
static u8 read_rfreg_hdl(struct _adapter *padapter, u8 *pbuf)
static u8 write_rfreg_hdl(struct _adapter *padapter, u8 *pbuf)
static u8 sys_suspend_hdl(struct _adapter *padapter, u8 *pbuf)
static struct cmd_obj *cmd_hdl_filter(struct _adapter *padapter,
struct cmd_obj *pcmd)
static u8 check_cmd_fifo(struct _adapter *padapter, uint sz)
u8 r8712_fw_cmd(struct _adapter *pAdapter, u32 cmd)
void r8712_fw_cmd_data(struct _adapter *pAdapter, u32 *value, u8 flag)
int r8712_cmd_thread(void *context)
void r8712_event_handle(struct _adapter *padapter, uint *peventbuf)
