static int netfs_data_recv(struct netfs_state *st, void *buf, u64 size)
static int pohmelfs_data_recv(struct netfs_state *st, void *data, unsigned int size)
int pohmelfs_data_recv_and_check(struct netfs_state *st, void *data, unsigned int size)
struct netfs_poll_helper ;
static int netfs_queue_wake(wait_queue_t *wait, unsigned mode, int sync, void *key)
static void netfs_queue_func(struct file *file, wait_queue_head_t *whead,
poll_table *pt)
static void netfs_poll_exit(struct netfs_state *st)
static int netfs_poll_init(struct netfs_state *st)
static int pohmelfs_read_page_response(struct netfs_state *st)
static int pohmelfs_check_name(struct pohmelfs_inode *parent, struct qstr *str,
struct netfs_inode_info *info)
static int pohmelfs_readdir_response(struct netfs_state *st)
static int pohmelfs_lookup_response(struct netfs_state *st)
static int pohmelfs_create_response(struct netfs_state *st)
static int pohmelfs_remove_response(struct netfs_state *st)
static int pohmelfs_transaction_response(struct netfs_state *st)
static int pohmelfs_page_cache_response(struct netfs_state *st)
static int pohmelfs_root_cap_response(struct netfs_state *st)
static int pohmelfs_crypto_cap_response(struct netfs_state *st)
static int pohmelfs_capabilities_response(struct netfs_state *st)
static int pohmelfs_getxattr_response(struct netfs_state *st)
int pohmelfs_data_lock_response(struct netfs_state *st)
static void __inline__ netfs_state_reset(struct netfs_state *st)
static int pohmelfs_recv(void *data)
int netfs_state_init(struct netfs_state *st)
void netfs_state_exit(struct netfs_state *st)
int pohmelfs_state_init_one(struct pohmelfs_sb *psb, struct pohmelfs_config *conf)
void pohmelfs_state_flush_transactions(struct netfs_state *st)
static void pohmelfs_state_exit_one(struct pohmelfs_config *c)
int pohmelfs_state_init(struct pohmelfs_sb *psb)
void pohmelfs_state_exit(struct pohmelfs_sb *psb)
void pohmelfs_switch_active(struct pohmelfs_sb *psb)
void pohmelfs_check_states(struct pohmelfs_sb *psb)
