void sas_init_dev(struct domain_device *dev)
static int sas_get_port_device(struct asd_sas_port *port)
int sas_notify_lldd_dev_found(struct domain_device *dev)
void sas_notify_lldd_dev_gone(struct domain_device *dev)
int sas_discover_end_dev(struct domain_device *dev)
static inline void sas_unregister_common_dev(struct domain_device *dev)
void sas_unregister_dev(struct domain_device *dev)
void sas_unregister_domain_devices(struct asd_sas_port *port)
static void sas_discover_domain(struct work_struct *work)
static void sas_revalidate_domain(struct work_struct *work)
int sas_discover_event(struct asd_sas_port *port, enum discover_event ev)
void sas_init_disc(struct sas_discovery *disc, struct asd_sas_port *port)
