static __init void jz4740_init_cmdline(int argc, char *argv[])
void __init prom_init(void)
void __init prom_free_prom_memory(void)
#define UART_REG(_reg) ((void __iomem *)CKSEG1ADDR(JZ4740_UART0_BASE_ADDR + (_reg << 2)))
void prom_putchar(char c)
