static int midibuf_message_length(unsigned char code)
static int midibuf_is_empty(struct MidiBuffer *this)
static int midibuf_is_full(struct MidiBuffer *this)
void line6_midibuf_reset(struct MidiBuffer *this)
int line6_midibuf_init(struct MidiBuffer *this, int size, int split)
void line6_midibuf_status(struct MidiBuffer *this)
int line6_midibuf_bytes_free(struct MidiBuffer *this)
int line6_midibuf_bytes_used(struct MidiBuffer *this)
int line6_midibuf_write(struct MidiBuffer *this, unsigned char *data,
int length)
int line6_midibuf_read(struct MidiBuffer *this, unsigned char *data, int length)
int line6_midibuf_ignore(struct MidiBuffer *this, int length)
int line6_midibuf_skip_message(struct MidiBuffer *this, unsigned short mask)
void line6_midibuf_destroy(struct MidiBuffer *this)
