static void wake_up_event_readers(struct service_processor *sp)
void ibmasm_receive_event(struct service_processor *sp, void *data, unsigned int data_size)
static inline int event_available(struct event_buffer *b, struct event_reader *r)
int ibmasm_get_next_event(struct service_processor *sp, struct event_reader *reader)
void ibmasm_cancel_next_event(struct event_reader *reader)
void ibmasm_event_reader_register(struct service_processor *sp, struct event_reader *reader)
void ibmasm_event_reader_unregister(struct service_processor *sp, struct event_reader *reader)
int ibmasm_event_buffer_init(struct service_processor *sp)
void ibmasm_event_buffer_exit(struct service_processor *sp)
