#define get_msci(port)	  (phy_node(port) ?   MSCI1_OFFSET :   MSCI0_OFFSET)
#define get_dmac_rx(port) (phy_node(port) ? DMAC1RX_OFFSET : DMAC0RX_OFFSET)
#define get_dmac_tx(port) (phy_node(port) ? DMAC1TX_OFFSET : DMAC0TX_OFFSET)
#define SCA_INTR_MSCI(node)    (node ? 0x10 : 0x01)
#define SCA_INTR_DMAC_RX(node) (node ? 0x20 : 0x02)
#define SCA_INTR_DMAC_TX(node) (node ? 0x40 : 0x04)
static inline struct net_device *port_to_dev(port_t *port)
static inline int sca_intr_status(card_t *card)
static inline port_t* dev_to_port(struct net_device *dev)
static inline u16 next_desc(port_t *port, u16 desc, int transmit)
static inline u16 desc_abs_number(port_t *port, u16 desc, int transmit)
static inline u16 desc_offset(port_t *port, u16 desc, int transmit)
static inline pkt_desc __iomem *desc_address(port_t *port, u16 desc,
int transmit)
static inline u32 buffer_offset(port_t *port, u16 desc, int transmit)
static inline void sca_set_carrier(port_t *port)
static void sca_init_port(port_t *port)
static inline void sca_msci_intr(port_t *port)
static inline void sca_rx(card_t *card, port_t *port, pkt_desc __iomem *desc,
u16 rxin)
static inline void sca_rx_intr(port_t *port)
static inline void sca_tx_intr(port_t *port)
static irqreturn_t sca_intr(int irq, void* dev_id)
static void sca_set_port(port_t *port)
static void sca_open(struct net_device *dev)
static void sca_close(struct net_device *dev)
static int sca_attach(struct net_device *dev, unsigned short encoding,
unsigned short parity)
static void sca_dump_rings(struct net_device *dev)
static netdev_tx_t sca_xmit(struct sk_buff *skb, struct net_device *dev)
static u32 __devinit sca_detect_ram(card_t *card, u8 __iomem *rambase,
u32 ramsize)
static void __devinit sca_init(card_t *card, int wait_states)
