RESTORE_PRED \
if (sce->ics.prediction_used[sfb])
flt16_round
flt16_even
flt16_trunc
predict
reset_predict_state
reset_all_predictors
reset_predictor_group
ff_aac_apply_main_pred
update_counters
ff_aac_adjust_common_pred
update_pred_resets
ff_aac_search_for_pred
ff_aac_encode_main_pred
