#define AVCODEC_ACELP_VECTORS_H
typedef struct ACELPVContext ACELPVContext;
ff_acelp_vectors_init;
ff_acelp_vectors_init_mips;
typedef struct AMRFixed  AMRFixed;
extern const uint8_t ff_fc_4pulses_8bits_tracks_13[16];
extern const uint8_t ff_fc_4pulses_8bits_track_4[32];
extern const uint8_t ff_fc_2pulses_9bits_track1[16];
extern const uint8_t ff_fc_2pulses_9bits_track1_gray[16];
extern const uint8_t ff_fc_2pulses_9bits_track2_gray[32];
extern const float ff_b60_sinc[61];
extern const float ff_pow_0_7[10];
extern const float ff_pow_0_75[10];
extern const float ff_pow_0_55[10];
ff_acelp_fc_pulse_per_track;
ff_decode_10_pulses_35bits;
ff_acelp_weighted_vector_sum;
ff_weighted_vector_sumf;
ff_adaptive_gain_control;
ff_scale_vector_to_given_sum_of_squares;
ff_set_fixed_vector;
ff_clear_fixed_vector;
