typedef struct ATRAC3PContext  ATRAC3PContext;
atrac3p_decode_close
set_channel_params
atrac3p_decode_init
decode_residual_spectrum
reconstruct_frame
atrac3p_decode_frame
AVCodec ff_atrac3p_decoder = ;
