#if FF_API_OLD_BSF
FF_DISABLE_DEPRECATION_WARNINGS
*av_bitstream_filter_next
av_register_bitstream_filter
typedef struct BSFCompatContext  BSFCompatContext;
*av_bitstream_filter_init
av_bitstream_filter_close
av_bitstream_filter_filter
FF_ENABLE_DEPRECATION_WARNINGS
