#define SUBBAND_COUNT 10
cfhd_decode_init
init_plane_defaults
init_frame_defaults
dequant_and_decompand
filter
horiz_filter
horiz_filter_clip
vert_filter
free_buffers
alloc_buffers
cfhd_decode
cfhd_close_decoder
AVCodec ff_cfhd_decoder = ;
