#if ARCH_ARM
enum HeaderType ;
enum AudioMode ;
enum ExtAudioType ;
enum LFEFlag ;
static const int8_t prm_ch_to_spkr_map[AMODE_COUNT][5] = ;
static const uint8_t audio_mode_ch_mask[AMODE_COUNT] = ;
static const uint8_t block_code_nbits[7] = ;
static const uint8_t quant_index_sel_nbits[DCA_CODE_BOOKS] = ;
static const uint8_t quant_index_group_size[DCA_CODE_BOOKS] = ;
dca_get_vlc
get_array
parse_frame_header
parse_coding_header
parse_scale
parse_joint_scale
parse_subframe_header
decode_blockcodes
parse_block_codes
parse_huffman_codes
extract_audio
dequantize
inverse_adpcm
parse_subframe_audio
erase_adpcm_history
alloc_sample_buffer
parse_frame_data
parse_xch_frame
parse_xxch_frame
parse_xbr_subframe
parse_xbr_frame
rand_x96
parse_x96_subframe_audio
erase_x96_adpcm_history
alloc_x96_sample_buffer
parse_x96_subframe_header
parse_x96_coding_header
parse_x96_frame_data
parse_x96_frame
parse_x96_frame_exss
parse_aux_data
parse_optional_info
ff_dca_core_parse
ff_dca_core_parse_exss
map_prm_ch_to_spkr
erase_dsp_history
set_filter_mode
ff_dca_core_filter_fixed
filter_frame_fixed
filter_frame_float
ff_dca_core_filter_frame
ff_dca_core_flush
ff_dca_core_init
ff_dca_core_close
