#define MAX_SLICES 256
struct hevc_dxva2_picture_context ;
fill_picture_entry
get_refpic_index
fill_picture_parameters
fill_scaling_lists
fill_slice_short
commit_bitstream_and_slice_buffer
dxva2_hevc_start_frame
dxva2_hevc_decode_slice
dxva2_hevc_end_frame
#if CONFIG_HEVC_DXVA2_HWACCEL
AVHWAccel ff_hevc_dxva2_hwaccel = ;
#if CONFIG_HEVC_D3D11VA_HWACCEL
AVHWAccel ff_hevc_d3d11va_hwaccel = ;
