#define MAX_SLICES 1024
struct dxva2_picture_context ;
fill_picture_parameters
fill_quantization_matrices
fill_slice
commit_bitstream_and_slice_buffer
dxva2_mpeg2_start_frame
dxva2_mpeg2_decode_slice
dxva2_mpeg2_end_frame
#if CONFIG_MPEG2_DXVA2_HWACCEL
AVHWAccel ff_mpeg2_dxva2_hwaccel = ;
#if CONFIG_MPEG2_D3D11VA_HWACCEL
AVHWAccel ff_mpeg2_d3d11va_hwaccel = ;
