#define DELTA_ERR_MAX 0.1
typedef struct cell_s  cell;
typedef struct elbg_data  elbg_data;
distance_limited
vect_division
eval_error_cell
get_closest_codebook
get_high_utility_cell
simple_lbg
get_new_centroids
shift_codebook
evaluate_utility_inc
update_utility_and_n_cb
try_shift_candidate
do_shiftings
#define BIG_PRIME 433494437LL
avpriv_init_elbg
avpriv_do_elbg
