static JavaVM *java_vm;
static pthread_key_t current_env;
static pthread_once_t once = PTHREAD_ONCE_INIT;
static pthread_mutex_t lock = PTHREAD_MUTEX_INITIALIZER;
jni_detach_env
jni_create_pthread_key
*ff_jni_get_env
*ff_jni_jstring_to_utf_chars
ff_jni_utf_chars_to_jstring
ff_jni_exception_get_summary
ff_jni_exception_check
ff_jni_init_jfields
ff_jni_reset_jfields
