#define AVCODEC_FMTCONVERT_H
typedef struct FmtConvertContext  FmtConvertContext;
ff_fmt_convert_init;
ff_fmt_convert_init_aarch64;
ff_fmt_convert_init_arm;
ff_fmt_convert_init_ppc;
ff_fmt_convert_init_x86;
ff_fmt_convert_init_mips;
