FFERRTAG
static const uint8_t sei_num_clock_ts_table[9] = ;
ff_h264_sei_uninit
decode_picture_timing
decode_registered_user_data_afd
decode_registered_user_data_closed_caption
decode_registered_user_data
decode_unregistered_user_data
decode_recovery_point
decode_buffering_period
decode_frame_packing_arrangement
decode_display_orientation
decode_green_metadata
ff_h264_sei_decode
*ff_h264_sei_stereo_mode
