parse_section_header
hap_parse_decode_instructions
hap_can_use_tex_in_place
hap_parse_frame_header
decompress_chunks_thread
decompress_texture_thread
hap_decode
hap_init
hap_close
AVCodec ff_hap_decoder = ;
