enum HEVC_SEI_TYPE ;
decode_nal_sei_decoded_picture_hash
decode_nal_sei_mastering_display_info
decode_nal_sei_frame_packing_arrangement
decode_nal_sei_display_orientation
decode_pic_timing
decode_registered_user_data_closed_caption
decode_nal_sei_user_data_registered_itu_t_t35
active_parameter_sets
decode_nal_sei_prefix
decode_nal_sei_suffix
decode_nal_sei_message
more_rbsp_data
ff_hevc_decode_nal_sei
ff_hevc_reset_sei
