#define HNM4_CHUNK_ID_PL 19536
#define HNM4_CHUNK_ID_IZ 23113
#define HNM4_CHUNK_ID_IU 21833
#define HNM4_CHUNK_ID_SD 17491
typedef struct Hnm4VideoContext  Hnm4VideoContext;
getbit
unpack_intraframe
postprocess_current_frame
copy_processed_frame
decode_interframe_v4
decode_interframe_v4a
hnm_update_palette
hnm_flip_buffers
hnm_decode_frame
hnm_decode_init
hnm_decode_end
AVCodec ff_hnm4_video_decoder = ;
