typedef struct LibSchroFrameContext  LibSchroFrameContext;
typedef struct SchroDecoderParams  SchroDecoderParams;
typedef struct SchroParseUnitContext  SchroParseUnitContext;
libschroedinger_decode_buffer_free
parse_context_init
*find_next_parse_unit
get_chroma_format
libschroedinger_decode_init
libschroedinger_decode_frame_free
libschroedinger_handle_first_access_unit
libschroedinger_decode_frame
libschroedinger_decode_close
libschroedinger_flush
AVCodec ff_libschroedinger_decoder = ;
