#define INPUT_DEQUEUE_TIMEOUT_US 8000
#define OUTPUT_DEQUEUE_TIMEOUT_US 8000
#define OUTPUT_DEQUEUE_BLOCK_TIMEOUT_US 1000000
enum ;
static const struct  color_formats[] = ;
mcdec_map_color_format
ff_mediacodec_dec_ref
ff_mediacodec_dec_unref
mediacodec_buffer_release
mediacodec_wrap_hw_buffer
mediacodec_wrap_sw_buffer
mediacodec_dec_parse_format
mediacodec_dec_flush_codec
ff_mediacodec_dec_init
ff_mediacodec_dec_decode
ff_mediacodec_dec_flush
ff_mediacodec_dec_close
ff_mediacodec_dec_is_flushing
AVHWAccel ff_h264_mediacodec_hwaccel = ;
AVHWAccel ff_hevc_mediacodec_hwaccel = ;
AVHWAccel ff_mpeg4_mediacodec_hwaccel = ;
AVHWAccel ff_vp8_mediacodec_hwaccel = ;
AVHWAccel ff_vp9_mediacodec_hwaccel = ;
