#if CONFIG_H264_MEDIACODEC_HWACCEL
*av_mediacodec_alloc_context
av_mediacodec_default_init
av_mediacodec_default_free
av_mediacodec_release_buffer
*av_mediacodec_alloc_context
av_mediacodec_default_init
av_mediacodec_default_free
av_mediacodec_release_buffer
