struct JNIAMediaCodecListFields  JNIAMediaCodecListFields;
static const struct FFJniField jni_amediacodeclist_mapping[] = ;
struct JNIAMediaFormatFields  JNIAMediaFormatFields;
static const struct FFJniField jni_amediaformat_mapping[] = ;
static const AVClass amediaformat_class = ;
struct FFAMediaFormat ;
struct JNIAMediaCodecFields  JNIAMediaCodecFields;
static const struct FFJniField jni_amediacodec_mapping[] = ;
static const AVClass amediacodec_class = ;
struct FFAMediaCodec ;
JNI_GET_ENV_OR_RETURN do  while (0)
JNI_GET_ENV_OR_RETURN_VOID do  while (0)
ff_AMediaCodecProfile_getProfileFromAVCodecContext
*ff_AMediaCodecList_getCodecNameByType
*ff_AMediaFormat_new
*ff_AMediaFormat_newFromObject
ff_AMediaFormat_delete
ff_AMediaFormat_toString
ff_AMediaFormat_getInt32
ff_AMediaFormat_getInt64
ff_AMediaFormat_getFloat
ff_AMediaFormat_getBuffer
ff_AMediaFormat_getString
ff_AMediaFormat_setInt32
ff_AMediaFormat_setInt64
ff_AMediaFormat_setFloat
ff_AMediaFormat_setString
ff_AMediaFormat_setBuffer
codec_init_static_fields
ff_AMediaCodec_createCodecByName
ff_AMediaCodec_createDecoderByType
ff_AMediaCodec_createEncoderByType
ff_AMediaCodec_delete
*ff_AMediaCodec_getName
ff_AMediaCodec_configure
ff_AMediaCodec_start
ff_AMediaCodec_stop
ff_AMediaCodec_flush
ff_AMediaCodec_releaseOutputBuffer
ff_AMediaCodec_releaseOutputBufferAtTime
ff_AMediaCodec_dequeueInputBuffer
ff_AMediaCodec_queueInputBuffer
ff_AMediaCodec_dequeueOutputBuffer
ff_AMediaCodec_getInputBuffer
ff_AMediaCodec_getOutputBuffer
ff_AMediaCodec_getOutputFormat
ff_AMediaCodec_infoTryAgainLater
ff_AMediaCodec_infoOutputBuffersChanged
ff_AMediaCodec_infoOutputFormatChanged
ff_AMediaCodec_getBufferFlagCodecConfig
ff_AMediaCodec_getBufferFlagEndOfStream
ff_AMediaCodec_getBufferFlagKeyFrame
ff_AMediaCodec_getConfigureFlagEncode
ff_AMediaCodec_cleanOutputBuffers
