#define AVCODEC_MEDIACODEC_SW_BUFFER_H
ff_mediacodec_sw_buffer_copy_yuv420_planar;
ff_mediacodec_sw_buffer_copy_yuv420_semi_planar;
ff_mediacodec_sw_buffer_copy_yuv420_packed_semi_planar;
ff_mediacodec_sw_buffer_copy_yuv420_packed_semi_planar_64x32Tile2m8ka;
