static AVCodecParser *av_first_parser = NULL;
*av_parser_next
av_register_codec_parser
*av_parser_init
ff_fetch_timestamp
av_parser_parse2
av_parser_change
av_parser_close
ff_combine_frame
ff_parse_close
ff_mpeg4video_split
