#define AVCODEC_PIXBLOCKDSP_H
typedef struct PixblockDSPContext  PixblockDSPContext;
ff_pixblockdsp_init;
ff_pixblockdsp_init_alpha;
ff_pixblockdsp_init_arm;
ff_pixblockdsp_init_ppc;
ff_pixblockdsp_init_x86;
ff_pixblockdsp_init_mips;
