extern const FFPsyModel ff_aac_psy_model;
ff_psy_init
*ff_psy_find_group
ff_psy_end
typedef struct FFPsyPreprocessContextFFPsyPreprocessContext;
#define FILT_ORDER 4
ff_psy_preprocess_init
ff_psy_preprocess
ff_psy_preprocess_end
