typedef struct PerThreadContext  PerThreadContext;
typedef struct FrameThreadContext  FrameThreadContext;
THREAD_SAFE_CALLBACKS \
((avctx)->thread_safe_callbacks || (avctx)->get_buffer2 == avcodec_default_get_buffer2)
*frame_worker_thread
update_context_from_thread
update_context_from_user
release_delayed_buffers
submit_packet
ff_thread_decode_frame
ff_thread_report_progress
ff_thread_await_progress
ff_thread_finish_setup
park_frame_worker_threads
ff_frame_thread_free
ff_frame_thread_init
ff_thread_flush
ff_thread_can_start_frame
thread_get_buffer_internal
ff_thread_get_format
ff_thread_get_buffer
ff_thread_release_buffer
