ra144_encode_close
ra144_encode_init
quantize
orthogonalize
get_match_score
create_adapt_vect
adaptive_cb_search
find_best_vect
fixed_cb_search
ra144_encode_subblock
ra144_encode_frame
AVCodec ff_ra_144_encoder = ;
