#define AVCODEC_SIMPLE_IDCT_H
ff_simple_idct_put_8;
ff_simple_idct_add_8;
ff_simple_idct_8;
ff_simple_idct_put_10;
ff_simple_idct_add_10;
ff_simple_idct_10;
ff_simple_idct_put_12;
ff_simple_idct_add_12;
ff_simple_idct_12;
ff_prores_idct;
ff_simple_idct248_put;
ff_simple_idct84_add;
ff_simple_idct48_add;
ff_simple_idct44_add;
