#define AVCODEC_SINEWIN_H
#if CONFIG_HARDCODED_TABLES
#   define SINETABLE_CONST const
#   define SINETABLE_CONST
#define USE_FIXED 0
SINETABLE \
DECLARE_ALIGNED)[size]
AAC_RENAME(INTFLOAT *window, int n);
AAC_RENAME(int index);
SINETABLE;
SINETABLE;
SINETABLE;
SINETABLE;
SINETABLE;
SINETABLE;
SINETABLE;
SINETABLE;
SINETABLE;
AAC_RENAME[14];
