#define AVCODEC_THREAD_H
typedef struct ThreadFrame  ThreadFrame;
ff_thread_flush;
ff_thread_decode_frame;
ff_thread_finish_setup;
ff_thread_report_progress;
ff_thread_await_progress;
ff_thread_get_format;
ff_thread_get_buffer;
ff_thread_release_buffer;
ff_thread_ref_frame;
ff_thread_init;
ff_thread_free;
ff_alloc_entries;
ff_reset_entries;
ff_thread_report_progress2;
ff_thread_await_progress2;
