#define AVCODEC_TIFF_COMMON_H
enum TiffTypes ;
static const uint8_t type_sizes[14] = ;
static const uint16_t ifd_tags[] = ;
ff_tis_ifd;
ff_tget_short;
ff_tget_long;
ff_tget_double;
ff_tget;
*ff_trationals2str;
*ff_tlongs2str;
*ff_tdoubles2str;
*ff_tshorts2str;
ff_tadd_rational_metadata;
ff_tadd_long_metadata;
ff_tadd_doubles_metadata;
ff_tadd_shorts_metadata;
ff_tadd_bytes_metadata;
ff_tadd_string_metadata;
ff_tdecode_header;
ff_tread_tag;
