eval_lpc_spectrum
eval_lpcenv
interpolate
get_cos
eval_lpcenv_or_interp
eval_lpcenv_2parts
dequant
dec_gain
rearrange_lsp
decode_lsp
dec_lpc_spectrum_inv
static const uint8_t wtype_to_wsize[] = ;
imdct_and_window
imdct_output
read_and_decode_spectrum
const enum TwinVQFrameType ff_twinvq_wtype_to_ftype_table[] = ;
ff_twinvq_decode_frame
init_mdct_win
permutate_in_line
transpose_perm
linear_perm
construct_perm_table
init_bitstream_params
ff_twinvq_decode_close
ff_twinvq_decode_init
