#define AVCODEC_VAAPI_INTERNAL_H
typedef struct  FFVAContext;
*ff_vaapi_get_context
ff_vaapi_get_surface_id
ff_vaapi_context_init;
ff_vaapi_context_fini;
ff_vaapi_common_end_frame;
*ff_vaapi_alloc_pic_param;
*ff_vaapi_alloc_iq_matrix;
*ff_vaapi_alloc_bitplane;
*ff_vaapi_alloc_slice;
ff_vaapi_mpeg_end_frame;
ff_vaapi_commit_slices;
ff_vaapi_render_picture;
