static const char *picture_type_name[] = ;
vaapi_encode_make_packed_header
vaapi_encode_make_param_buffer
vaapi_encode_wait
vaapi_encode_issue
vaapi_encode_output
vaapi_encode_discard
*vaapi_encode_alloc
vaapi_encode_free
vaapi_encode_step
vaapi_encode_get_next
vaapi_encode_mangle_end
vaapi_encode_clear_old
ff_vaapi_encode2
vaapi_encode_check_config
ff_vaapi_encode_init
ff_vaapi_encode_close
