get_VAMvModeVC1
vc1_has_MVTYPEMB_bitplane
vc1_has_SKIPMB_bitplane
vc1_has_DIRECTMB_bitplane
vc1_has_ACPRED_bitplane
vc1_has_OVERFLAGS_bitplane
vc1_get_PTYPE
vc1_get_MVMODE
vc1_get_MVMODE2
vc1_get_TTFRM
vc1_pack_bitplanes
vaapi_vc1_start_frame
vaapi_vc1_decode_slice
#if CONFIG_WMV3_VAAPI_HWACCEL
AVHWAccel ff_wmv3_vaapi_hwaccel = ;
AVHWAccel ff_vc1_vaapi_hwaccel = ;
