#define AVCODEC_VC1_H
#define AC_VLC_BITS 9
enum QuantMode ;
enum DQProfile ;
enum DQSingleEdge ;
enum DQDoubleEdge ;
enum MVModes ;
enum MBModesIntfr ;
enum BMVTypes ;
enum TransformTypes ;
enum CodingSet ;
enum COTypes ;
enum FrameCodingMode ;
enum Imode ;
typedef struct VC1Context VC1Context;
ff_vc1_decode_sequence_header;
ff_vc1_decode_entry_point;
int ff_vc1_parse_frame_header    (VC1Context *v, GetBitContext *gb);
ff_vc1_parse_frame_header_adv;
ff_vc1_init_common;
ff_vc1_decode_init_alloc_tables;
ff_vc1_init_transposed_scantables;
ff_vc1_decode_end;
ff_vc1_decode_blocks;
ff_vc1_loop_filter_iblk;
ff_vc1_loop_filter_iblk_delayed;
ff_vc1_smooth_overlap_filter_iblk;
ff_vc1_apply_p_loop_filter;
ff_vc1_mc_1mv;
ff_vc1_mc_4mv_luma;
ff_vc1_mc_4mv_chroma;
ff_vc1_mc_4mv_chroma4;
ff_vc1_interp_mc;
