vc1_scale_luma
vc1_scale_chroma
vc1_lut_scale_luma
vc1_lut_scale_chroma
static const uint8_t popcount4[16] = ;
get_luma_mv
get_chroma_mv
ff_vc1_mc_1mv
ff_vc1_mc_4mv_luma
ff_vc1_mc_4mv_chroma
ff_vc1_mc_4mv_chroma4
ff_vc1_interp_mc
