#if CONFIG_H264_VDA_HWACCEL
*av_vda_alloc_context
av_vda_default_init
av_vda_default_init2
av_vda_default_free
ff_vda_default_free
*av_vda_alloc_context
av_vda_default_init
av_vda_default_init2
av_vda_default_free
