#define AVCODEC_VDA_VT_INTERNAL_H
ff_vda_output_callback;
ff_vda_default_init;
ff_vda_default_free;
typedef struct VTContext  VTContext;
ff_videotoolbox_alloc_frame;
ff_videotoolbox_uninit;
ff_videotoolbox_buffer_create;
ff_videotoolbox_h264_start_frame;
ff_videotoolbox_h264_decode_slice;
ff_videotoolbox_avcc_extradata_create;
