struct vda_buffer ;
vda_decoder_callback
vda_sync_decode
vda_old_h264_start_frame
vda_old_h264_decode_slice
vda_h264_release_buffer
vda_old_h264_end_frame
ff_vda_create_decoder
ff_vda_destroy_decoder
AVHWAccel ff_h264_vda_old_hwaccel = ;
ff_vda_output_callback
vda_h264_end_frame
ff_vda_default_init
AVHWAccel ff_h264_vda_hwaccel = ;
