#if FF_API_BUFS_VDPAU
#if FF_API_VDPAU
#undef NDEBUG
vdpau_error
*av_alloc_vdpaucontext
MAKE_ACCESSORS(AVVDPAUContext, vdpau_hwaccel, AVVDPAU_Render2, render2)
av_vdpau_get_surface_parameters
ff_vdpau_common_init
ff_vdpau_common_uninit
ff_vdpau_common_reinit
ff_vdpau_common_start_frame
ff_vdpau_common_end_frame
#if CONFIG_MPEG1_VDPAU_HWACCEL || \
CONFIG_MPEG2_VDPAU_HWACCEL || CONFIG_MPEG4_VDPAU_HWACCEL || \
CONFIG_VC1_VDPAU_HWACCEL   || CONFIG_WMV3_VDPAU_HWACCEL
ff_vdpau_mpeg_end_frame
ff_vdpau_add_buffer
#if FF_API_VDPAU
ff_vdpau_add_data_chunk
#if CONFIG_H264_VDPAU_DECODER
ff_vdpau_h264_set_reference_frames
ff_vdpau_h264_picture_start
ff_vdpau_h264_picture_complete
#if CONFIG_MPEG_VDPAU_DECODER || CONFIG_MPEG1_VDPAU_DECODER
ff_vdpau_mpeg_picture_complete
#if CONFIG_VC1_VDPAU_DECODER
ff_vdpau_vc1_decode_picture
#if CONFIG_MPEG4_VDPAU_DECODER
ff_vdpau_mpeg4_decode_picture
#if FF_API_VDPAU_PROFILE
av_vdpau_get_profile
*av_vdpau_alloc_context
av_vdpau_bind_context
