static const AVClass vorbis_parser_class = ;
parse_id_header
parse_setup_header
vorbis_parse_init
av_vorbis_parse_frame_flags
av_vorbis_parse_frame
av_vorbis_parse_reset
av_vorbis_parse_free
*av_vorbis_parse_init
#if CONFIG_VORBIS_PARSER
typedef struct VorbisParseContext  VorbisParseContext;
vorbis_parse
vorbis_parser_close
AVCodecParser ff_vorbis_parser = ;
