#define VP6_MAX_HUFF_SIZE 12
vp6_parse_coeff;
vp6_parse_coeff_huffman;
vp6_parse_header
vp6_coeff_order_table_init
vp6_default_models_init
vp6_parse_vector_models
vp6_huff_cmp
vp6_build_huff_tree
vp6_parse_coeff_models
vp6_parse_vector_adjustment
vp6_get_nb_null
vp6_parse_coeff_huffman
vp6_parse_coeff
vp6_block_variance
vp6_filter_hv4
vp6_filter_diag2
vp6_filter
vp6_decode_init_context;
vp6_decode_init
vp6_decode_init_context
vp6_decode_free_context;
vp6_decode_free
vp6_decode_free_context
AVCodec ff_vp6_decoder = ;
AVCodec ff_vp6f_decoder = ;
AVCodec ff_vp6a_decoder = ;
