#define AVCODEC_VP8DATA_H
static const uint8_t vp7_pred4x4_mode[] = ;
static const uint8_t vp8_pred4x4_mode[] = ;
static const int8_t vp8_pred16x16_tree_intra[4][2] = ;
static const int8_t vp8_pred16x16_tree_inter[4][2] = ;
typedef struct VP7MVPred  VP7MVPred;
#define VP7_MV_PRED_COUNT 12
static const VP7MVPred vp7_mv_pred[VP7_MV_PRED_COUNT] = ;
static const int vp7_mode_contexts[31][4] = ;
static const int vp8_mode_contexts[6][4] = ;
static const uint8_t vp8_mbsplits[5][16] = ;
static const uint8_t vp8_mbfirstidx[4][16] = ;
static const uint8_t vp8_mbsplit_count[4] = ;
static const uint8_t vp8_mbsplit_prob[3] = ;
static const uint8_t vp7_submv_prob[3] = ;
static const uint8_t vp8_submv_prob[5][3] = ;
static const uint8_t vp8_pred16x16_prob_intra[4] = ;
static const uint8_t vp8_pred16x16_prob_inter[4] = ;
static const int8_t vp8_pred4x4_tree[9][2] = ;
static const int8_t vp8_pred8x8c_tree[3][2] = ;
static const uint8_t vp8_pred8x8c_prob_intra[3] = ;
static const uint8_t vp8_pred8x8c_prob_inter[3] = ;
static const uint8_t vp8_pred4x4_prob_inter[9] = ;
static const uint8_t vp8_pred4x4_prob_intra[10][10][9] = ;
static const int8_t vp8_segmentid_tree[][2] = ;
static const uint8_t vp8_coeff_band[16] = ;
static const int8_t vp8_coeff_band_indexes[8][10] = ;
static const uint8_t vp8_dct_cat1_prob[] = ;
static const uint8_t vp8_dct_cat2_prob[] = ;
static const uint8_t vp8_dct_cat3_prob[] = ;
static const uint8_t vp8_dct_cat4_prob[] = ;
static const uint8_t vp8_dct_cat5_prob[] = ;
static const uint8_t vp8_dct_cat6_prob[] = ;
const uint8_t *const ff_vp8_dct_cat_prob[] = ;
static const uint8_t vp8_token_default_probs[4][8][3][NUM_DCT_TOKENS - 1] = ;
static const uint8_t vp8_token_update_probs[4][8][3][NUM_DCT_TOKENS - 1] = ;
static const uint8_t vp8_dc_qlookup[VP8_MAX_QUANT + 1] = ;
static const uint16_t vp8_ac_qlookup[VP8_MAX_QUANT + 1] = ;
static const uint8_t vp8_mv_update_prob[2][19] = ;
static const uint8_t vp7_mv_default_prob[2][17] = ;
static const uint8_t vp8_mv_default_prob[2][19] = ;
static const uint8_t vp7_feature_value_size[2][4] = ;
static const int8_t vp7_feature_index_tree[4][2] =
;
static const uint16_t vp7_ydc_qlookup[] = ;
static const uint16_t vp7_yac_qlookup[] = ;
static const uint16_t vp7_y2dc_qlookup[] = ;
static const uint16_t vp7_y2ac_qlookup[] = ;
