#define DC21285_BASE ((volatile unsigned int *)0x42000160)
#define SER0_BASE    ((volatile unsigned char *)0x7c0003f8)
static inline void putc(char c)
static inline void flush(void)
#define arch_decomp_setup()
#define arch_decomp_wdog()
