static void usb_urb_complete(struct urb *urb)
int usb_urb_kill(struct usb_data_stream *stream)
int usb_urb_submit(struct usb_data_stream *stream)
static int usb_free_stream_buffers(struct usb_data_stream *stream)
static int usb_allocate_stream_buffers(struct usb_data_stream *stream, int num, unsigned long size)
static int usb_bulk_urb_init(struct usb_data_stream *stream)
static int usb_isoc_urb_init(struct usb_data_stream *stream)
int usb_urb_init(struct usb_data_stream *stream, struct usb_data_stream_properties *props)
int usb_urb_exit(struct usb_data_stream *stream)
