Plotter::Plotter(QWidget *parent)
: QWidget(parent)
void Plotter::setPlotSettings(const PlotSettings &settings)
void Plotter::zoomOut()
void Plotter::zoomIn()
void Plotter::setCurveData(int id, const QVector<QPointF> &data)
void Plotter::clearCurve(int id)
QSize Plotter::minimumSizeHint() const
QSize Plotter::sizeHint() const
void Plotter::paintEvent(QPaintEvent *)
void Plotter::resizeEvent(QResizeEvent *)
void Plotter::mousePressEvent(QMouseEvent *event)
void Plotter::mouseMoveEvent(QMouseEvent *event)
void Plotter::mouseReleaseEvent(QMouseEvent *event)
void Plotter::keyPressEvent(QKeyEvent *event)
void Plotter::wheelEvent(QWheelEvent *event)
void Plotter::updateRubberBandRegion()
void Plotter::refreshPixmap()
void Plotter::drawGrid(QPainter *painter)
void Plotter::drawCurves(QPainter *painter)
PlotSettings::PlotSettings()
void PlotSettings::scroll(int dx, int dy)
void PlotSettings::adjust()
void PlotSettings::adjustAxis(double &min, double &max, int &numTicks)
