#define _VB_STRUCT_
#define EXTERN
#define EXTERN extern
struct XGI_PanelDelayTblStruct ;
struct XGI_LCDDataStruct ;
struct XGI_LVDSCRT1HDataStruct ;
struct XGI_LVDSCRT1VDataStruct ;
struct XGI_TVDataStruct ;
struct XGI_LVDSDataStruct ;
struct XGI_LVDSDesStruct ;
struct XGI_LVDSCRT1DataStruct ;
struct XGI_StStruct ;
struct XGI_StandTableStruct ;
struct XGI_ExtStruct ;
struct XGI_Ext2Struct ;
struct XGI_MCLKDataStruct ;
struct XGI_ECLKDataStruct ;
struct XGI_VCLKDataStruct ;
struct XGI_VBVCLKDataStruct ;
struct XGI_StResInfoStruct ;
struct XGI_ModeResInfoStruct ;
struct XGI_LCDNBDesStruct ;
struct XGI_LCDDesStruct ;
struct XGI_LCDDataTablStruct ;
struct XGI_TVTablDataStruct ;
struct XGI330_LCDDataDesStruct ;
struct XGI330_LVDSDataStruct ;
struct XGI330_LCDDataDesStruct2 ;
struct XGI330_LCDDataStruct ;
struct XGI330_TVDataStruct ;
struct XGI330_LCDDataTablStruct ;
struct XGI330_TVDataTablStruct ;
struct XGI330_CHTVDataStruct ;
struct XGI_TimingHStruct ;
struct XGI_TimingVStruct ;
struct XGI_CH7007TV_TimingHStruct ;
struct XGI_CH7007TV_TimingVStruct ;
struct XGI_XG21CRT1Struct ;
struct XGI330_CHTVRegDataStruct ;
struct XGI330_LCDCapStruct ;
struct XGI21_LVDSCapStruct ;
struct XGI_CRT1TableStruct ;
struct XGI330_VCLKDataStruct ;
struct XGI301C_Tap4TimingStruct ;
struct XGI_New_StandTableStruct ;
struct vb_device_info ;
struct TimingInfo ;
#define _VB_STRUCT_
