#define _ASM_IA64_SIGCONTEXT_H
#define IA64_SC_FLAG_ONSTACK_BIT		0
#define IA64_SC_FLAG_IN_SYSCALL_BIT		1
#define IA64_SC_FLAG_FPH_VALID_BIT		2
#define IA64_SC_FLAG_ONSTACK		(1 << IA64_SC_FLAG_ONSTACK_BIT)
#define IA64_SC_FLAG_IN_SYSCALL		(1 << IA64_SC_FLAG_IN_SYSCALL_BIT)
#define IA64_SC_FLAG_FPH_VALID		(1 << IA64_SC_FLAG_FPH_VALID_BIT)
# ifndef __ASSEMBLY__
struct sigcontext ;
# endif
