#define _ASM_IA64_SPARSEMEM_H
#define SECTION_SIZE_BITS	(30)
#define MAX_PHYSMEM_BITS	(50)
#if ((CONFIG_FORCE_MAX_ZONEORDER - 1 + PAGE_SHIFT) > SECTION_SIZE_BITS)
#undef SECTION_SIZE_BITS
#define SECTION_SIZE_BITS (CONFIG_FORCE_MAX_ZONEORDER - 1 + PAGE_SHIFT)
