int vq_init(struct c2_dev *c2dev)
void vq_term(struct c2_dev *c2dev)
struct c2_vq_req *vq_req_alloc(struct c2_dev *c2dev)
void vq_req_free(struct c2_dev *c2dev, struct c2_vq_req *r)
void vq_req_get(struct c2_dev *c2dev, struct c2_vq_req *r)
void vq_req_put(struct c2_dev *c2dev, struct c2_vq_req *r)
void *vq_repbuf_alloc(struct c2_dev *c2dev)
int vq_send_wr(struct c2_dev *c2dev, union c2wr *wr)
int vq_wait_for_reply(struct c2_dev *c2dev, struct c2_vq_req *req)
void vq_repbuf_free(struct c2_dev *c2dev, void *reply)
