const char *via_slap = "Please slap VIA Technologies to motivate them "
"releasing full documentation for your platform!\n";
static inline u32 cle266_encode_pll(struct via_pll_config pll)
static inline u32 k800_encode_pll(struct via_pll_config pll)
static inline u32 vx855_encode_pll(struct via_pll_config pll)
static inline void cle266_set_primary_pll_encoded(u32 data)
static inline void k800_set_primary_pll_encoded(u32 data)
static inline void cle266_set_secondary_pll_encoded(u32 data)
static inline void k800_set_secondary_pll_encoded(u32 data)
static inline void set_engine_pll_encoded(u32 data)
static void cle266_set_primary_pll(struct via_pll_config config)
static void k800_set_primary_pll(struct via_pll_config config)
static void vx855_set_primary_pll(struct via_pll_config config)
static void cle266_set_secondary_pll(struct via_pll_config config)
static void k800_set_secondary_pll(struct via_pll_config config)
static void vx855_set_secondary_pll(struct via_pll_config config)
static void k800_set_engine_pll(struct via_pll_config config)
static void vx855_set_engine_pll(struct via_pll_config config)
static void set_primary_pll_state(u8 state)
static void set_secondary_pll_state(u8 state)
static void set_engine_pll_state(u8 state)
static void set_primary_clock_state(u8 state)
static void set_secondary_clock_state(u8 state)
static inline u8 set_clock_source_common(enum via_clksrc source, bool use_pll)
static void set_primary_clock_source(enum via_clksrc source, bool use_pll)
static void set_secondary_clock_source(enum via_clksrc source, bool use_pll)
static void dummy_set_clock_state(u8 state)
static void dummy_set_clock_source(enum via_clksrc source, bool use_pll)
static void dummy_set_pll_state(u8 state)
static void dummy_set_pll(struct via_pll_config config)
void via_clock_init(struct via_clock *clock, int gfx_chip)
