#define __SMP_H
struct smp_command_hdr  __packed;
#define SMP_CMD_PAIRING_REQ	0x01
#define SMP_CMD_PAIRING_RSP	0x02
struct smp_cmd_pairing  __packed;
#define SMP_CMD_PAIRING_CONFIRM	0x03
struct smp_cmd_pairing_confirm  __packed;
#define SMP_CMD_PAIRING_RANDOM	0x04
struct smp_cmd_pairing_random  __packed;
#define SMP_CMD_PAIRING_FAIL	0x05
struct smp_cmd_pairing_fail  __packed;
#define SMP_CMD_ENCRYPT_INFO	0x06
struct smp_cmd_encrypt_info  __packed;
#define SMP_CMD_MASTER_IDENT	0x07
struct smp_cmd_master_ident  __packed;
#define SMP_CMD_IDENT_INFO	0x08
struct smp_cmd_ident_info  __packed;
#define SMP_CMD_IDENT_ADDR_INFO	0x09
struct smp_cmd_ident_addr_info  __packed;
#define SMP_CMD_SIGN_INFO	0x0a
struct smp_cmd_sign_info  __packed;
#define SMP_CMD_SECURITY_REQ	0x0b
struct smp_cmd_security_req  __packed;
#define SMP_PASSKEY_ENTRY_FAILED	0x01
#define SMP_OOB_NOT_AVAIL		0x02
#define SMP_AUTH_REQUIREMENTS		0x03
#define SMP_CONFIRM_FAILED		0x04
#define SMP_PAIRING_NOTSUPP		0x05
#define SMP_ENC_KEY_SIZE		0x06
#define SMP_CMD_NOTSUPP		0x07
#define SMP_UNSPECIFIED		0x08
#define SMP_REPEATED_ATTEMPTS		0x09
