#if !defined(_SND_PS3_H_)
#define _SND_PS3_H_
#define SND_PS3_DRIVER_NAME "snd_ps3"
enum snd_ps3_out_channel ;
enum snd_ps3_dma_filltype ;
enum snd_ps3_ch ;
struct snd_ps3_avsetting_info ;
struct snd_ps3_card_info ;
#define PS3_AUDIO_DMAC_BLOCK_SIZE (128)
#define PS3_AUDIO_FIFO_STAGE_SIZE (256)
#define PS3_AUDIO_FIFO_STAGE_COUNT (8)
#define PS3_AUDIO_FIFO_SIZE \
(PS3_AUDIO_FIFO_STAGE_SIZE * PS3_AUDIO_FIFO_STAGE_COUNT)
#define PS3_AUDIO_DMAC_MAX_BLOCKS  (PS3_AUDIO_DMASIZE_BLOCKS_MASK + 1)
#define PS3_AUDIO_NORMAL_DMA_START_CH (0)
#define PS3_AUDIO_NORMAL_DMA_COUNT    (8)
#define PS3_AUDIO_NULL_DMA_START_CH \
(PS3_AUDIO_NORMAL_DMA_START_CH + PS3_AUDIO_NORMAL_DMA_COUNT)
#define PS3_AUDIO_NULL_DMA_COUNT      (2)
#define SND_PS3_MAX_VOL (0x0F)
#define SND_PS3_MIN_VOL (0x00)
#define SND_PS3_MIN_ATT SND_PS3_MIN_VOL
#define SND_PS3_MAX_ATT SND_PS3_MAX_VOL
#define SND_PS3_PCM_PREALLOC_SIZE \
(PS3_AUDIO_DMAC_BLOCK_SIZE * PS3_AUDIO_DMAC_MAX_BLOCKS * 4)
#define SND_PS3_DMA_REGION_SIZE \
(SND_PS3_PCM_PREALLOC_SIZE + PAGE_SIZE)
#define PS3_AUDIO_IOID       (1UL)
