static int dbg_populate_lsave(struct ubifs_info *c);
#define dbg_populate_lsave(c) 0
static struct ubifs_cnode *first_dirty_cnode(struct ubifs_nnode *nnode)
static struct ubifs_cnode *next_dirty_cnode(struct ubifs_cnode *cnode)
static int get_cnodes_to_commit(struct ubifs_info *c)
static void upd_ltab(struct ubifs_info *c, int lnum, int free, int dirty)
static int alloc_lpt_leb(struct ubifs_info *c, int *lnum)
static int layout_cnodes(struct ubifs_info *c)
static int realloc_lpt_leb(struct ubifs_info *c, int *lnum)
static int write_cnodes(struct ubifs_info *c)
static struct ubifs_pnode *next_pnode_to_dirty(struct ubifs_info *c,
struct ubifs_pnode *pnode)
static struct ubifs_pnode *pnode_lookup(struct ubifs_info *c, int i)
static void add_pnode_dirt(struct ubifs_info *c, struct ubifs_pnode *pnode)
static void do_make_pnode_dirty(struct ubifs_info *c, struct ubifs_pnode *pnode)
static int make_tree_dirty(struct ubifs_info *c)
static int need_write_all(struct ubifs_info *c)
static void lpt_tgc_start(struct ubifs_info *c)
static int lpt_tgc_end(struct ubifs_info *c)
static void populate_lsave(struct ubifs_info *c)
static struct ubifs_nnode *nnode_lookup(struct ubifs_info *c, int i)
static int make_nnode_dirty(struct ubifs_info *c, int node_num, int lnum,
int offs)
static int make_pnode_dirty(struct ubifs_info *c, int node_num, int lnum,
int offs)
static int make_ltab_dirty(struct ubifs_info *c, int lnum, int offs)
static int make_lsave_dirty(struct ubifs_info *c, int lnum, int offs)
static int make_node_dirty(struct ubifs_info *c, int node_type, int node_num,
int lnum, int offs)
static int get_lpt_node_len(const struct ubifs_info *c, int node_type)
static int get_pad_len(const struct ubifs_info *c, uint8_t *buf, int len)
static int get_lpt_node_type(const struct ubifs_info *c, uint8_t *buf,
int *node_num)
static int is_a_node(const struct ubifs_info *c, uint8_t *buf, int len)
static int lpt_gc_lnum(struct ubifs_info *c, int lnum)
static int lpt_gc(struct ubifs_info *c)
int ubifs_lpt_start_commit(struct ubifs_info *c)
static void free_obsolete_cnodes(struct ubifs_info *c)
int ubifs_lpt_end_commit(struct ubifs_info *c)
int ubifs_lpt_post_commit(struct ubifs_info *c)
static struct ubifs_nnode *first_nnode(struct ubifs_info *c, int *hght)
static struct ubifs_nnode *next_nnode(struct ubifs_info *c,
struct ubifs_nnode *nnode, int *hght)
void ubifs_lpt_free(struct ubifs_info *c, int wr_only)
static int dbg_is_all_ff(uint8_t *buf, int len)
static int dbg_is_nnode_dirty(struct ubifs_info *c, int lnum, int offs)
static int dbg_is_pnode_dirty(struct ubifs_info *c, int lnum, int offs)
static int dbg_is_ltab_dirty(struct ubifs_info *c, int lnum, int offs)
static int dbg_is_lsave_dirty(struct ubifs_info *c, int lnum, int offs)
static int dbg_is_node_dirty(struct ubifs_info *c, int node_type, int lnum,
int offs)
static int dbg_check_ltab_lnum(struct ubifs_info *c, int lnum)
int dbg_check_ltab(struct ubifs_info *c)
int dbg_chk_lpt_free_spc(struct ubifs_info *c)
int dbg_chk_lpt_sz(struct ubifs_info *c, int action, int len)
static void dump_lpt_leb(const struct ubifs_info *c, int lnum)
void dbg_dump_lpt_lebs(const struct ubifs_info *c)
static int dbg_populate_lsave(struct ubifs_info *c)
