static inline void set_page_poison(struct page *page)
static inline void clear_page_poison(struct page *page)
static inline bool page_poison(struct page *page)
static void poison_highpage(struct page *page)
static void poison_page(struct page *page)
static void poison_pages(struct page *page, int n)
static bool single_bit_flip(unsigned char a, unsigned char b)
static void check_poison_mem(unsigned char *mem, size_t bytes)
static void unpoison_highpage(struct page *page)
static void unpoison_page(struct page *page)
static void unpoison_pages(struct page *page, int n)
void kernel_map_pages(struct page *page, int numpages, int enable)
