static inline void loadSingle(const unsigned int Fn, const unsigned int __user *pMem)
static inline void loadDouble(const unsigned int Fn, const unsigned int __user *pMem)
static inline void loadExtended(const unsigned int Fn, const unsigned int __user *pMem)
static inline void loadMultiple(const unsigned int Fn, const unsigned int __user *pMem)
static inline void storeSingle(struct roundingData *roundData, const unsigned int Fn, unsigned int __user *pMem)
static inline void storeDouble(struct roundingData *roundData, const unsigned int Fn, unsigned int __user *pMem)
static inline void storeExtended(const unsigned int Fn, unsigned int __user *pMem)
static inline void storeMultiple(const unsigned int Fn, unsigned int __user *pMem)
unsigned int PerformLDF(const unsigned int opcode)
unsigned int PerformSTF(const unsigned int opcode)
unsigned int PerformLFM(const unsigned int opcode)
unsigned int PerformSFM(const unsigned int opcode)
unsigned int EmulateCPDT(const unsigned int opcode)
