static inline void eeprom_cmd(uint32_t cmd, struct scsi_qla_host *ha)
static inline int eeprom_size(struct scsi_qla_host *ha)
static inline int eeprom_no_addr_bits(struct scsi_qla_host *ha)
static inline int eeprom_no_data_bits(struct scsi_qla_host *ha)
static int fm93c56a_select(struct scsi_qla_host * ha)
static int fm93c56a_cmd(struct scsi_qla_host * ha, int cmd, int addr)
static int fm93c56a_deselect(struct scsi_qla_host * ha)
static int fm93c56a_datain(struct scsi_qla_host * ha, unsigned short *value)
static int eeprom_readword(int eepromAddr, u16 * value,
struct scsi_qla_host * ha)
u16 rd_nvram_word(struct scsi_qla_host * ha, int offset)
int qla4xxx_is_nvram_configuration_valid(struct scsi_qla_host * ha)
int ql4xxx_sem_spinlock(struct scsi_qla_host * ha, u32 sem_mask, u32 sem_bits)
void ql4xxx_sem_unlock(struct scsi_qla_host * ha, u32 sem_mask)
int ql4xxx_sem_lock(struct scsi_qla_host * ha, u32 sem_mask, u32 sem_bits)
