u32 read_pci_config(u8 bus, u8 slot, u8 func, u8 offset)
u8 read_pci_config_byte(u8 bus, u8 slot, u8 func, u8 offset)
u16 read_pci_config_16(u8 bus, u8 slot, u8 func, u8 offset)
void write_pci_config(u8 bus, u8 slot, u8 func, u8 offset,
u32 val)
void write_pci_config_byte(u8 bus, u8 slot, u8 func, u8 offset, u8 val)
void write_pci_config_16(u8 bus, u8 slot, u8 func, u8 offset, u16 val)
int early_pci_allowed(void)
void early_dump_pci_device(u8 bus, u8 slot, u8 func)
void early_dump_pci_devices(void)
