#define _INTERFACE_ADAPTER_H
typedef struct _BULK_ENDP_IN
BULK_ENDP_IN, *PBULK_ENDP_IN;
typedef struct _BULK_ENDP_OUT
BULK_ENDP_OUT, *PBULK_ENDP_OUT;
typedef struct _INTR_ENDP_IN
INTR_ENDP_IN, *PINTR_ENDP_IN;
typedef struct _INTR_ENDP_OUT
INTR_ENDP_OUT, *PINTR_ENDP_OUT;
typedef struct _USB_TCB
USB_TCB, *PUSB_TCB;
typedef struct _USB_RCB
USB_RCB, *PUSB_RCB;
typedef struct _S_INTERFACE_ADAPTER
S_INTERFACE_ADAPTER,*PS_INTERFACE_ADAPTER;
