typedef struct bytecode_align  bytecode_align;
bc_align_destroy;
bc_align_print;
bc_align_finalize;
bc_align_calc_len;
bc_align_expand;
bc_align_tobytes;
static const yasm_bytecode_callback bc_align_callback = ;
bc_align_destroy
bc_align_print
bc_align_finalize
bc_align_calc_len
bc_align_expand
bc_align_tobytes
yasm_bc_create_align
