struct yasm_dataval ;
typedef struct bytecode_data  bytecode_data;
bc_data_destroy;
bc_data_print;
bc_data_finalize;
bc_data_item_size;
bc_data_calc_len;
bc_data_tobytes;
static const yasm_bytecode_callback bc_data_callback = ;
bc_data_destroy
bc_data_print
bc_data_finalize
bc_data_item_size
bc_data_calc_len
bc_data_tobytes
yasm_bc_create_data
yasm_bc_create_leb128
yasm_dv_create_expr
yasm_dv_create_raw
yasm_dv_create_reserve
yasm_dv_get_value
yasm_dv_set_multiple
yasm_dv_get_multiple
yasm_dvs_delete
yasm_dvs_append
yasm_dvs_print
