typedef struct bytecode_incbin  bytecode_incbin;
bc_incbin_destroy;
bc_incbin_print;
bc_incbin_finalize;
bc_incbin_calc_len;
bc_incbin_tobytes;
static const yasm_bytecode_callback bc_incbin_callback = ;
bc_incbin_destroy
bc_incbin_print
bc_incbin_finalize
bc_incbin_calc_len
bc_incbin_tobytes
yasm_bc_create_incbin
