#define YASM_FLOATNUM_H
#define YASM_LIB_DECL
YASM_LIB_DECL
yasm_floatnum_initialize;
YASM_LIB_DECL
yasm_floatnum_cleanup;
*yasm_floatnum_create;
*yasm_floatnum_copy;
YASM_LIB_DECL
yasm_floatnum_destroy;
YASM_LIB_DECL
yasm_floatnum_calc;
YASM_LIB_DECL
yasm_floatnum_get_int;
YASM_LIB_DECL
yasm_floatnum_get_sized;
YASM_LIB_DECL
yasm_floatnum_check_size;
YASM_LIB_DECL
yasm_floatnum_print;
