yasm_ea_set_segreg
yasm_operand_create_reg
yasm_operand_create_segreg
yasm_operand_create_mem
yasm_operand_create_imm
yasm_insn_ops_append
yasm_insn_add_prefix
yasm_insn_add_seg_prefix
yasm_insn_initialize
yasm_insn_delete ( yasm_effaddr *))
yasm_insn_print
yasm_insn_finalize
