#define BITVECT_NATIVE_SIZE     256
struct yasm_intnum ;
static wordptr conv_bv;
static wordptr result, spare, op1static, op2static;
static BitVector_from_Dec_static_data *from_dec_data;
yasm_intnum_initialize
yasm_intnum_cleanup
intnum_frombv
intnum_tobv
yasm_intnum_create_dec
yasm_intnum_create_bin
yasm_intnum_create_oct
yasm_intnum_create_hex
yasm_intnum_create_charconst_nasm
yasm_intnum_create_charconst_tasm
yasm_intnum_create_uint
yasm_intnum_create_int
yasm_intnum_create_leb128
yasm_intnum_create_sized
yasm_intnum_copy
yasm_intnum_destroy
yasm_intnum_calc
yasm_intnum_compare
yasm_intnum_zero
yasm_intnum_set
yasm_intnum_set_uint
yasm_intnum_set_int
yasm_intnum_is_zero
yasm_intnum_is_pos1
yasm_intnum_is_neg1
yasm_intnum_sign
yasm_intnum_get_uint
yasm_intnum_get_int
yasm_intnum_get_sized
yasm_intnum_check_size
yasm_intnum_in_range
get_leb128
size_leb128
yasm_intnum_get_leb128
yasm_intnum_size_leb128
yasm_get_sleb128
yasm_size_sleb128
yasm_get_uleb128
yasm_size_uleb128
yasm_intnum_get_str
yasm_intnum_print
