typedef struct line_mapping  line_mapping;
typedef struct line_source_info  line_source_info;
struct yasm_linemap ;
filename_delete_one
yasm_linemap_set
yasm_linemap_poke
yasm_linemap_create
yasm_linemap_destroy
yasm_linemap_get_current
yasm_linemap_add_source
yasm_linemap_goto_next
yasm_linemap_lookup
yasm_linemap_traverse_filenames (const char *filename, void *d))
yasm_linemap_get_source
