struct yasm_section ;
yasm_section_destroy;
typedef struct yasm_directive_wrap  yasm_directive_wrap;
dir_extern
dir_global
dir_common
dir_section
static const yasm_directive object_directives[] = ;
directive_level2_delete
directive_level1_delete
directives_add
yasm_object_create
yasm_object_get_general
yasm_object_directive
yasm_object_set_source_fn
yasm_object_set_global_prefix
yasm_object_set_global_suffix
yasm_section_is_code
yasm_section_get_opt_flags
yasm_section_set_opt_flags
yasm_section_is_default
yasm_section_set_default
yasm_section_get_object
yasm_section_get_data
yasm_section_add_data
yasm_object_destroy
yasm_object_print
yasm_object_finalize
yasm_object_sections_traverse (yasm_section *sect, void *d))
yasm_object_find_general
yasm_section_add_reloc ( void *reloc))
yasm_section_relocs_first
yasm_section_reloc_next
yasm_reloc_get
yasm_section_bcs_first
yasm_section_bcs_last
yasm_section_bcs_append
yasm_section_bcs_traverse (yasm_bytecode *bc, void *d))
yasm_section_get_name
yasm_section_set_align
yasm_section_get_align
yasm_section_destroy
yasm_section_print
typedef struct yasm_span yasm_span;
typedef struct yasm_offset_setter  yasm_offset_setter;
typedef struct yasm_span_term  yasm_span_term;
struct yasm_span ;
typedef struct optimize_data  optimize_data;
create_span
optimize_add_span
add_span_term
span_create_terms
recalc_normal_span
update_all_bc_offsets
span_destroy
optimize_cleanup
optimize_itree_add
check_cycle
optimize_term_expand
yasm_object_optimize
