#define OUTPUT_BIT_RATE 96000
#define OUTPUT_CHANNELS 2
*get_error_text
open_input_file
open_output_file
init_packet
init_input_frame
init_resampler
init_fifo
write_output_file_header
decode_audio_frame
init_converted_samples
convert_samples
add_samples_to_fifo
read_decode_convert_and_store
init_output_frame
static int64_t pts = 0;
encode_audio_frame
load_encode_and_write
write_output_file_trailer
main
