#if HAVE_VSX
static void fft32_vsx_interleave(FFTComplex *z)
static void fft64_vsx_interleave(FFTComplex *z)
static void fft128_vsx_interleave(FFTComplex *z)
static void fft256_vsx_interleave(FFTComplex *z)
static void fft512_vsx_interleave(FFTComplex *z)
static void fft1024_vsx_interleave(FFTComplex *z)
static void fft2048_vsx_interleave(FFTComplex *z)
static void fft4096_vsx_interleave(FFTComplex *z)
static void fft8192_vsx_interleave(FFTComplex *z)
static void fft16384_vsx_interleave(FFTComplex *z)
static void fft32768_vsx_interleave(FFTComplex *z)
static void fft65536_vsx_interleave(FFTComplex *z)
static void fft32_vsx(FFTComplex *z)
static void fft64_vsx(FFTComplex *z)
static void fft128_vsx(FFTComplex *z)
static void fft256_vsx(FFTComplex *z)
static void fft512_vsx(FFTComplex *z)
static void fft1024_vsx(FFTComplex *z)
static void fft2048_vsx(FFTComplex *z)
static void fft4096_vsx(FFTComplex *z)
static void fft8192_vsx(FFTComplex *z)
static void fft16384_vsx(FFTComplex *z)
static void fft32768_vsx(FFTComplex *z)
static void fft65536_vsx(FFTComplex *z)
static void (* const fft_dispatch_vsx[])(FFTComplex*) = ;
static void (* const fft_dispatch_vsx_interleave[])(FFTComplex*) = ;
void ff_fft_calc_interleave_vsx(FFTContext *s, FFTComplex *z)
void ff_fft_calc_vsx(FFTContext *s, FFTComplex *z)
