static inline void cache_wback_all(void)
static void sh7705_flush_icache_range(void *args)
static void __flush_dcache_page(unsigned long phys)
static void sh7705_flush_dcache_page(void *arg)
static void sh7705_flush_cache_all(void *args)
static void sh7705_flush_cache_page(void *args)
static void sh7705_flush_icache_page(void *page)
void __init sh7705_cache_init(void)
