enum aa_code ;
struct aa_ext ;
static void audit_cb(struct audit_buffer *ab, void *va)
static int audit_iface(struct aa_profile *new, const char *name,
const char *info, struct aa_ext *e, int error)
static bool inbounds(struct aa_ext *e, size_t size)
static size_t unpack_u16_chunk(struct aa_ext *e, char **chunk)
static bool unpack_X(struct aa_ext *e, enum aa_code code)
static bool unpack_nameX(struct aa_ext *e, enum aa_code code, const char *name)
static bool unpack_u32(struct aa_ext *e, u32 *data, const char *name)
static bool unpack_u64(struct aa_ext *e, u64 *data, const char *name)
static size_t unpack_array(struct aa_ext *e, const char *name)
static size_t unpack_blob(struct aa_ext *e, char **blob, const char *name)
static int unpack_str(struct aa_ext *e, const char **string, const char *name)
static int unpack_strdup(struct aa_ext *e, char **string, const char *name)
static bool verify_accept(struct aa_dfa *dfa, int flags)
static struct aa_dfa *unpack_dfa(struct aa_ext *e)
static bool unpack_trans_table(struct aa_ext *e, struct aa_profile *profile)
static bool unpack_rlimits(struct aa_ext *e, struct aa_profile *profile)
static struct aa_profile *unpack_profile(struct aa_ext *e)
static int verify_header(struct aa_ext *e, const char **ns)
static bool verify_xindex(int xindex, int table_size)
static bool verify_dfa_xindex(struct aa_dfa *dfa, int table_size)
static int verify_profile(struct aa_profile *profile)
struct aa_profile *aa_unpack(void *udata, size_t size, const char **ns)
