#define SMSC_CONFIG_PORT_ADDR	 (0x3F0)
#define SMSC_INDEX_PORT_ADDR	 SMSC_CONFIG_PORT_ADDR
#define SMSC_DATA_PORT_ADDR	 (SMSC_INDEX_PORT_ADDR + 1)
#define SMSC_ENTER_CONFIG_KEY	 0x55
#define SMSC_EXIT_CONFIG_KEY	 0xaa
#define SMCS_LOGICAL_DEV_INDEX	 0x07
#define SMSC_DEVICE_ID_INDEX	 0x20
#define SMSC_DEVICE_REV_INDEX	 0x21
#define SMSC_ACTIVATE_INDEX	 0x30
#define SMSC_PRIMARY_BASE_INDEX	 0x60
#define SMSC_SECONDARY_BASE_INDEX 0x62
#define SMSC_PRIMARY_INT_INDEX	 0x70
#define SMSC_SECONDARY_INT_INDEX 0x72
#define SMSC_HDCS0_INDEX	 0xf0
#define SMSC_HDCS1_INDEX	 0xf1
#define SMSC_IDE1_DEVICE	1
#define SMSC_IDE2_DEVICE	2
#define SMSC_PARALLEL_DEVICE	3
#define SMSC_SERIAL1_DEVICE	4
#define SMSC_SERIAL2_DEVICE	5
#define SMSC_KEYBOARD_DEVICE	7
#define SMSC_CONFIG_REGISTERS	8
#define SMSC_READ_INDEXED(index) ()
#define SMSC_WRITE_INDEXED(val, index) ()
#define	IDE1_PRIMARY_BASE	0x01f0
#define	IDE1_SECONDARY_BASE	0x03f6
#define	IDE2_PRIMARY_BASE	0x0170
#define	IDE2_SECONDARY_BASE	0x0376
#define SERIAL1_PRIMARY_BASE	0x03f8
#define SERIAL2_PRIMARY_BASE	0x02f8
#define	MSB(x)		( (x) >> 8 )
#define	LSB(x)		( (x) & 0xff )
#define	MICRODEV_FPGA_GP_BASE		0xa6100000ul
static int __init smsc_superio_setup(void)
device_initcall(smsc_superio_setup);
