#if APPLE_SUPPORTS_QUICKTIME
#define PyMac_PRECHECK(rtn) do  while(0)
extern PyObject *_CtlObj_New(ControlHandle);
extern int _CtlObj_Convert(PyObject *, ControlHandle *);
#define CtlObj_New _CtlObj_New
#define CtlObj_Convert _CtlObj_Convert
static PyObject *CtlObj_WhichControl(ControlHandle);
#define as_Control(h) ((ControlHandle)h)
#define as_Resource(ctl) ((Handle)ctl)
#define GetControlRect(ctl, rectp) GetControlBounds(ctl, rectp)
#define MAXTABS 32
static int
ControlFontStyle_Convert(PyObject *v, ControlFontStyleRec *itself)
static PyObject *
PyControlID_New(ControlID *itself)
static int
PyControlID_Convert(PyObject *v, ControlID *itself)
static int
DataBrowserTableViewColumnDesc_Convert(PyObject *v, DataBrowserTableViewColumnDesc *itself)
static int
ControlButtonContentInfo_Convert(PyObject *v, ControlButtonContentInfo *itself)
static int
DataBrowserListViewHeaderDesc_Convert(PyObject *v, DataBrowserListViewHeaderDesc *itself)
static int
DataBrowserListViewColumnDesc_Convert(PyObject *v, DataBrowserListViewColumnDesc *itself)
#define kMyControlActionProcTag 'ACTN'
static PyObject *tracker;
static ControlActionUPP mytracker_upp;
static ControlActionUPP myactionproc_upp;
static ControlUserPaneKeyDownUPP mykeydownproc_upp;
static ControlUserPaneFocusUPP myfocusproc_upp;
static ControlUserPaneDrawUPP mydrawproc_upp;
static ControlUserPaneIdleUPP myidleproc_upp;
static ControlUserPaneHitTestUPP myhittestproc_upp;
static ControlUserPaneTrackingUPP mytrackingproc_upp;
static int settrackfunc(PyObject *);
static void clrtrackfunc(void);
static int setcallback(PyObject *, OSType, PyObject *, UniversalProcPtr *);
static PyObject *Ctl_Error;
PyTypeObject Control_Type;
#define CtlObj_Check(x) ((x)->ob_type == &Control_Type || PyObject_TypeCheck((x), &Control_Type))
typedef struct ControlObject  ControlObject;
PyObject *CtlObj_New(ControlHandle itself)
int CtlObj_Convert(PyObject *v, ControlHandle *p_itself)
static void CtlObj_dealloc(ControlObject *self)
static PyObject *CtlObj_HiliteControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_ShowControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_HideControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_IsControlActive(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_IsControlVisible(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_ActivateControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_DeactivateControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlVisibility(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_IsControlEnabled(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_EnableControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_DisableControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_Draw1Control(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetBestControlRect(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlFontStyle(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_DrawControlInCurrentPort(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetUpControlBackground(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetUpControlTextColor(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_DragControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_TestControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_HandleControlContextualMenuClick(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlClickActivation(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_HandleControlKey(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_HandleControlSetCursor(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_MoveControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SizeControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlTitle(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlTitle(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlTitleWithCFString(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_CopyControlTitleAsCFString(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlValue(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlValue(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlMinimum(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlMinimum(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlMaximum(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlMaximum(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlViewSize(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlViewSize(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControl32BitValue(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControl32BitValue(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControl32BitMaximum(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControl32BitMaximum(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControl32BitMinimum(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControl32BitMinimum(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_IsValidControlHandle(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlID(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlID(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlCommandID(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlCommandID(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_RemoveControlProperty(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlPropertyAttributes(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_ChangeControlPropertyAttributes(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlRegion(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlVariant(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlAction(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlReference(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlReference(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_EmbedControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_AutoEmbedControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetSuperControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_CountSubControls(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetIndexedSubControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlSupervisor(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlFeatures(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlDataSize(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_HandleControlDragTracking(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_HandleControlDragReceive(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlDragTrackingEnabled(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_IsControlDragTrackingEnabled(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlBounds(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_IsControlHilited(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlHilite(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlOwner(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlDataHandle(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlPopupMenuHandle(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlPopupMenuID(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlDataHandle(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlBounds(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlPopupMenuHandle(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlPopupMenuID(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetBevelButtonMenuValue(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetBevelButtonMenuValue(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetBevelButtonMenuHandle(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetBevelButtonContentInfo(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetBevelButtonTransform(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDisclosureTriangleLastValue(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetTabContentRect(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetTabEnabled(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetImageWellContentInfo(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetImageWellTransform(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserViewStyle(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserViewStyle(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_EnableDataBrowserEditCommand(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_ExecuteDataBrowserEditCommand(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserSelectionAnchor(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_MoveDataBrowserSelectionAnchor(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_OpenDataBrowserContainer(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_CloseDataBrowserContainer(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SortDataBrowserContainer(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserItems(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserItemCount(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_IsDataBrowserItemSelected(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserItemState(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_RevealDataBrowserItem(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserActiveItems(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserActiveItems(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserScrollBarInset(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserScrollBarInset(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserTarget(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserTarget(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserSortOrder(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserSortOrder(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserScrollPosition(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserScrollPosition(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserHasScrollBars(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserHasScrollBars(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserSortProperty(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserSortProperty(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserSelectionFlags(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserSelectionFlags(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserPropertyFlags(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserPropertyFlags(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserEditText(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_CopyDataBrowserEditText(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserEditText(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserEditItem(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserEditItem(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserItemPartBounds(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_RemoveDataBrowserTableViewColumn(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserTableViewColumnCount(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserTableViewHiliteStyle(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserTableViewHiliteStyle(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserTableViewRowHeight(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserTableViewRowHeight(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserTableViewColumnWidth(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserTableViewColumnWidth(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserTableViewItemRowHeight(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserTableViewItemRowHeight(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserTableViewNamedColumnWidth(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserTableViewNamedColumnWidth(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserTableViewGeometry(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserTableViewGeometry(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserTableViewItemID(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserTableViewItemRow(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserTableViewItemRow(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserTableViewColumnPosition(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserTableViewColumnPosition(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserTableViewColumnProperty(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_AutoSizeDataBrowserListViewColumns(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_AddDataBrowserListViewColumn(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserListViewHeaderBtnHeight(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserListViewHeaderBtnHeight(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserListViewUsePlainBackground(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserListViewUsePlainBackground(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserListViewDisclosureColumn(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserListViewDisclosureColumn(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserColumnViewPath(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserColumnViewPathLength(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetDataBrowserColumnViewDisplayType(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetDataBrowserColumnViewDisplayType(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_as_Resource(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlRect(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_DisposeControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_TrackControl(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_HandleControlClick(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlData(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlData(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlData_Handle(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_GetControlData_Handle(ControlObject *_self, PyObject *_args)
static PyObject *CtlObj_SetControlData_Callback(ControlObject *_self, PyObject *_args)
static PyMethodDef CtlObj_methods[] = ;
#define CtlObj_getsetlist NULL
static int CtlObj_compare(ControlObject *self, ControlObject *other)
#define CtlObj_repr NULL
static long CtlObj_hash(ControlObject *self)
#define CtlObj_tp_init 0
#define CtlObj_tp_alloc PyType_GenericAlloc
static PyObject *CtlObj_tp_new(PyTypeObject *type, PyObject *_args, PyObject *_kwds)
#define CtlObj_tp_free PyObject_Del
PyTypeObject Control_Type = ;
static PyObject *Ctl_NewControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_GetNewControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_DrawControls(PyObject *_self, PyObject *_args)
static PyObject *Ctl_UpdateControls(PyObject *_self, PyObject *_args)
static PyObject *Ctl_FindControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_IdleControls(PyObject *_self, PyObject *_args)
static PyObject *Ctl_GetControlByID(PyObject *_self, PyObject *_args)
static PyObject *Ctl_DumpControlHierarchy(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateRootControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_GetRootControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_GetKeyboardFocus(PyObject *_self, PyObject *_args)
static PyObject *Ctl_SetKeyboardFocus(PyObject *_self, PyObject *_args)
static PyObject *Ctl_AdvanceKeyboardFocus(PyObject *_self, PyObject *_args)
static PyObject *Ctl_ReverseKeyboardFocus(PyObject *_self, PyObject *_args)
static PyObject *Ctl_ClearKeyboardFocus(PyObject *_self, PyObject *_args)
static PyObject *Ctl_SetAutomaticControlDragTrackingEnabledForWindow(PyObject *_self, PyObject *_args)
static PyObject *Ctl_IsAutomaticControlDragTrackingEnabledForWindow(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateBevelButtonControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateSliderControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateDisclosureTriangleControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateProgressBarControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateRelevanceBarControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateLittleArrowsControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateChasingArrowsControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateSeparatorControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateGroupBoxControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateCheckGroupBoxControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreatePopupGroupBoxControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateImageWellControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreatePopupArrowControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreatePlacardControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateClockControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateUserPaneControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateEditTextControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateStaticTextControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreatePictureControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateIconControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateWindowHeaderControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreatePushButtonControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreatePushButtonWithIconControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateRadioButtonControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateCheckBoxControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateScrollBarControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreatePopupButtonControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateRadioGroupControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateScrollingTextBoxControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateDisclosureButtonControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateRoundButtonControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateDataBrowserControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateEditUnicodeTextControl(PyObject *_self, PyObject *_args)
static PyObject *Ctl_FindControlUnderMouse(PyObject *_self, PyObject *_args)
static PyObject *Ctl_as_Control(PyObject *_self, PyObject *_args)
static PyObject *Ctl_CreateTabsControl(PyObject *_self, PyObject *_args)
static PyMethodDef Ctl_methods[] = ;
static PyObject *
CtlObj_NewUnmanaged(ControlHandle itself)
static PyObject *
CtlObj_WhichControl(ControlHandle c)
static int
settrackfunc(PyObject *obj)
static void
clrtrackfunc(void)
static pascal void
mytracker(ControlHandle ctl, short part)
static int
setcallback(PyObject *myself, OSType which, PyObject *callback, UniversalProcPtr *uppp)
static PyObject *
callcallback(ControlObject *self, OSType which, PyObject *arglist)
static pascal void
myactionproc(ControlHandle control, SInt16 part)
static pascal ControlPartCode
mykeydownproc(ControlHandle control, SInt16 keyCode, SInt16 charCode, SInt16 modifiers)
static pascal ControlPartCode
myfocusproc(ControlHandle control, ControlPartCode part)
static pascal void
mydrawproc(ControlHandle control, SInt16 part)
static pascal void
myidleproc(ControlHandle control)
static pascal ControlPartCode
myhittestproc(ControlHandle control, Point where)
static pascal ControlPartCode
mytrackingproc(ControlHandle control, Point startPt, ControlActionUPP actionProc)
static PyMethodDef Ctl_methods[] = ;
void init_Ctl(void)
