static int status_to_error(u32 status)
void fhci_add_td_to_frame(struct fhci_time_frame *frame, struct td *td)
void fhci_add_tds_to_ed(struct ed *ed, struct td **td_list, int number)
static struct td *peek_td_from_ed(struct ed *ed)
struct td *fhci_remove_td_from_frame(struct fhci_time_frame *frame)
struct td *fhci_peek_td_from_frame(struct fhci_time_frame *frame)
struct td *fhci_remove_td_from_ed(struct ed *ed)
struct td *fhci_remove_td_from_done_list(struct fhci_controller_list *p_list)
void fhci_move_td_from_ed_to_done_list(struct fhci_usb *usb, struct ed *ed)
static void free_urb_priv(struct fhci_hcd *fhci, struct urb *urb)
void fhci_urb_complete_free(struct fhci_hcd *fhci, struct urb *urb)
void fhci_done_td(struct urb *urb, struct td *td)
void fhci_del_ed_list(struct fhci_hcd *fhci, struct ed *ed)
