#define UHCREV		(0x0000)
#define UHCHCON		(0x0004)
#define UHCCOMS		(0x0008)
#define UHCINTS		(0x000C)
#define UHCINTE		(0x0010)
#define UHCINTD		(0x0014)
#define UHCHCCA		(0x0018)
#define UHCPCED		(0x001C)
#define UHCCHED		(0x0020)
#define UHCCCED		(0x0024)
#define UHCBHED		(0x0028)
#define UHCBCED		(0x002C)
#define UHCDHEAD	(0x0030)
#define UHCFMI		(0x0034)
#define UHCFMR		(0x0038)
#define UHCFMN		(0x003C)
#define UHCPERS		(0x0040)
#define UHCLS		(0x0044)
#define UHCRHDA		(0x0048)
#define UHCRHDA_NOCP	(1 << 12)
#define UHCRHDA_OCPM	(1 << 11)
#define UHCRHDA_POTPGT(x) \
(((x) & 0xff) << 24)
#define UHCRHDB		(0x004C)
#define UHCRHS		(0x0050)
#define UHCRHPS1	(0x0054)
#define UHCRHPS2	(0x0058)
#define UHCRHPS3	(0x005C)
#define UHCSTAT		(0x0060)
#define UHCSTAT_UPS3	(1 << 16)
#define UHCSTAT_SBMAI	(1 << 15)
#define UHCSTAT_SBTAI	(1 << 14)
#define UHCSTAT_UPRI	(1 << 13)
#define UHCSTAT_UPS2	(1 << 12)
#define UHCSTAT_UPS1	(1 << 11)
#define UHCSTAT_HTA	(1 << 10)
#define UHCSTAT_HBA	(1 << 8)
#define UHCSTAT_RWUE	(1 << 7)
#define UHCHR           (0x0064)
#define UHCHR_SSEP3	(1 << 11)
#define UHCHR_SSEP2	(1 << 10)
#define UHCHR_SSEP1	(1 << 9)
#define UHCHR_PCPL	(1 << 7)
#define UHCHR_PSPL	(1 << 6)
#define UHCHR_SSE	(1 << 5)
#define UHCHR_UIT	(1 << 4)
#define UHCHR_SSDC	(1 << 3)
#define UHCHR_CGR	(1 << 2)
#define UHCHR_FHR	(1 << 1)
#define UHCHR_FSBIR	(1 << 0)
#define UHCHIE          (0x0068)
#define UHCHIE_UPS3IE	(1 << 14)
#define UHCHIE_UPRIE	(1 << 13)
#define UHCHIE_UPS2IE	(1 << 12)
#define UHCHIE_UPS1IE	(1 << 11)
#define UHCHIE_TAIE	(1 << 10)
#define UHCHIE_HBAIE	(1 << 8)
#define UHCHIE_RWIE	(1 << 7)
#define UHCHIT          (0x006C)
#define PXA_UHC_MAX_PORTNUM    3
struct pxa27x_ohci ;
#define to_pxa27x_ohci(hcd)	(struct pxa27x_ohci *)hcd_to_ohci(hcd)
static int pxa27x_ohci_select_pmm(struct pxa27x_ohci *ohci, int mode)
extern int usb_disabled(void);
static inline void pxa27x_setup_hc(struct pxa27x_ohci *ohci,
struct pxaohci_platform_data *inf)
static inline void pxa27x_reset_hc(struct pxa27x_ohci *ohci)
extern void pxa27x_clear_otgph(void);
#define pxa27x_clear_otgph()	do  while (0)
static int pxa27x_start_hc(struct pxa27x_ohci *ohci, struct device *dev)
static void pxa27x_stop_hc(struct pxa27x_ohci *ohci, struct device *dev)
int usb_hcd_pxa27x_probe (const struct hc_driver *driver, struct platform_device *pdev)
void usb_hcd_pxa27x_remove (struct usb_hcd *hcd, struct platform_device *pdev)
static int __devinit
ohci_pxa27x_start (struct usb_hcd *hcd)
static const struct hc_driver ohci_pxa27x_hc_driver = ;
static int ohci_hcd_pxa27x_drv_probe(struct platform_device *pdev)
static int ohci_hcd_pxa27x_drv_remove(struct platform_device *pdev)
static int ohci_hcd_pxa27x_drv_suspend(struct device *dev)
static int ohci_hcd_pxa27x_drv_resume(struct device *dev)
static const struct dev_pm_ops ohci_hcd_pxa27x_pm_ops = ;
MODULE_ALIAS("platform:pxa27x-ohci");
static struct platform_driver ohci_hcd_pxa27x_driver = ;
