MainForm::MainForm()
void MainForm::updateEmployeeView()
void MainForm::addDepartment()
void MainForm::deleteDepartment()
void MainForm::editEmployees()
void MainForm::createDepartmentPanel()
void MainForm::createEmployeePanel()
