#define STACK_SP(STACK)		*(STACK)
#define STACK_LR64(STACK)	*((unsigned long *)(STACK) + 2)
#define STACK_LR32(STACK)	*((unsigned int *)(STACK) + 1)
#define STACK_LR(STACK)		STACK_LR64(STACK)
#define STACK_LR(STACK)		STACK_LR32(STACK)
static unsigned int user_getsp32(unsigned int sp, int is_first)
static unsigned long user_getsp64(unsigned long sp, int is_first)
static unsigned long kernel_getsp(unsigned long sp, int is_first)
void op_powerpc_backtrace(struct pt_regs * const regs, unsigned int depth)
