#define AVDEVICE_AVDEVICE_H
avdevice_version;
*avdevice_configuration;
*avdevice_license;
avdevice_register_all;
*av_input_audio_device_next;
*av_input_video_device_next;
*av_output_audio_device_next;
*av_output_video_device_next;
typedef struct AVDeviceRect  AVDeviceRect;
enum AVAppToDevMessageType ;
enum AVDevToAppMessageType ;
avdevice_app_to_dev_control_message;
avdevice_dev_to_app_control_message;
typedef struct AVDeviceCapabilitiesQuery  AVDeviceCapabilitiesQuery;
extern const AVOption av_device_capabilities[];
avdevice_capabilities_create;
avdevice_capabilities_free;
typedef struct AVDeviceInfo  AVDeviceInfo;
typedef struct AVDeviceInfoList  AVDeviceInfoList;
avdevice_list_devices;
avdevice_free_list_devices;
avdevice_list_input_sources;
avdevice_list_output_sinks;
