extern
#if CONFIG_LIBZVBI
calc_parity_and_line_offset
teletext_data_unit_from_vbi_data
avpacket_queue_init
avpacket_queue_flush
avpacket_queue_end
avpacket_queue_size
avpacket_queue_put
avpacket_queue_get
class decklink_input_callback : public IDeckLinkInputCallback
;
decklink_input_callback::decklink_input_callback(AVFormatContext *_avctx) : m_refCount(0)
decklink_input_callback::~decklink_input_callback()
decklink_input_callback::AddRef
decklink_input_callback::Release
get_pkt_pts
decklink_input_callback::VideoInputFrameArrived
decklink_input_callback::VideoInputFormatChanged
decklink_start_input
extern
