extern
class decklink_frame : public IDeckLinkVideoFrame
;
class decklink_output_callback : public IDeckLinkVideoOutputCallback
;
decklink_setup_video
decklink_setup_audio
ff_decklink_write_trailer
decklink_write_video_packet
decklink_write_audio_packet
extern
