DECLARE_QUERYINTERFACE(libAVEnumMediaTypes,
)
DECLARE_ADDREF(libAVEnumMediaTypes)
DECLARE_RELEASE(libAVEnumMediaTypes)
libAVEnumMediaTypes_Next
libAVEnumMediaTypes_Skip
libAVEnumMediaTypes_Reset
libAVEnumMediaTypes_Clone
libAVEnumMediaTypes_Setup
DECLARE_CREATE(libAVEnumMediaTypes, libAVEnumMediaTypes_Setup(this, type), const AM_MEDIA_TYPE *type)
DECLARE_DESTROY(libAVEnumMediaTypes, nothing)
