DECLARE_QUERYINTERFACE(libAVFilter,
)
DECLARE_ADDREF(libAVFilter)
DECLARE_RELEASE(libAVFilter)
libAVFilter_GetClassID
libAVFilter_Stop
libAVFilter_Pause
libAVFilter_Run
libAVFilter_GetState
libAVFilter_SetSyncSource
libAVFilter_GetSyncSource
libAVFilter_EnumPins
libAVFilter_FindPin
libAVFilter_QueryFilterInfo
libAVFilter_JoinFilterGraph
libAVFilter_QueryVendorInfo
libAVFilter_Setup
libAVFilter_Cleanup
DECLARE_CREATE(libAVFilter, libAVFilter_Setup(this, priv_data, callback, type),
void *priv_data, void *callback, enum dshowDeviceType type)
DECLARE_DESTROY(libAVFilter, libAVFilter_Cleanup)
