typedef struct PulseData  PulseData;
pulse_audio_sink_device_cb
pulse_update_sink_info
pulse_audio_sink_input_cb
pulse_update_sink_input_info
pulse_event
pulse_stream_writable
pulse_overflow
pulse_underflow
pulse_stream_state
pulse_stream_wait
pulse_context_state
pulse_context_wait
pulse_stream_result
pulse_finish_stream_operation
pulse_set_pause
pulse_flash_stream
pulse_context_result
pulse_finish_context_operation
pulse_set_mute
pulse_set_volume
pulse_subscribe_events
pulse_map_channels_to_pulse
pulse_write_trailer
pulse_write_header
pulse_write_packet
pulse_write_frame
pulse_get_output_timestamp
pulse_get_device_list
pulse_control_message
OFFSET offsetof(PulseData, a)
#define E AV_OPT_FLAG_ENCODING_PARAM
static const AVOption options[] = ;
static const AVClass pulse_muxer_class = ;
AVOutputFormat ff_pulse_muxer = ;
