ff_codec_id_to_pulse_format
enum PulseAudioContextState ;
typedef struct PulseAudioDeviceList  PulseAudioDeviceList;
pa_state_cb
ff_pulse_audio_disconnect_context
ff_pulse_audio_connect_context
pulse_add_detected_device
pulse_audio_source_device_cb
pulse_audio_sink_device_cb
pulse_server_info_cb
ff_pulse_audio_get_devices
