#define AVDEVICE_PULSE_AUDIO_COMMON_H
ff_codec_id_to_pulse_format;
av_warn_unused_result
ff_pulse_audio_get_devices;
av_warn_unused_result
ff_pulse_audio_connect_context;
ff_pulse_audio_disconnect_context;
