#define AVDEVICE_VERSION_H
#define LIBAVDEVICE_VERSION_MAJOR  57
#define LIBAVDEVICE_VERSION_MINOR   1
#define LIBAVDEVICE_VERSION_MICRO 100
AV_VERSION_INT
AV_VERSION
#define LIBAVDEVICE_BUILD       LIBAVDEVICE_VERSION_INT
AV_STRINGIFY
