Tetrahedron::Tetrahedron(QWidget *parent)
: QGLWidget(parent)
void Tetrahedron::initializeGL()
void Tetrahedron::resizeGL(int width, int height)
void Tetrahedron::paintGL()
void Tetrahedron::mousePressEvent(QMouseEvent *event)
void Tetrahedron::mouseMoveEvent(QMouseEvent *event)
void Tetrahedron::mouseDoubleClickEvent(QMouseEvent *event)
void Tetrahedron::draw()
int Tetrahedron::faceAtPosition(const QPoint &pos)
