#define __ASM_MACH_JAZZ_FLOPPY_H
static inline unsigned char fd_inb(unsigned int port)
static inline void fd_outb(unsigned char value, unsigned int port)
static inline void fd_enable_dma(void)
static inline void fd_disable_dma(void)
static inline int fd_request_dma(void)
static inline void fd_free_dma(void)
static inline void fd_clear_dma_ff(void)
static inline void fd_set_dma_mode(char mode)
static inline void fd_set_dma_addr(char *a)
static inline void fd_set_dma_count(unsigned int count)
static inline int fd_get_dma_residue(void)
static inline void fd_enable_irq(void)
static inline void fd_disable_irq(void)
static inline int fd_request_irq(void)
static inline void fd_free_irq(void)
static inline unsigned long fd_getfdaddr1(void)
static inline unsigned long fd_dma_mem_alloc(unsigned long size)
static inline void fd_dma_mem_free(unsigned long addr, unsigned long size)
static inline unsigned long fd_drive_type(unsigned long n)
