#define AMIGACONFIG_H
#define BYTEORDER 4321
#define HAVE_BCOPY 1
#undef HAVE_CHECK_H
#define HAVE_MEMMOVE 1
#define HAVE_UNISTD_H 1
#define WORDS_BIGENDIAN
#define XML_CONTEXT_BYTES 1024
#define XML_DTD
#define XML_NS
