#define WATCOMCONFIG_H
#define WIN32_LEAN_AND_MEAN
#undef WIN32_LEAN_AND_MEAN
#define BYTEORDER 1234
#define HAVE_MEMMOVE 1
#define HAVE_UNISTD_H 1
#define PACKAGE_BUGREPORT
#define PACKAGE_NAME
#define PACKAGE_STRING
#undef PACKAGE_TARNAME
#define PACKAGE_VERSION
#define XML_CONTEXT_BYTES 1024
#define XML_DTD 1
#define XML_NS 1
