struct drbd_bitmap ;
#define bm_print_lock_info(m) __bm_print_lock_info(m, __func__)
static void __bm_print_lock_info(struct drbd_conf *mdev, const char *func)
void drbd_bm_lock(struct drbd_conf *mdev, char *why, enum bm_flag flags)
void drbd_bm_unlock(struct drbd_conf *mdev)
#define BM_PAGE_IDX_MASK	((1UL<<24)-1)
#define BM_PAGE_IO_LOCK		31
#define BM_PAGE_IO_ERROR	30
#define BM_PAGE_NEED_WRITEOUT	29
#define BM_PAGE_LAZY_WRITEOUT	28
static void bm_store_page_idx(struct page *page, unsigned long idx)
static unsigned long bm_page_to_idx(struct page *page)
static void bm_page_lock_io(struct drbd_conf *mdev, int page_nr)
static void bm_page_unlock_io(struct drbd_conf *mdev, int page_nr)
static void bm_set_page_unchanged(struct page *page)
static void bm_set_page_need_writeout(struct page *page)
static int bm_test_page_unchanged(struct page *page)
static void bm_set_page_io_err(struct page *page)
static void bm_clear_page_io_err(struct page *page)
static void bm_set_page_lazy_writeout(struct page *page)
static int bm_test_page_lazy_writeout(struct page *page)
static unsigned int bm_word_to_page_idx(struct drbd_bitmap *b, unsigned long long_nr)
static unsigned int bm_bit_to_page_idx(struct drbd_bitmap *b, u64 bitnr)
static unsigned long *__bm_map_pidx(struct drbd_bitmap *b, unsigned int idx, const enum km_type km)
static unsigned long *bm_map_pidx(struct drbd_bitmap *b, unsigned int idx)
static void __bm_unmap(unsigned long *p_addr, const enum km_type km)
;
static void bm_unmap(unsigned long *p_addr)
#define S2W(s)	((s)<<(BM_EXT_SHIFT-BM_BLOCK_SHIFT-LN2_BPL))
#define MLPP(X) ((X) & ((PAGE_SIZE/sizeof(long))-1))
#define LWPP (PAGE_SIZE/sizeof(long))
static void bm_free_pages(struct page **pages, unsigned long number)
static void bm_vk_free(void *ptr, int v)
static struct page **bm_realloc_pages(struct drbd_bitmap *b, unsigned long want)
int drbd_bm_init(struct drbd_conf *mdev)
sector_t drbd_bm_capacity(struct drbd_conf *mdev)
void drbd_bm_cleanup(struct drbd_conf *mdev)
#define BITS_PER_PAGE		(1UL << (PAGE_SHIFT + 3))
#define BITS_PER_PAGE_MASK	(BITS_PER_PAGE - 1)
#define BITS_PER_LONG_MASK	(BITS_PER_LONG - 1)
static int bm_clear_surplus(struct drbd_bitmap *b)
static void bm_set_surplus(struct drbd_bitmap *b)
static unsigned long bm_count_bits(struct drbd_bitmap *b)
static void bm_memset(struct drbd_bitmap *b, size_t offset, int c, size_t len)
int drbd_bm_resize(struct drbd_conf *mdev, sector_t capacity, int set_new_bits)
unsigned long _drbd_bm_total_weight(struct drbd_conf *mdev)
unsigned long drbd_bm_total_weight(struct drbd_conf *mdev)
size_t drbd_bm_words(struct drbd_conf *mdev)
unsigned long drbd_bm_bits(struct drbd_conf *mdev)
void drbd_bm_merge_lel(struct drbd_conf *mdev, size_t offset, size_t number,
unsigned long *buffer)
void drbd_bm_get_lel(struct drbd_conf *mdev, size_t offset, size_t number,
unsigned long *buffer)
void drbd_bm_set_all(struct drbd_conf *mdev)
void drbd_bm_clear_all(struct drbd_conf *mdev)
struct bm_aio_ctx ;
static void bm_async_io_complete(struct bio *bio, int error)
static void bm_page_io_async(struct bm_aio_ctx *ctx, int page_nr, int rw) __must_hold(local)
static int bm_rw(struct drbd_conf *mdev, int rw, unsigned lazy_writeout_upper_idx) __must_hold(local)
int drbd_bm_read(struct drbd_conf *mdev) __must_hold(local)
int drbd_bm_write(struct drbd_conf *mdev) __must_hold(local)
int drbd_bm_write_lazy(struct drbd_conf *mdev, unsigned upper_idx) __must_hold(local)
int drbd_bm_write_page(struct drbd_conf *mdev, unsigned int idx) __must_hold(local)
static unsigned long __bm_find_next(struct drbd_conf *mdev, unsigned long bm_fo,
const int find_zero_bit, const enum km_type km)
static unsigned long bm_find_next(struct drbd_conf *mdev,
unsigned long bm_fo, const int find_zero_bit)
unsigned long drbd_bm_find_next(struct drbd_conf *mdev, unsigned long bm_fo)
unsigned long _drbd_bm_find_next(struct drbd_conf *mdev, unsigned long bm_fo)
unsigned long _drbd_bm_find_next_zero(struct drbd_conf *mdev, unsigned long bm_fo)
static int __bm_change_bits_to(struct drbd_conf *mdev, const unsigned long s,
unsigned long e, int val)
static int bm_change_bits_to(struct drbd_conf *mdev, const unsigned long s,
const unsigned long e, int val)
int drbd_bm_set_bits(struct drbd_conf *mdev, const unsigned long s, const unsigned long e)
int drbd_bm_clear_bits(struct drbd_conf *mdev, const unsigned long s, const unsigned long e)
static inline void bm_set_full_words_within_one_page(struct drbd_bitmap *b,
int page_nr, int first_word, int last_word)
void _drbd_bm_set_bits(struct drbd_conf *mdev, const unsigned long s, const unsigned long e)
int drbd_bm_test_bit(struct drbd_conf *mdev, const unsigned long bitnr)
int drbd_bm_count_bits(struct drbd_conf *mdev, const unsigned long s, const unsigned long e)
int drbd_bm_e_weight(struct drbd_conf *mdev, unsigned long enr)
unsigned long drbd_bm_ALe_set_all(struct drbd_conf *mdev, unsigned long al_enr)
