#define _BATYPE_H_
#define 	TOTAL_TXBA_NUM	16
#define	TOTAL_RXBA_NUM	16
#define	BA_SETUP_TIMEOUT	200
#define	BA_INACT_TIMEOUT	60000
#define	BA_POLICY_DELAYED		0
#define	BA_POLICY_IMMEDIATE	1
#define	ADDBA_STATUS_SUCCESS			0
#define	ADDBA_STATUS_REFUSED		37
#define	ADDBA_STATUS_INVALID_PARAM	38
#define	DELBA_REASON_QSTA_LEAVING	36
#define	DELBA_REASON_END_BA			37
#define	DELBA_REASON_UNKNOWN_BA	38
#define	DELBA_REASON_TIMEOUT			39
typedef union _SEQUENCE_CONTROLSEQUENCE_CONTROL, *PSEQUENCE_CONTROL;
typedef union _BA_PARAM_SET  BA_PARAM_SET, *PBA_PARAM_SET;
typedef union _DELBA_PARAM_SET  DELBA_PARAM_SET, *PDELBA_PARAM_SET;
typedef struct _BA_RECORD  BA_RECORD, *PBA_RECORD;
