static irqreturn_t fnic_isr_legacy(int irq, void *data)
static irqreturn_t fnic_isr_msi(int irq, void *data)
static irqreturn_t fnic_isr_msix_rq(int irq, void *data)
static irqreturn_t fnic_isr_msix_wq(int irq, void *data)
static irqreturn_t fnic_isr_msix_wq_copy(int irq, void *data)
static irqreturn_t fnic_isr_msix_err_notify(int irq, void *data)
void fnic_free_intr(struct fnic *fnic)
int fnic_request_intr(struct fnic *fnic)
int fnic_set_intr_mode(struct fnic *fnic)
void fnic_clear_intr_mode(struct fnic *fnic)
