EXPORT_SYMBOL_GPL(kvmppc_trampoline_enter);
EXPORT_SYMBOL_GPL(kvmppc_trampoline_lowmem);
EXPORT_SYMBOL_GPL(kvmppc_rmcall);
EXPORT_SYMBOL_GPL(kvmppc_load_up_fpu);
EXPORT_SYMBOL_GPL(kvmppc_load_up_altivec);
EXPORT_SYMBOL_GPL(kvmppc_load_up_vsx);
