typedef struct FilterContext
FilterContext;
typedef struct ColorContext
ColorContext;
lum_h_scale
lum_convert
ff_init_desc_fmt_convert
ff_init_desc_hscale
chr_h_scale
chr_convert
ff_init_desc_cfmt_convert
ff_init_desc_chscale
no_chr_scale
ff_init_desc_no_chr
