#define SWSCALE_VERSION_H
#define LIBSWSCALE_VERSION_MAJOR   4
#define LIBSWSCALE_VERSION_MINOR   2
#define LIBSWSCALE_VERSION_MICRO 100
AV_VERSION_INT
AV_VERSION
#define LIBSWSCALE_BUILD        LIBSWSCALE_VERSION_INT
AV_STRINGIFY
#define FF_API_SWS_VECTOR            (LIBSWSCALE_VERSION_MAJOR < 6)
