static irqreturn_t aac_rx_intr_producer(int irq, void *dev_id)
static irqreturn_t aac_rx_intr_message(int irq, void *dev_id)
static void aac_rx_disable_interrupt(struct aac_dev *dev)
static void aac_rx_enable_interrupt_producer(struct aac_dev *dev)
static void aac_rx_enable_interrupt_message(struct aac_dev *dev)
static int rx_sync_cmd(struct aac_dev *dev, u32 command,
u32 p1, u32 p2, u32 p3, u32 p4, u32 p5, u32 p6,
u32 *status, u32 * r1, u32 * r2, u32 * r3, u32 * r4)
static void aac_rx_interrupt_adapter(struct aac_dev *dev)
static void aac_rx_notify_adapter(struct aac_dev *dev, u32 event)
static void aac_rx_start_adapter(struct aac_dev *dev)
static int aac_rx_check_health(struct aac_dev *dev)
int aac_rx_deliver_producer(struct fib * fib)
static int aac_rx_deliver_message(struct fib * fib)
static int aac_rx_ioremap(struct aac_dev * dev, u32 size)
static int aac_rx_restart_adapter(struct aac_dev *dev, int bled)
int aac_rx_select_comm(struct aac_dev *dev, int comm)
int _aac_rx_init(struct aac_dev *dev)
int aac_rx_init(struct aac_dev *dev)
