#define MAX_XLOG_SIZE (64 * 1024)
static void bri_cpu_trapped (PISDN_ADAPTER IoAdapter)
static void reset_bri_hardware (PISDN_ADAPTER IoAdapter)
static void stop_bri_hardware (PISDN_ADAPTER IoAdapter)
static int load_bri_hardware (PISDN_ADAPTER IoAdapter)
static int bri_ISR (struct _ISDN_ADAPTER* IoAdapter)
static void disable_bri_interrupt (PISDN_ADAPTER IoAdapter)
void prepare_maestra_functions (PISDN_ADAPTER IoAdapter)
