#define MAX_XLOG_SIZE  (64 * 1024)
static dword pri_ram_offset (ADAPTER* a)
static void pri_cpu_trapped (PISDN_ADAPTER IoAdapter)
static void reset_pri_hardware (PISDN_ADAPTER IoAdapter)
static void stop_pri_hardware (PISDN_ADAPTER IoAdapter)
static int load_pri_hardware (PISDN_ADAPTER IoAdapter)
static int pri_ISR (struct _ISDN_ADAPTER* IoAdapter)
static void disable_pri_interrupt (PISDN_ADAPTER IoAdapter)
static void prepare_common_pri_functions (PISDN_ADAPTER IoAdapter)
void prepare_pri_functions (PISDN_ADAPTER IoAdapter)
void prepare_pri2_functions (PISDN_ADAPTER IoAdapter)
