struct dialog_info dlg;
static void set_mono_theme(void)
#define DLG_COLOR(dialog, f, b, h) \
do  while (0)
static void set_classic_theme(void)
static void set_blackbg_theme(void)
static void set_bluetitle_theme(void)
static int set_theme(const char *theme)
static void init_one_color(struct dialog_color *color)
static void init_dialog_colors(void)
static void color_setup(const char *theme)
void attr_clear(WINDOW * win, int height, int width, chtype attr)
void dialog_clear(void)
int init_dialog(const char *backtitle)
void set_dialog_backtitle(const char *backtitle)
void end_dialog(int x, int y)
void print_title(WINDOW *dialog, const char *title, int width)
void print_autowrap(WINDOW * win, const char *prompt, int width, int y, int x)
void print_button(WINDOW * win, const char *label, int y, int x, int selected)
void
draw_box(WINDOW * win, int y, int x, int height, int width,
chtype box, chtype border)
void draw_shadow(WINDOW * win, int y, int x, int height, int width)
int first_alpha(const char *string, const char *exempt)
int on_key_esc(WINDOW *win)
int on_key_resize(void)
struct dialog_list *item_cur;
struct dialog_list item_nil;
struct dialog_list *item_head;
void item_reset(void)
void item_make(const char *fmt, ...)
void item_add_str(const char *fmt, ...)
void item_set_tag(char tag)
void item_set_data(void *ptr)
void item_set_selected(int val)
int item_activate_selected(void)
void *item_data(void)
char item_tag(void)
int item_count(void)
void item_set(int n)
int item_n(void)
const char *item_str(void)
int item_is_selected(void)
int item_is_tag(char tag)
