#define BSIZE 512
typedef struct yasm_preproc_raw  yasm_preproc_raw;
yasm_preproc_module yasm_raw_LTX_preproc;
raw_preproc_create
raw_preproc_destroy
raw_preproc_get_line
raw_preproc_get_included_file
raw_preproc_add_include_file
raw_preproc_predefine_macro
raw_preproc_undefine_macro
raw_preproc_define_builtin
raw_preproc_add_standard
yasm_preproc_module yasm_raw_LTX_preproc = ;
