#define __BFA_DEFS_SVC_H__
#define BFA_IOCFC_INTR_DELAY	1125
#define BFA_IOCFC_INTR_LATENCY	225
#define BFA_IOCFCOE_INTR_DELAY	25
#define BFA_IOCFCOE_INTR_LATENCY 5
struct bfa_iocfc_intr_attr_s ;
struct bfa_iocfc_fwcfg_s ;
struct bfa_iocfc_drvcfg_s ;
struct bfa_iocfc_cfg_s ;
struct bfa_fw_io_stats_s ;
struct bfa_fw_port_fpg_stats_s ;
struct bfa_fw_port_lksm_stats_s ;
struct bfa_fw_port_snsm_stats_s ;
struct bfa_fw_port_physm_stats_s ;
struct bfa_fw_fip_stats_s ;
struct bfa_fw_lps_stats_s ;
struct bfa_fw_fcoe_stats_s ;
struct bfa_fw_fcoe_port_stats_s ;
struct bfa_fw_fc_uport_stats_s ;
union bfa_fw_fc_port_stats_s ;
struct bfa_fw_port_stats_s ;
struct bfa_fw_fcxchg_stats_s ;
struct bfa_fw_lpsm_stats_s ;
struct bfa_fw_trunk_stats_s ;
struct bfa_fw_advsm_stats_s ;
struct bfa_fw_iocfc_stats_s ;
struct bfa_iocfc_attr_s ;
struct bfa_fw_eth_sndrcv_stats_s ;
struct bfa_fw_mac_mod_stats_s ;
struct bfa_fw_ct_mod_stats_s ;
struct bfa_fw_stats_s ;
#define BFA_IOCFC_PATHTOV_MAX	60
#define BFA_IOCFC_QDEPTH_MAX	2000
enum bfa_qos_state ;
enum bfa_qos_priority ;
enum bfa_qos_bw_alloc ;
struct bfa_qos_attr_s ;
#define  BFA_QOS_MAX_VC  16
struct bfa_qos_vc_info_s ;
struct bfa_qos_vc_attr_s ;
struct bfa_qos_stats_s ;
struct bfa_fcoe_stats_s ;
union bfa_fcport_stats_u ;
struct bfa_fcpim_del_itn_stats_s ;
struct bfa_itnim_iostats_s ;
enum bfa_port_states ;
enum bfa_port_type ;
enum bfa_port_topology ;
enum bfa_port_opmode ;
#define BFA_PORT_OPMODE_LB_HARD(_mode)			\
((_mode == BFA_PORT_OPMODE_LB_INT) ||		\
(_mode == BFA_PORT_OPMODE_LB_SLW) ||		\
(_mode == BFA_PORT_OPMODE_LB_EXT))
enum bfa_port_linkstate ;
enum bfa_port_linkstate_rsn ;
struct bfa_port_cfg_s ;
struct bfa_port_attr_s ;
struct bfa_port_fcpmap_s ;
struct bfa_port_rnid_s ;
struct bfa_fcport_fcf_s ;
enum bfa_trunk_state ;
struct bfa_trunk_vc_attr_s ;
struct bfa_port_link_s ;
enum bfa_trunk_link_fctl ;
enum bfa_trunk_link_state ;
#define BFA_TRUNK_MAX_PORTS	2
struct bfa_trunk_link_attr_s ;
struct bfa_trunk_attr_s ;
struct bfa_rport_hal_stats_s ;
struct bfa_rport_qos_attr_s ;
#define BFA_IOBUCKET_MAX 14
struct bfa_itnim_latency_s ;
struct bfa_itnim_ioprofile_s ;
struct bfa_port_fc_stats_s ;
struct bfa_port_eth_stats_s ;
union bfa_port_stats_u ;
