#define __ARCH_ARM_MACH_OMAP2_OMAP_HWMOD_COMMON_DATA_H
extern struct omap_hwmod_class l3_hwmod_class;
extern struct omap_hwmod_class l4_hwmod_class;
extern struct omap_hwmod_class mpu_hwmod_class;
extern struct omap_hwmod_class iva_hwmod_class;
