static struct omap_hwmod omap2430_mpu_hwmod;
static struct omap_hwmod omap2430_iva_hwmod;
static struct omap_hwmod omap2430_l3_main_hwmod;
static struct omap_hwmod omap2430_l4_core_hwmod;
static struct omap_hwmod omap2430_dss_core_hwmod;
static struct omap_hwmod omap2430_dss_dispc_hwmod;
static struct omap_hwmod omap2430_dss_rfbi_hwmod;
static struct omap_hwmod omap2430_dss_venc_hwmod;
static struct omap_hwmod omap2430_wd_timer2_hwmod;
static struct omap_hwmod omap2430_gpio1_hwmod;
static struct omap_hwmod omap2430_gpio2_hwmod;
static struct omap_hwmod omap2430_gpio3_hwmod;
static struct omap_hwmod omap2430_gpio4_hwmod;
static struct omap_hwmod omap2430_gpio5_hwmod;
static struct omap_hwmod omap2430_dma_system_hwmod;
static struct omap_hwmod omap2430_mcbsp1_hwmod;
static struct omap_hwmod omap2430_mcbsp2_hwmod;
static struct omap_hwmod omap2430_mcbsp3_hwmod;
static struct omap_hwmod omap2430_mcbsp4_hwmod;
static struct omap_hwmod omap2430_mcbsp5_hwmod;
static struct omap_hwmod omap2430_mcspi1_hwmod;
static struct omap_hwmod omap2430_mcspi2_hwmod;
static struct omap_hwmod omap2430_mcspi3_hwmod;
static struct omap_hwmod omap2430_mmc1_hwmod;
static struct omap_hwmod omap2430_mmc2_hwmod;
static struct omap_hwmod_ocp_if omap2430_l3_main__l4_core = ;
static struct omap_hwmod_ocp_if omap2430_mpu__l3_main = ;
static struct omap_hwmod_ocp_if *omap2430_l3_main_slaves[] = ;
static struct omap_hwmod_ocp_if omap2430_dss__l3 = ;
static struct omap_hwmod_ocp_if *omap2430_l3_main_masters[] = ;
static struct omap_hwmod omap2430_l3_main_hwmod = ;
static struct omap_hwmod omap2430_l4_wkup_hwmod;
static struct omap_hwmod omap2430_uart1_hwmod;
static struct omap_hwmod omap2430_uart2_hwmod;
static struct omap_hwmod omap2430_uart3_hwmod;
static struct omap_hwmod omap2430_i2c1_hwmod;
static struct omap_hwmod omap2430_i2c2_hwmod;
static struct omap_hwmod omap2430_usbhsotg_hwmod;
static struct omap_hwmod_ocp_if omap2430_usbhsotg__l3 = ;
#define OMAP2_I2C_AS_LEN		128
static struct omap_hwmod_addr_space omap2430_i2c1_addr_space[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__i2c1 = ;
static struct omap_hwmod_addr_space omap2430_i2c2_addr_space[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__i2c2 = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__l4_wkup = ;
static struct omap_hwmod_addr_space omap2430_uart1_addr_space[] = ;
static struct omap_hwmod_ocp_if omap2_l4_core__uart1 = ;
static struct omap_hwmod_addr_space omap2430_uart2_addr_space[] = ;
static struct omap_hwmod_ocp_if omap2_l4_core__uart2 = ;
static struct omap_hwmod_addr_space omap2430_uart3_addr_space[] = ;
static struct omap_hwmod_ocp_if omap2_l4_core__uart3 = ;
static struct omap_hwmod_addr_space omap2430_usbhsotg_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__usbhsotg = ;
static struct omap_hwmod_ocp_if *omap2430_usbhsotg_masters[] = ;
static struct omap_hwmod_ocp_if *omap2430_usbhsotg_slaves[] = ;
static struct omap_hwmod_addr_space omap2430_mmc1_addr_space[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__mmc1 = ;
static struct omap_hwmod_addr_space omap2430_mmc2_addr_space[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__mmc2 = ;
static struct omap_hwmod_ocp_if *omap2430_l4_core_slaves[] = ;
static struct omap_hwmod_ocp_if *omap2430_l4_core_masters[] = ;
static struct omap_hwmod omap2430_l4_core_hwmod = ;
static struct omap_hwmod_ocp_if *omap2430_l4_wkup_slaves[] = ;
static struct omap_hwmod_ocp_if *omap2430_l4_wkup_masters[] = ;
static struct omap_hwmod_addr_space omap2430_mcspi1_addr_space[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__mcspi1 = ;
static struct omap_hwmod_addr_space omap2430_mcspi2_addr_space[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__mcspi2 = ;
static struct omap_hwmod_addr_space omap2430_mcspi3_addr_space[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__mcspi3 = ;
static struct omap_hwmod omap2430_l4_wkup_hwmod = ;
static struct omap_hwmod_ocp_if *omap2430_mpu_masters[] = ;
static struct omap_hwmod omap2430_mpu_hwmod = ;
static struct omap_hwmod_ocp_if omap2430_l3__iva = ;
static struct omap_hwmod_ocp_if *omap2430_iva_masters[] = ;
static struct omap_hwmod omap2430_iva_hwmod = ;
static struct omap_hwmod_class_sysconfig omap2430_timer_sysc = ;
static struct omap_hwmod_class omap2430_timer_hwmod_class = ;
static struct omap_hwmod omap2430_timer1_hwmod;
static struct omap_hwmod_irq_info omap2430_timer1_mpu_irqs[] = ;
static struct omap_hwmod_addr_space omap2430_timer1_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_wkup__timer1 = ;
static struct omap_hwmod_ocp_if *omap2430_timer1_slaves[] = ;
static struct omap_hwmod omap2430_timer1_hwmod = ;
static struct omap_hwmod omap2430_timer2_hwmod;
static struct omap_hwmod_irq_info omap2430_timer2_mpu_irqs[] = ;
static struct omap_hwmod_addr_space omap2430_timer2_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__timer2 = ;
static struct omap_hwmod_ocp_if *omap2430_timer2_slaves[] = ;
static struct omap_hwmod omap2430_timer2_hwmod = ;
static struct omap_hwmod omap2430_timer3_hwmod;
static struct omap_hwmod_irq_info omap2430_timer3_mpu_irqs[] = ;
static struct omap_hwmod_addr_space omap2430_timer3_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__timer3 = ;
static struct omap_hwmod_ocp_if *omap2430_timer3_slaves[] = ;
static struct omap_hwmod omap2430_timer3_hwmod = ;
static struct omap_hwmod omap2430_timer4_hwmod;
static struct omap_hwmod_irq_info omap2430_timer4_mpu_irqs[] = ;
static struct omap_hwmod_addr_space omap2430_timer4_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__timer4 = ;
static struct omap_hwmod_ocp_if *omap2430_timer4_slaves[] = ;
static struct omap_hwmod omap2430_timer4_hwmod = ;
static struct omap_hwmod omap2430_timer5_hwmod;
static struct omap_hwmod_irq_info omap2430_timer5_mpu_irqs[] = ;
static struct omap_hwmod_addr_space omap2430_timer5_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__timer5 = ;
static struct omap_hwmod_ocp_if *omap2430_timer5_slaves[] = ;
static struct omap_hwmod omap2430_timer5_hwmod = ;
static struct omap_hwmod omap2430_timer6_hwmod;
static struct omap_hwmod_irq_info omap2430_timer6_mpu_irqs[] = ;
static struct omap_hwmod_addr_space omap2430_timer6_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__timer6 = ;
static struct omap_hwmod_ocp_if *omap2430_timer6_slaves[] = ;
static struct omap_hwmod omap2430_timer6_hwmod = ;
static struct omap_hwmod omap2430_timer7_hwmod;
static struct omap_hwmod_irq_info omap2430_timer7_mpu_irqs[] = ;
static struct omap_hwmod_addr_space omap2430_timer7_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__timer7 = ;
static struct omap_hwmod_ocp_if *omap2430_timer7_slaves[] = ;
static struct omap_hwmod omap2430_timer7_hwmod = ;
static struct omap_hwmod omap2430_timer8_hwmod;
static struct omap_hwmod_irq_info omap2430_timer8_mpu_irqs[] = ;
static struct omap_hwmod_addr_space omap2430_timer8_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__timer8 = ;
static struct omap_hwmod_ocp_if *omap2430_timer8_slaves[] = ;
static struct omap_hwmod omap2430_timer8_hwmod = ;
static struct omap_hwmod omap2430_timer9_hwmod;
static struct omap_hwmod_irq_info omap2430_timer9_mpu_irqs[] = ;
static struct omap_hwmod_addr_space omap2430_timer9_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__timer9 = ;
static struct omap_hwmod_ocp_if *omap2430_timer9_slaves[] = ;
static struct omap_hwmod omap2430_timer9_hwmod = ;
static struct omap_hwmod omap2430_timer10_hwmod;
static struct omap_hwmod_irq_info omap2430_timer10_mpu_irqs[] = ;
static struct omap_hwmod_addr_space omap2430_timer10_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__timer10 = ;
static struct omap_hwmod_ocp_if *omap2430_timer10_slaves[] = ;
static struct omap_hwmod omap2430_timer10_hwmod = ;
static struct omap_hwmod omap2430_timer11_hwmod;
static struct omap_hwmod_irq_info omap2430_timer11_mpu_irqs[] = ;
static struct omap_hwmod_addr_space omap2430_timer11_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__timer11 = ;
static struct omap_hwmod_ocp_if *omap2430_timer11_slaves[] = ;
static struct omap_hwmod omap2430_timer11_hwmod = ;
static struct omap_hwmod omap2430_timer12_hwmod;
static struct omap_hwmod_irq_info omap2430_timer12_mpu_irqs[] = ;
static struct omap_hwmod_addr_space omap2430_timer12_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__timer12 = ;
static struct omap_hwmod_ocp_if *omap2430_timer12_slaves[] = ;
static struct omap_hwmod omap2430_timer12_hwmod = ;
static struct omap_hwmod_addr_space omap2430_wd_timer2_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_wkup__wd_timer2 = ;
static struct omap_hwmod_class_sysconfig omap2430_wd_timer_sysc = ;
static struct omap_hwmod_class omap2430_wd_timer_hwmod_class = ;
static struct omap_hwmod_ocp_if *omap2430_wd_timer2_slaves[] = ;
static struct omap_hwmod omap2430_wd_timer2_hwmod = ;
static struct omap_hwmod_class_sysconfig uart_sysc = ;
static struct omap_hwmod_class uart_class = ;
static struct omap_hwmod_irq_info uart1_mpu_irqs[] = ;
static struct omap_hwmod_dma_info uart1_sdma_reqs[] = ;
static struct omap_hwmod_ocp_if *omap2430_uart1_slaves[] = ;
static struct omap_hwmod omap2430_uart1_hwmod = ;
static struct omap_hwmod_irq_info uart2_mpu_irqs[] = ;
static struct omap_hwmod_dma_info uart2_sdma_reqs[] = ;
static struct omap_hwmod_ocp_if *omap2430_uart2_slaves[] = ;
static struct omap_hwmod omap2430_uart2_hwmod = ;
static struct omap_hwmod_irq_info uart3_mpu_irqs[] = ;
static struct omap_hwmod_dma_info uart3_sdma_reqs[] = ;
static struct omap_hwmod_ocp_if *omap2430_uart3_slaves[] = ;
static struct omap_hwmod omap2430_uart3_hwmod = ;
static struct omap_hwmod_class_sysconfig omap2430_dss_sysc = ;
static struct omap_hwmod_class omap2430_dss_hwmod_class = ;
static struct omap_hwmod_dma_info omap2430_dss_sdma_chs[] = ;
static struct omap_hwmod_ocp_if *omap2430_dss_masters[] = ;
static struct omap_hwmod_addr_space omap2430_dss_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__dss = ;
static struct omap_hwmod_ocp_if *omap2430_dss_slaves[] = ;
static struct omap_hwmod_opt_clk dss_opt_clks[] = ;
static struct omap_hwmod omap2430_dss_core_hwmod = ;
static struct omap_hwmod_class_sysconfig omap2430_dispc_sysc = ;
static struct omap_hwmod_class omap2430_dispc_hwmod_class = ;
static struct omap_hwmod_irq_info omap2430_dispc_irqs[] = ;
static struct omap_hwmod_addr_space omap2430_dss_dispc_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__dss_dispc = ;
static struct omap_hwmod_ocp_if *omap2430_dss_dispc_slaves[] = ;
static struct omap_hwmod omap2430_dss_dispc_hwmod = ;
static struct omap_hwmod_class_sysconfig omap2430_rfbi_sysc = ;
static struct omap_hwmod_class omap2430_rfbi_hwmod_class = ;
static struct omap_hwmod_addr_space omap2430_dss_rfbi_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__dss_rfbi = ;
static struct omap_hwmod_ocp_if *omap2430_dss_rfbi_slaves[] = ;
static struct omap_hwmod omap2430_dss_rfbi_hwmod = ;
static struct omap_hwmod_class omap2430_venc_hwmod_class = ;
static struct omap_hwmod_addr_space omap2430_dss_venc_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__dss_venc = ;
static struct omap_hwmod_ocp_if *omap2430_dss_venc_slaves[] = ;
static struct omap_hwmod omap2430_dss_venc_hwmod = ;
static struct omap_hwmod_class_sysconfig i2c_sysc = ;
static struct omap_hwmod_class i2c_class = ;
static struct omap_i2c_dev_attr i2c_dev_attr = ;
static struct omap_hwmod_irq_info i2c1_mpu_irqs[] = ;
static struct omap_hwmod_dma_info i2c1_sdma_reqs[] = ;
static struct omap_hwmod_ocp_if *omap2430_i2c1_slaves[] = ;
static struct omap_hwmod omap2430_i2c1_hwmod = ;
static struct omap_hwmod_irq_info i2c2_mpu_irqs[] = ;
static struct omap_hwmod_dma_info i2c2_sdma_reqs[] = ;
static struct omap_hwmod_ocp_if *omap2430_i2c2_slaves[] = ;
static struct omap_hwmod omap2430_i2c2_hwmod = ;
static struct omap_hwmod_addr_space omap2430_gpio1_addr_space[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_wkup__gpio1 = ;
static struct omap_hwmod_addr_space omap2430_gpio2_addr_space[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_wkup__gpio2 = ;
static struct omap_hwmod_addr_space omap2430_gpio3_addr_space[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_wkup__gpio3 = ;
static struct omap_hwmod_addr_space omap2430_gpio4_addr_space[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_wkup__gpio4 = ;
static struct omap_hwmod_addr_space omap2430_gpio5_addr_space[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__gpio5 = ;
static struct omap_gpio_dev_attr gpio_dev_attr = ;
static struct omap_hwmod_class_sysconfig omap243x_gpio_sysc = ;
static struct omap_hwmod_class omap243x_gpio_hwmod_class = ;
static struct omap_hwmod_irq_info omap243x_gpio1_irqs[] = ;
static struct omap_hwmod_ocp_if *omap2430_gpio1_slaves[] = ;
static struct omap_hwmod omap2430_gpio1_hwmod = ;
static struct omap_hwmod_irq_info omap243x_gpio2_irqs[] = ;
static struct omap_hwmod_ocp_if *omap2430_gpio2_slaves[] = ;
static struct omap_hwmod omap2430_gpio2_hwmod = ;
static struct omap_hwmod_irq_info omap243x_gpio3_irqs[] = ;
static struct omap_hwmod_ocp_if *omap2430_gpio3_slaves[] = ;
static struct omap_hwmod omap2430_gpio3_hwmod = ;
static struct omap_hwmod_irq_info omap243x_gpio4_irqs[] = ;
static struct omap_hwmod_ocp_if *omap2430_gpio4_slaves[] = ;
static struct omap_hwmod omap2430_gpio4_hwmod = ;
static struct omap_hwmod_irq_info omap243x_gpio5_irqs[] = ;
static struct omap_hwmod_ocp_if *omap2430_gpio5_slaves[] = ;
static struct omap_hwmod omap2430_gpio5_hwmod = ;
static struct omap_hwmod_class_sysconfig omap2430_dma_sysc = ;
static struct omap_hwmod_class omap2430_dma_hwmod_class = ;
static struct omap_dma_dev_attr dma_dev_attr = ;
static struct omap_hwmod_irq_info omap2430_dma_system_irqs[] = ;
static struct omap_hwmod_addr_space omap2430_dma_system_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_dma_system__l3 = ;
static struct omap_hwmod_ocp_if *omap2430_dma_system_masters[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__dma_system = ;
static struct omap_hwmod_ocp_if *omap2430_dma_system_slaves[] = ;
static struct omap_hwmod omap2430_dma_system_hwmod = ;
static struct omap_hwmod_class_sysconfig omap2430_mailbox_sysc = ;
static struct omap_hwmod_class omap2430_mailbox_hwmod_class = ;
static struct omap_hwmod omap2430_mailbox_hwmod;
static struct omap_hwmod_irq_info omap2430_mailbox_irqs[] = ;
static struct omap_hwmod_addr_space omap2430_mailbox_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__mailbox = ;
static struct omap_hwmod_ocp_if *omap2430_mailbox_slaves[] = ;
static struct omap_hwmod omap2430_mailbox_hwmod = ;
static struct omap_hwmod_class_sysconfig omap2430_mcspi_sysc = ;
static struct omap_hwmod_class omap2430_mcspi_class = ;
static struct omap_hwmod_irq_info omap2430_mcspi1_mpu_irqs[] = ;
static struct omap_hwmod_dma_info omap2430_mcspi1_sdma_reqs[] = ;
static struct omap_hwmod_ocp_if *omap2430_mcspi1_slaves[] = ;
static struct omap2_mcspi_dev_attr omap_mcspi1_dev_attr = ;
static struct omap_hwmod omap2430_mcspi1_hwmod = ;
static struct omap_hwmod_irq_info omap2430_mcspi2_mpu_irqs[] = ;
static struct omap_hwmod_dma_info omap2430_mcspi2_sdma_reqs[] = ;
static struct omap_hwmod_ocp_if *omap2430_mcspi2_slaves[] = ;
static struct omap2_mcspi_dev_attr omap_mcspi2_dev_attr = ;
static struct omap_hwmod omap2430_mcspi2_hwmod = ;
static struct omap_hwmod_irq_info omap2430_mcspi3_mpu_irqs[] = ;
static struct omap_hwmod_dma_info omap2430_mcspi3_sdma_reqs[] = ;
static struct omap_hwmod_ocp_if *omap2430_mcspi3_slaves[] = ;
static struct omap2_mcspi_dev_attr omap_mcspi3_dev_attr = ;
static struct omap_hwmod omap2430_mcspi3_hwmod = ;
static struct omap_hwmod_class_sysconfig omap2430_usbhsotg_sysc = ;
static struct omap_hwmod_class usbotg_class = ;
static struct omap_hwmod_irq_info omap2430_usbhsotg_mpu_irqs[] = ;
static struct omap_hwmod omap2430_usbhsotg_hwmod = ;
static struct omap_hwmod_class_sysconfig omap2430_mcbsp_sysc = ;
static struct omap_hwmod_class omap2430_mcbsp_hwmod_class = ;
static struct omap_hwmod_irq_info omap2430_mcbsp1_irqs[] = ;
static struct omap_hwmod_dma_info omap2430_mcbsp1_sdma_chs[] = ;
static struct omap_hwmod_addr_space omap2430_mcbsp1_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__mcbsp1 = ;
static struct omap_hwmod_ocp_if *omap2430_mcbsp1_slaves[] = ;
static struct omap_hwmod omap2430_mcbsp1_hwmod = ;
static struct omap_hwmod_irq_info omap2430_mcbsp2_irqs[] = ;
static struct omap_hwmod_dma_info omap2430_mcbsp2_sdma_chs[] = ;
static struct omap_hwmod_addr_space omap2430_mcbsp2_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__mcbsp2 = ;
static struct omap_hwmod_ocp_if *omap2430_mcbsp2_slaves[] = ;
static struct omap_hwmod omap2430_mcbsp2_hwmod = ;
static struct omap_hwmod_irq_info omap2430_mcbsp3_irqs[] = ;
static struct omap_hwmod_dma_info omap2430_mcbsp3_sdma_chs[] = ;
static struct omap_hwmod_addr_space omap2430_mcbsp3_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__mcbsp3 = ;
static struct omap_hwmod_ocp_if *omap2430_mcbsp3_slaves[] = ;
static struct omap_hwmod omap2430_mcbsp3_hwmod = ;
static struct omap_hwmod_irq_info omap2430_mcbsp4_irqs[] = ;
static struct omap_hwmod_dma_info omap2430_mcbsp4_sdma_chs[] = ;
static struct omap_hwmod_addr_space omap2430_mcbsp4_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__mcbsp4 = ;
static struct omap_hwmod_ocp_if *omap2430_mcbsp4_slaves[] = ;
static struct omap_hwmod omap2430_mcbsp4_hwmod = ;
static struct omap_hwmod_irq_info omap2430_mcbsp5_irqs[] = ;
static struct omap_hwmod_dma_info omap2430_mcbsp5_sdma_chs[] = ;
static struct omap_hwmod_addr_space omap2430_mcbsp5_addrs[] = ;
static struct omap_hwmod_ocp_if omap2430_l4_core__mcbsp5 = ;
static struct omap_hwmod_ocp_if *omap2430_mcbsp5_slaves[] = ;
static struct omap_hwmod omap2430_mcbsp5_hwmod = ;
static struct omap_hwmod_class_sysconfig omap2430_mmc_sysc = ;
static struct omap_hwmod_class omap2430_mmc_class = ;
static struct omap_hwmod_irq_info omap2430_mmc1_mpu_irqs[] = ;
static struct omap_hwmod_dma_info omap2430_mmc1_sdma_reqs[] = ;
static struct omap_hwmod_opt_clk omap2430_mmc1_opt_clks[] = ;
static struct omap_hwmod_ocp_if *omap2430_mmc1_slaves[] = ;
static struct omap_mmc_dev_attr mmc1_dev_attr = ;
static struct omap_hwmod omap2430_mmc1_hwmod = ;
static struct omap_hwmod_irq_info omap2430_mmc2_mpu_irqs[] = ;
static struct omap_hwmod_dma_info omap2430_mmc2_sdma_reqs[] = ;
static struct omap_hwmod_opt_clk omap2430_mmc2_opt_clks[] = ;
static struct omap_hwmod_ocp_if *omap2430_mmc2_slaves[] = ;
static struct omap_hwmod omap2430_mmc2_hwmod = ;
static __initdata struct omap_hwmod *omap2430_hwmods[] = ;
int __init omap2430_hwmod_init(void)
