#define __ARCH_ARM_MACH_OMAP2_PRM_H
#define OMAP_INTRANSITION_MASK				(1 << 20)
#define OMAP_POWERSTATEST_SHIFT				0
#define OMAP_POWERSTATEST_MASK				(0x3 << 0)
#define OMAP_POWERSTATE_SHIFT				0
#define OMAP_POWERSTATE_MASK				(0x3 << 0)
