#define PYTHON_EXE          (L)
#define PYTHON_EXE_LEN      (12)
#define KILL_PYTHON_EXE     (L)
#define KILL_PYTHON_EXE_LEN (17)
#define PYTHON_EXE          (L)
#define PYTHON_EXE_LEN      (10)
#define KILL_PYTHON_EXE     (L)
#define KILL_PYTHON_EXE_LEN (15)
int
main(int argc, char **argv)
