#define	_FC_ELS_H_
enum fc_els_cmd ;
#define	FC_ELS_CMDS_INIT
struct fc_els_ls_acc ;
struct fc_els_ls_rjt ;
enum fc_els_rjt_reason ;
enum fc_els_rjt_explan ;
struct fc_els_csp ;
#define	sp_tot_seq	sp_u.sp_plogi._sp_tot_seq
#define	sp_rel_off	sp_u.sp_plogi._sp_rel_off
#define	sp_r_a_tov	sp_u.sp_flogi_acc._sp_r_a_tov
#define	FC_SP_BB_DATA_MASK 0xfff
#define	FC_SP_MIN_MAX_PAYLOAD	FC_MIN_MAX_PAYLOAD
#define	FC_SP_MAX_MAX_PAYLOAD	FC_MAX_PAYLOAD
#define	FC_SP_FT_NPIV	0x8000
#define	FC_SP_FT_CIRO	0x8000
#define	FC_SP_FT_CLAD	0x8000
#define	FC_SP_FT_RAND	0x4000
#define	FC_SP_FT_VAL	0x2000
#define	FC_SP_FT_NPIV_ACC	0x2000
#define	FC_SP_FT_FPORT	0x1000
#define	FC_SP_FT_ABB	0x0800
#define	FC_SP_FT_EDTR	0x0400
#define	FC_SP_FT_MCAST	0x0200
#define	FC_SP_FT_BCAST	0x0100
#define	FC_SP_FT_HUNT	0x0080
#define	FC_SP_FT_SIMP	0x0040
#define	FC_SP_FT_SEC	0x0020
#define	FC_SP_FT_CSYN	0x0010
#define	FC_SP_FT_RTTOV	0x0008
#define	FC_SP_FT_HALF	0x0004
#define	FC_SP_FT_SEQC	0x0002
#define	FC_SP_FT_PAYL	0x0001
struct fc_els_cssp ;
#define	FC_CPC_VALID	0x8000
#define	FC_CPC_IMIX	0x4000
#define	FC_CPC_SEQ	0x0800
#define	FC_CPC_CAMP	0x0200
#define	FC_CPC_PRI	0x0080
#define	FC_CPI_CSYN	0x0010
#define	FC_CPR_CSYN	0x0008
struct fc_els_flogi  __attribute__((__packed__));
struct fc_els_spp ;
#define	FC_SPP_OPA_VAL	    0x80
#define	FC_SPP_RPA_VAL	    0x40
#define	FC_SPP_EST_IMG_PAIR 0x20
#define	FC_SPP_RESP_MASK    0x0f
enum fc_els_spp_resp ;
struct fc_els_rrq ;
struct fc_els_rec ;
struct fc_els_rec_acc ;
struct fc_els_prli ;
struct fc_els_prlo ;
struct fc_els_adisc  __attribute__((__packed__));
struct fc_els_logo ;
struct fc_els_rtv ;
struct fc_els_rtv_acc ;
#define	FC_ELS_RTV_EDRES (1 << 26)
#define	FC_ELS_RTV_RTTOV (1 << 19)
struct fc_els_scr ;
enum fc_els_scr_func ;
struct fc_els_rscn ;
struct fc_els_rscn_page ;
#define	ELS_RSCN_EV_QUAL_BIT	2
#define	ELS_RSCN_EV_QUAL_MASK	0xf
#define	ELS_RSCN_ADDR_FMT_BIT	0
#define	ELS_RSCN_ADDR_FMT_MASK	0x3
enum fc_els_rscn_ev_qual ;
enum fc_els_rscn_addr_fmt ;
struct fc_els_rnid ;
enum fc_els_rnid_fmt ;
struct fc_els_rnid_resp ;
struct fc_els_rnid_cid ;
struct fc_els_rnid_gen ;
enum fc_els_rnid_atype ;
enum fc_els_rnid_mgmt ;
enum fc_els_rnid_ipver ;
struct fc_els_rpl ;
struct fc_els_pnb ;
struct fc_els_rpl_resp ;
struct fc_els_lesb ;
struct fc_els_rps ;
enum fc_els_rps_flag ;
struct fc_els_rps_resp ;
enum fc_els_rps_resp_flag ;
enum fc_els_rps_resp_status ;
struct fc_els_lirr ;
enum fc_els_lirr_func ;
struct fc_els_srl ;
enum fc_els_srl_flag ;
struct fc_els_rls ;
struct fc_els_rls_resp ;
struct fc_els_rlir ;
struct fc_els_clir ;
enum fc_els_clir_ts_fmt ;
struct fc_els_clid ;
enum fc_els_clid_iq ;
enum fc_els_clid_ic ;
