#define _ASM_X86_ATOMIC64_64_H
#define ATOMIC64_INIT(i)
static inline long atomic64_read(const atomic64_t *v)
static inline void atomic64_set(atomic64_t *v, long i)
static inline void atomic64_add(long i, atomic64_t *v)
static inline void atomic64_sub(long i, atomic64_t *v)
static inline int atomic64_sub_and_test(long i, atomic64_t *v)
static inline void atomic64_inc(atomic64_t *v)
static inline void atomic64_dec(atomic64_t *v)
static inline int atomic64_dec_and_test(atomic64_t *v)
static inline int atomic64_inc_and_test(atomic64_t *v)
static inline int atomic64_add_negative(long i, atomic64_t *v)
static inline long atomic64_add_return(long i, atomic64_t *v)
static inline long atomic64_sub_return(long i, atomic64_t *v)
#define atomic64_inc_return(v)  (atomic64_add_return(1, (v)))
#define atomic64_dec_return(v)  (atomic64_sub_return(1, (v)))
static inline long atomic64_cmpxchg(atomic64_t *v, long old, long new)
static inline long atomic64_xchg(atomic64_t *v, long new)
static inline int atomic64_add_unless(atomic64_t *v, long a, long u)
#define atomic64_inc_not_zero(v) atomic64_add_unless((v), 1, 0)
static inline long atomic64_dec_if_positive(atomic64_t *v)
