#define _ASM_X86_BOOT_H
#define NORMAL_VGA	0xffff
#define EXTENDED_VGA	0xfffe
#define ASK_VGA		0xfffd
#define LOAD_PHYSICAL_ADDR ((CONFIG_PHYSICAL_START \
+ (CONFIG_PHYSICAL_ALIGN - 1)) \
& ~(CONFIG_PHYSICAL_ALIGN - 1))
#define MIN_KERNEL_ALIGN_LG2	PMD_SHIFT
#define MIN_KERNEL_ALIGN_LG2	(PAGE_SHIFT + THREAD_ORDER)
#define MIN_KERNEL_ALIGN	(_AC(1, UL) << MIN_KERNEL_ALIGN_LG2)
#if (CONFIG_PHYSICAL_ALIGN & (CONFIG_PHYSICAL_ALIGN-1)) || \
(CONFIG_PHYSICAL_ALIGN < MIN_KERNEL_ALIGN)
#error "Invalid value for CONFIG_PHYSICAL_ALIGN"
#define BOOT_HEAP_SIZE             0x400000
#define BOOT_HEAP_SIZE	0x8000
#define BOOT_STACK_SIZE	0x4000
#define BOOT_STACK_SIZE	0x1000
