#define _ASM_X86_MPSPEC_DEF_H
#define SMP_MAGIC_IDENT	(('_'<<24) | ('P'<<16) | ('M'<<8) | '_')
# define MAX_MPC_ENTRY 1024
struct mpf_intel ;
#define MPC_SIGNATURE "PCMP"
struct mpc_table ;
#define	MP_PROCESSOR		0
#define	MP_BUS			1
#define	MP_IOAPIC		2
#define	MP_INTSRC		3
#define	MP_LINTSRC		4
#define	MP_TRANSLATION		192
#define CPU_ENABLED		1
#define CPU_BOOTPROCESSOR	2
#define CPU_STEPPING_MASK	0x000F
#define CPU_MODEL_MASK		0x00F0
#define CPU_FAMILY_MASK		0x0F00
struct mpc_cpu ;
struct mpc_bus ;
#define BUSTYPE_EISA	"EISA"
#define BUSTYPE_ISA	"ISA"
#define BUSTYPE_INTERN	"INTERN"
#define BUSTYPE_MCA	"MCA"
#define BUSTYPE_VL	"VL"
#define BUSTYPE_PCI	"PCI"
#define BUSTYPE_PCMCIA	"PCMCIA"
#define BUSTYPE_CBUS	"CBUS"
#define BUSTYPE_CBUSII	"CBUSII"
#define BUSTYPE_FUTURE	"FUTURE"
#define BUSTYPE_MBI	"MBI"
#define BUSTYPE_MBII	"MBII"
#define BUSTYPE_MPI	"MPI"
#define BUSTYPE_MPSA	"MPSA"
#define BUSTYPE_NUBUS	"NUBUS"
#define BUSTYPE_TC	"TC"
#define BUSTYPE_VME	"VME"
#define BUSTYPE_XPRESS	"XPRESS"
#define MPC_APIC_USABLE		0x01
struct mpc_ioapic ;
struct mpc_intsrc ;
enum mp_irq_source_types ;
#define MP_IRQDIR_DEFAULT	0
#define MP_IRQDIR_HIGH		1
#define MP_IRQDIR_LOW		3
#define MP_APIC_ALL	0xFF
struct mpc_lintsrc ;
#define MPC_OEM_SIGNATURE "_OEM"
struct mpc_oemtable ;
enum mp_bustype ;
