static int get_tclk(void);
int mv78xx0_core_index(void)
static int get_hclk(void)
static void get_pclk_l2clk(int hclk, int core_index, int *pclk, int *l2clk)
static int get_tclk(void)
static struct map_desc mv78xx0_io_desc[] __initdata = ;
void __init mv78xx0_map_io(void)
void __init mv78xx0_ehci0_init(void)
void __init mv78xx0_ehci1_init(void)
void __init mv78xx0_ehci2_init(void)
void __init mv78xx0_ge00_init(struct mv643xx_eth_platform_data *eth_data)
void __init mv78xx0_ge01_init(struct mv643xx_eth_platform_data *eth_data)
void __init mv78xx0_ge10_init(struct mv643xx_eth_platform_data *eth_data)
void __init mv78xx0_ge11_init(struct mv643xx_eth_platform_data *eth_data)
void __init mv78xx0_i2c_init(void)
void __init mv78xx0_sata_init(struct mv_sata_platform_data *sata_data)
void __init mv78xx0_uart0_init(void)
void __init mv78xx0_uart1_init(void)
void __init mv78xx0_uart2_init(void)
void __init mv78xx0_uart3_init(void)
void __init mv78xx0_init_early(void)
static void mv78xx0_timer_init(void)
struct sys_timer mv78xx0_timer = ;
static char * __init mv78xx0_id(void)
static int __init is_l2_writethrough(void)
void __init mv78xx0_init(void)
