#if HAVE_UNISTD_H
#if !HAVE_GETOPT
#define LEN 240
fill_float_array
compare_floats
fill_double_array
compare_doubles
test_vector_fmul
#define ARBITRARY_FMAC_SCALAR_CONST 0.005
test_vector_fmac_scalar
test_vector_fmul_scalar
test_vector_dmul_scalar
#define ARBITRARY_FMUL_WINDOW_CONST 0.008
test_vector_fmul_window
#define ARBITRARY_FMUL_ADD_CONST 0.005
test_vector_fmul_add
test_vector_fmul_reverse
test_butterflies_float
#define ARBITRARY_SCALARPRODUCT_CONST 0.2
test_scalarproduct_float
main
