static void radeon_fence_write(struct radeon_device *rdev, u32 seq)
static u32 radeon_fence_read(struct radeon_device *rdev)
int radeon_fence_emit(struct radeon_device *rdev, struct radeon_fence *fence)
static bool radeon_fence_poll_locked(struct radeon_device *rdev)
static void radeon_fence_destroy(struct kref *kref)
int radeon_fence_create(struct radeon_device *rdev, struct radeon_fence **fence)
bool radeon_fence_signaled(struct radeon_fence *fence)
int radeon_fence_wait(struct radeon_fence *fence, bool intr)
int radeon_fence_wait_next(struct radeon_device *rdev)
int radeon_fence_wait_last(struct radeon_device *rdev)
struct radeon_fence *radeon_fence_ref(struct radeon_fence *fence)
void radeon_fence_unref(struct radeon_fence **fence)
void radeon_fence_process(struct radeon_device *rdev)
int radeon_fence_driver_init(struct radeon_device *rdev)
void radeon_fence_driver_fini(struct radeon_device *rdev)
#if defined(CONFIG_DEBUG_FS)
static int radeon_debugfs_fence_info(struct seq_file *m, void *data)
static struct drm_info_list radeon_debugfs_fence_list[] = ;
int radeon_debugfs_fence_init(struct radeon_device *rdev)
