static bool igp_read_bios_from_vram(struct radeon_device *rdev)
static bool radeon_read_bios(struct radeon_device *rdev)
static bool radeon_atrm_get_bios(struct radeon_device *rdev)
static bool ni_read_disabled_bios(struct radeon_device *rdev)
static bool r700_read_disabled_bios(struct radeon_device *rdev)
static bool r600_read_disabled_bios(struct radeon_device *rdev)
static bool avivo_read_disabled_bios(struct radeon_device *rdev)
static bool legacy_read_disabled_bios(struct radeon_device *rdev)
static bool radeon_read_disabled_bios(struct radeon_device *rdev)
bool radeon_get_bios(struct radeon_device *rdev)
