void mn10300_dcache_flush(void)
void mn10300_dcache_flush_page(unsigned long start)
void mn10300_dcache_flush_range(unsigned long start, unsigned long end)
void mn10300_dcache_flush_range2(unsigned long start, unsigned long size)
void mn10300_dcache_flush_inv(void)
void mn10300_dcache_flush_inv_page(unsigned long start)
void mn10300_dcache_flush_inv_range(unsigned long start, unsigned long end)
void mn10300_dcache_flush_inv_range2(unsigned long start, unsigned long size)
