int lpm_adjust(int lpm, int mask)
static u16 ccwreq_next_path(struct ccw_device *cdev)
static void ccwreq_stop(struct ccw_device *cdev, int rc)
static void ccwreq_do(struct ccw_device *cdev)
void ccw_request_start(struct ccw_device *cdev)
int ccw_request_cancel(struct ccw_device *cdev)
static enum io_status ccwreq_status(struct ccw_device *cdev, struct irb *lcirb)
static void ccwreq_log_status(struct ccw_device *cdev, enum io_status status)
void ccw_request_handler(struct ccw_device *cdev)
void ccw_request_timeout(struct ccw_device *cdev)
void ccw_request_notoper(struct ccw_device *cdev)
