#define _HOST_WLAN_CONFIG_H_
#define WLAN_CONFIG_DONOT_IGNORE_BARKER_IN_ERP 0
#define WLAN_CONFIG_IGNORE_POWER_SAVE_FAIL_EVENT_DURING_SCAN 0
#define WLAN_CONFIG_KEEP_ALIVE_INTERVAL 60
#define WLAN_CONFIG_DISCONNECT_TIMEOUT 10
#define WLAN_CONFIG_DISABLE_11N         0
#define WLAN_CONFIG_BT_SHARING          0
#define WLAN_CONFIG_WLAN_OFF                1
#define WLAN_CONFIG_PM_SUSPEND              0
#define WLAN_CONFIG_PM_WOW2                 0
#define WLAN_CONFIG_DISABLE_TX_BURSTING     0
