#define _XTENSA_ATOMIC_H
#define ATOMIC_INIT(i)
#define atomic_read(v)		(*(volatile int *)&(v)->counter)
#define atomic_set(v,i)		((v)->counter = (i))
static inline void atomic_add(int i, atomic_t * v)
static inline void atomic_sub(int i, atomic_t *v)
static inline int atomic_add_return(int i, atomic_t * v)
static inline int atomic_sub_return(int i, atomic_t * v)
#define atomic_sub_and_test(i,v) (atomic_sub_return((i),(v)) == 0)
#define atomic_inc(v) atomic_add(1,(v))
#define atomic_inc_return(v) atomic_add_return(1,(v))
#define atomic_dec(v) atomic_sub(1,(v))
#define atomic_dec_return(v) atomic_sub_return(1,(v))
#define atomic_dec_and_test(v) (atomic_sub_return(1,(v)) == 0)
#define atomic_inc_and_test(v) (atomic_add_return(1,(v)) == 0)
#define atomic_add_negative(i,v) (atomic_add_return((i),(v)) < 0)
#define atomic_cmpxchg(v, o, n) ((int)cmpxchg(&((v)->counter), (o), (n)))
#define atomic_xchg(v, new) (xchg(&((v)->counter), new))
static __inline__ int atomic_add_unless(atomic_t *v, int a, int u)
#define atomic_inc_not_zero(v) atomic_add_unless((v), 1, 0)
static inline void atomic_clear_mask(unsigned int mask, atomic_t *v)
static inline void atomic_set_mask(unsigned int mask, atomic_t *v)
#define smp_mb__before_atomic_dec()	barrier()
#define smp_mb__after_atomic_dec()	barrier()
#define smp_mb__before_atomic_inc()	barrier()
#define smp_mb__after_atomic_inc()	barrier()
