#define	__BPQETHER_H
#define SIOCSBPQETHOPT		(SIOCDEVPRIVATE+0)
#define SIOCSBPQETHADDR		(SIOCDEVPRIVATE+1)
struct bpq_ethaddr ;
#define SIOCGBPQETHPARAM	0x5000
#define SIOCSBPQETHPARAM	0x5001
struct bpq_req  ;
