#define _LINUX_IF_BONDING_H
#define BOND_ABI_VERSION 2
#define BOND_ENSLAVE_OLD		(SIOCDEVPRIVATE)
#define BOND_RELEASE_OLD		(SIOCDEVPRIVATE + 1)
#define BOND_SETHWADDR_OLD		(SIOCDEVPRIVATE + 2)
#define BOND_SLAVE_INFO_QUERY_OLD	(SIOCDEVPRIVATE + 11)
#define BOND_INFO_QUERY_OLD		(SIOCDEVPRIVATE + 12)
#define BOND_CHANGE_ACTIVE_OLD		(SIOCDEVPRIVATE + 13)
#define BOND_CHECK_MII_STATUS	(SIOCGMIIPHY)
#define BOND_MODE_ROUNDROBIN	0
#define BOND_MODE_ACTIVEBACKUP	1
#define BOND_MODE_XOR		2
#define BOND_MODE_BROADCAST	3
#define BOND_MODE_8023AD        4
#define BOND_MODE_TLB           5
#define BOND_MODE_ALB		6
#define BOND_LINK_UP    0
#define BOND_LINK_FAIL  1
#define BOND_LINK_DOWN  2
#define BOND_LINK_BACK  3
#define BOND_STATE_ACTIVE       0
#define BOND_STATE_BACKUP       1
#define BOND_DEFAULT_MAX_BONDS  1
#define BOND_DEFAULT_TX_QUEUES 16
#define BOND_DEFAULT_RESEND_IGMP	1
#define BOND_XMIT_POLICY_LAYER2		0
#define BOND_XMIT_POLICY_LAYER34	1
#define BOND_XMIT_POLICY_LAYER23	2
typedef struct ifbond  ifbond;
typedef struct ifslave  ifslave;
struct ad_info ;
