#define _LINUX_IF_FDDI_H
#define FDDI_K_ALEN			6
#define FDDI_K_8022_HLEN	16
#define FDDI_K_SNAP_HLEN	21
#define FDDI_K_8022_ZLEN	16
#define FDDI_K_SNAP_ZLEN	21
#define FDDI_K_8022_DLEN	4475
#define FDDI_K_SNAP_DLEN	4470
#define FDDI_K_LLC_ZLEN		13
#define FDDI_K_LLC_LEN		4491
#define FDDI_FC_K_VOID					0x00
#define FDDI_FC_K_NON_RESTRICTED_TOKEN	0x80
#define FDDI_FC_K_RESTRICTED_TOKEN		0xC0
#define FDDI_FC_K_SMT_MIN				0x41
#define FDDI_FC_K_SMT_MAX		   		0x4F
#define FDDI_FC_K_MAC_MIN				0xC1
#define FDDI_FC_K_MAC_MAX		  		0xCF
#define FDDI_FC_K_ASYNC_LLC_MIN			0x50
#define FDDI_FC_K_ASYNC_LLC_DEF			0x54
#define FDDI_FC_K_ASYNC_LLC_MAX			0x5F
#define FDDI_FC_K_SYNC_LLC_MIN			0xD0
#define FDDI_FC_K_SYNC_LLC_MAX			0xD7
#define FDDI_FC_K_IMPLEMENTOR_MIN		0x60
#define FDDI_FC_K_IMPLEMENTOR_MAX  		0x6F
#define FDDI_FC_K_RESERVED_MIN			0x70
#define FDDI_FC_K_RESERVED_MAX			0x7F
#define FDDI_EXTENDED_SAP	0xAA
#define FDDI_UI_CMD			0x03
struct fddi_8022_1_hdr  __attribute__((packed));
struct fddi_8022_2_hdr  __attribute__((packed));
#define FDDI_K_OUI_LEN	3
struct fddi_snap_hdr  __attribute__((packed));
struct fddihdr  __attribute__((packed));
struct fddi_statistics ;
