#define __ISDNIF_H__
#define ISDN_PTYPE_UNKNOWN   0
#define ISDN_PTYPE_1TR6      1
#define ISDN_PTYPE_EURO      2
#define ISDN_PTYPE_LEASED    3
#define ISDN_PTYPE_NI1       4
#define ISDN_PTYPE_MAX       7
#define ISDN_PROTO_L2_X75I   0
#define ISDN_PROTO_L2_X75UI  1
#define ISDN_PROTO_L2_X75BUI 2
#define ISDN_PROTO_L2_HDLC   3
#define ISDN_PROTO_L2_TRANS  4
#define ISDN_PROTO_L2_X25DTE 5
#define ISDN_PROTO_L2_X25DCE 6
#define ISDN_PROTO_L2_V11096 7
#define ISDN_PROTO_L2_V11019 8
#define ISDN_PROTO_L2_V11038 9
#define ISDN_PROTO_L2_MODEM  10
#define ISDN_PROTO_L2_FAX    11
#define ISDN_PROTO_L2_HDLC_56K 12
#define ISDN_PROTO_L2_MAX    15
#define ISDN_PROTO_L3_TRANS	0
#define ISDN_PROTO_L3_TRANSDSP	1
#define ISDN_PROTO_L3_FCLASS2	2
#define ISDN_PROTO_L3_FCLASS1	3
#define ISDN_PROTO_L3_MAX	7
#define DSS1_CMD_INVOKE       ((0x00 << 8) | ISDN_PTYPE_EURO)
#define DSS1_CMD_INVOKE_ABORT ((0x01 << 8) | ISDN_PTYPE_EURO)
#define DSS1_STAT_INVOKE_RES  ((0x80 << 8) | ISDN_PTYPE_EURO)
#define DSS1_STAT_INVOKE_ERR  ((0x81 << 8) | ISDN_PTYPE_EURO)
#define DSS1_STAT_INVOKE_BRD  ((0x82 << 8) | ISDN_PTYPE_EURO)
#define NI1_CMD_INVOKE       ((0x00 << 8) | ISDN_PTYPE_NI1)
#define NI1_CMD_INVOKE_ABORT ((0x01 << 8) | ISDN_PTYPE_NI1)
#define NI1_STAT_INVOKE_RES  ((0x80 << 8) | ISDN_PTYPE_NI1)
#define NI1_STAT_INVOKE_ERR  ((0x81 << 8) | ISDN_PTYPE_NI1)
#define NI1_STAT_INVOKE_BRD  ((0x82 << 8) | ISDN_PTYPE_NI1)
typedef struct
isdn_cmd_stat;
#define ISDN_CMD_IOCTL    0
#define ISDN_CMD_DIAL     1
#define ISDN_CMD_ACCEPTD  2
#define ISDN_CMD_ACCEPTB  3
#define ISDN_CMD_HANGUP   4
#define ISDN_CMD_CLREAZ   5
#define ISDN_CMD_SETEAZ   6
#define ISDN_CMD_GETEAZ   7
#define ISDN_CMD_SETSIL   8
#define ISDN_CMD_GETSIL   9
#define ISDN_CMD_SETL2   10
#define ISDN_CMD_GETL2   11
#define ISDN_CMD_SETL3   12
#define ISDN_CMD_GETL3   13
#define ISDN_CMD_SUSPEND 16
#define ISDN_CMD_RESUME  17
#define ISDN_CMD_PROCEED 18
#define ISDN_CMD_ALERT   19
#define ISDN_CMD_REDIR   20
#define ISDN_CMD_PROT_IO 21
#define CAPI_PUT_MESSAGE 22
#define ISDN_CMD_FAXCMD  23
#define ISDN_CMD_AUDIO   24
#define ISDN_STAT_STAVAIL 256
#define ISDN_STAT_ICALL   257
#define ISDN_STAT_RUN     258
#define ISDN_STAT_STOP    259
#define ISDN_STAT_DCONN   260
#define ISDN_STAT_BCONN   261
#define ISDN_STAT_DHUP    262
#define ISDN_STAT_BHUP    263
#define ISDN_STAT_CINF    264
#define ISDN_STAT_LOAD    265
#define ISDN_STAT_UNLOAD  266
#define ISDN_STAT_BSENT   267
#define ISDN_STAT_NODCH   268
#define ISDN_STAT_ADDCH   269
#define ISDN_STAT_CAUSE   270
#define ISDN_STAT_ICALLW  271
#define ISDN_STAT_REDIR   272
#define ISDN_STAT_PROT    273
#define ISDN_STAT_DISPLAY 274
#define ISDN_STAT_L1ERR   275
#define ISDN_STAT_FAXIND  276
#define ISDN_STAT_AUDIO   277
#define ISDN_STAT_DISCH   278
#define ISDN_AUDIO_SETDD	0
#define ISDN_AUDIO_DTMF		1
#define ISDN_STAT_L1ERR_SEND 1
#define ISDN_STAT_L1ERR_RECV 2
#define ISDN_FEATURE_L2_X75I    (0x0001 << ISDN_PROTO_L2_X75I)
#define ISDN_FEATURE_L2_X75UI   (0x0001 << ISDN_PROTO_L2_X75UI)
#define ISDN_FEATURE_L2_X75BUI  (0x0001 << ISDN_PROTO_L2_X75BUI)
#define ISDN_FEATURE_L2_HDLC    (0x0001 << ISDN_PROTO_L2_HDLC)
#define ISDN_FEATURE_L2_TRANS   (0x0001 << ISDN_PROTO_L2_TRANS)
#define ISDN_FEATURE_L2_X25DTE  (0x0001 << ISDN_PROTO_L2_X25DTE)
#define ISDN_FEATURE_L2_X25DCE  (0x0001 << ISDN_PROTO_L2_X25DCE)
#define ISDN_FEATURE_L2_V11096  (0x0001 << ISDN_PROTO_L2_V11096)
#define ISDN_FEATURE_L2_V11019  (0x0001 << ISDN_PROTO_L2_V11019)
#define ISDN_FEATURE_L2_V11038  (0x0001 << ISDN_PROTO_L2_V11038)
#define ISDN_FEATURE_L2_MODEM   (0x0001 << ISDN_PROTO_L2_MODEM)
#define ISDN_FEATURE_L2_FAX	(0x0001 << ISDN_PROTO_L2_FAX)
#define ISDN_FEATURE_L2_HDLC_56K (0x0001 << ISDN_PROTO_L2_HDLC_56K)
#define ISDN_FEATURE_L2_MASK    (0x0FFFF)
#define ISDN_FEATURE_L2_SHIFT   (0)
#define ISDN_FEATURE_L3_TRANS   (0x10000 << ISDN_PROTO_L3_TRANS)
#define ISDN_FEATURE_L3_TRANSDSP (0x10000 << ISDN_PROTO_L3_TRANSDSP)
#define ISDN_FEATURE_L3_FCLASS2	(0x10000 << ISDN_PROTO_L3_FCLASS2)
#define ISDN_FEATURE_L3_FCLASS1	(0x10000 << ISDN_PROTO_L3_FCLASS1)
#define ISDN_FEATURE_L3_MASK    (0x0FF0000)
#define ISDN_FEATURE_L3_SHIFT   (16)
#define ISDN_FEATURE_P_UNKNOWN  (0x1000000 << ISDN_PTYPE_UNKNOWN)
#define ISDN_FEATURE_P_1TR6     (0x1000000 << ISDN_PTYPE_1TR6)
#define ISDN_FEATURE_P_EURO     (0x1000000 << ISDN_PTYPE_EURO)
#define ISDN_FEATURE_P_NI1      (0x1000000 << ISDN_PTYPE_NI1)
#define ISDN_FEATURE_P_MASK     (0x0FF000000)
#define ISDN_FEATURE_P_SHIFT    (24)
typedef struct setup_parm  setup_parm;
#define FAXIDLEN 21
typedef struct T30_s  __packed T30_s;
#define ISDN_TTY_FAX_CONN_IN	0
#define ISDN_TTY_FAX_CONN_OUT	1
#define ISDN_TTY_FAX_FCON	0
#define ISDN_TTY_FAX_DIS 	1
#define ISDN_TTY_FAX_FTT 	2
#define ISDN_TTY_FAX_MCF 	3
#define ISDN_TTY_FAX_DCS 	4
#define ISDN_TTY_FAX_TRAIN_OK	5
#define ISDN_TTY_FAX_EOP 	6
#define ISDN_TTY_FAX_EOM 	7
#define ISDN_TTY_FAX_MPS 	8
#define ISDN_TTY_FAX_DTC 	9
#define ISDN_TTY_FAX_RID 	10
#define ISDN_TTY_FAX_HNG 	11
#define ISDN_TTY_FAX_DT  	12
#define ISDN_TTY_FAX_FCON_I	13
#define ISDN_TTY_FAX_DR  	14
#define ISDN_TTY_FAX_ET  	15
#define ISDN_TTY_FAX_CFR 	16
#define ISDN_TTY_FAX_PTS 	17
#define ISDN_TTY_FAX_SENT	18
#define ISDN_FAX_PHASE_IDLE	0
#define ISDN_FAX_PHASE_A	1
#define ISDN_FAX_PHASE_B   	2
#define ISDN_FAX_PHASE_C   	3
#define ISDN_FAX_PHASE_D   	4
#define ISDN_FAX_PHASE_E   	5
#define ISDN_FAX_CLASS1_FAE	0
#define ISDN_FAX_CLASS1_FTS	1
#define ISDN_FAX_CLASS1_FRS	2
#define ISDN_FAX_CLASS1_FTM	3
#define ISDN_FAX_CLASS1_FRM	4
#define ISDN_FAX_CLASS1_FTH	5
#define ISDN_FAX_CLASS1_FRH	6
#define ISDN_FAX_CLASS1_CTRL	7
#define ISDN_FAX_CLASS1_OK	0
#define ISDN_FAX_CLASS1_CONNECT	1
#define ISDN_FAX_CLASS1_NOCARR	2
#define ISDN_FAX_CLASS1_ERROR	3
#define ISDN_FAX_CLASS1_FCERROR	4
#define ISDN_FAX_CLASS1_QUERY	5
typedef struct  aux_s;
#define AT_COMMAND	0
#define AT_EQ_VALUE	1
#define AT_QUERY	2
#define AT_EQ_QUERY	3
#define MAX_CAPI_PARA_LEN 50
typedef struct  capi_msg;
typedef struct  isdn_ctrl;
#define dss1_io    isdn_io
#define ni1_io     isdn_io
typedef struct  isdn_if;
extern int register_isdn(isdn_if*);
