#define _LINUX_RDS_H
#define RDS_IB_ABI_VERSION		0x301
#define RDS_CANCEL_SENT_TO      	1
#define RDS_GET_MR			2
#define RDS_FREE_MR			3
#define RDS_RECVERR			5
#define RDS_CONG_MONITOR		6
#define RDS_GET_MR_FOR_DEST		7
#define RDS_CMSG_RDMA_ARGS		1
#define RDS_CMSG_RDMA_DEST		2
#define RDS_CMSG_RDMA_MAP		3
#define RDS_CMSG_RDMA_STATUS		4
#define RDS_CMSG_CONG_UPDATE		5
#define RDS_CMSG_ATOMIC_FADD		6
#define RDS_CMSG_ATOMIC_CSWP		7
#define RDS_CMSG_MASKED_ATOMIC_FADD	8
#define RDS_CMSG_MASKED_ATOMIC_CSWP	9
#define RDS_INFO_FIRST			10000
#define RDS_INFO_COUNTERS		10000
#define RDS_INFO_CONNECTIONS		10001
#define RDS_INFO_SEND_MESSAGES		10003
#define RDS_INFO_RETRANS_MESSAGES       10004
#define RDS_INFO_RECV_MESSAGES          10005
#define RDS_INFO_SOCKETS                10006
#define RDS_INFO_TCP_SOCKETS            10007
#define RDS_INFO_IB_CONNECTIONS		10008
#define RDS_INFO_CONNECTION_STATS	10009
#define RDS_INFO_IWARP_CONNECTIONS	10010
#define RDS_INFO_LAST			10010
struct rds_info_counter  __attribute__((packed));
#define RDS_INFO_CONNECTION_FLAG_SENDING	0x01
#define RDS_INFO_CONNECTION_FLAG_CONNECTING	0x02
#define RDS_INFO_CONNECTION_FLAG_CONNECTED	0x04
#define TRANSNAMSIZ	16
struct rds_info_connection  __attribute__((packed));
#define RDS_INFO_MESSAGE_FLAG_ACK               0x01
#define RDS_INFO_MESSAGE_FLAG_FAST_ACK          0x02
struct rds_info_message  __attribute__((packed));
struct rds_info_socket  __attribute__((packed));
struct rds_info_tcp_socket  __attribute__((packed));
#define RDS_IB_GID_LEN	16
struct rds_info_rdma_connection ;
#define RDS_CONG_MONITOR_SIZE	64
#define RDS_CONG_MONITOR_BIT(port)  (((unsigned int) port) % RDS_CONG_MONITOR_SIZE)
#define RDS_CONG_MONITOR_MASK(port) (1ULL << RDS_CONG_MONITOR_BIT(port))
typedef uint64_t	rds_rdma_cookie_t;
struct rds_iovec ;
struct rds_get_mr_args ;
struct rds_get_mr_for_dest_args ;
struct rds_free_mr_args ;
struct rds_rdma_args ;
struct rds_atomic_args ;
struct rds_rdma_notify ;
#define RDS_RDMA_SUCCESS	0
#define RDS_RDMA_REMOTE_ERROR	1
#define RDS_RDMA_CANCELED	2
#define RDS_RDMA_DROPPED	3
#define RDS_RDMA_OTHER_ERROR	4
#define RDS_RDMA_READWRITE	0x0001
#define RDS_RDMA_FENCE		0x0002
#define RDS_RDMA_INVALIDATE	0x0004
#define RDS_RDMA_USE_ONCE	0x0008
#define RDS_RDMA_DONTWAIT	0x0010
#define RDS_RDMA_NOTIFY_ME	0x0020
#define RDS_RDMA_SILENT		0x0040
