#define _LINUX_TASKSTATS_H
#define TASKSTATS_VERSION	8
#define TS_COMM_LEN		32
struct taskstats ;
enum ;
#define TASKSTATS_CMD_MAX (__TASKSTATS_CMD_MAX - 1)
enum ;
#define TASKSTATS_TYPE_MAX (__TASKSTATS_TYPE_MAX - 1)
enum ;
#define TASKSTATS_CMD_ATTR_MAX (__TASKSTATS_CMD_ATTR_MAX - 1)
#define TASKSTATS_GENL_NAME	"TASKSTATS"
#define TASKSTATS_GENL_VERSION	0x1
