#define AES_BLOCK_SIZE (16)
typedef struct AVAESCTR  AVAESCTR;
*av_aes_ctr_alloc
av_aes_ctr_set_iv
av_aes_ctr_get_iv
av_aes_ctr_set_random_iv
av_aes_ctr_init
av_aes_ctr_free
av_aes_ctr_increment_be64
av_aes_ctr_increment_iv
av_aes_ctr_crypt
