#define AVUTIL_ATOMIC_WIN32_H
#define WIN32_LEAN_AND_MEAN
#define avpriv_atomic_int_get atomic_int_get_win32
atomic_int_get_win32
#define avpriv_atomic_int_set atomic_int_set_win32
atomic_int_set_win32
#define avpriv_atomic_int_add_and_fetch atomic_int_add_and_fetch_win32
atomic_int_add_and_fetch_win32
#define avpriv_atomic_ptr_cas atomic_ptr_cas_win32
*atomic_ptr_cas_win32
