struct AVAudioFifo ;
av_audio_fifo_free
*av_audio_fifo_alloc
av_audio_fifo_realloc
av_audio_fifo_write
av_audio_fifo_peek
av_audio_fifo_peek_at
av_audio_fifo_read
av_audio_fifo_drain
av_audio_fifo_reset
av_audio_fifo_size
av_audio_fifo_space
