struct channel_name ;
static const struct channel_name channel_names[] = ;
*get_channel_name
static const struct  channel_layout_map[] = ;
get_channel_layout_single
av_get_channel_layout
av_bprint_channel_layout
av_get_channel_layout_string
av_get_channel_layout_nb_channels
av_get_default_channel_layout
av_get_channel_layout_channel_index
*av_get_channel_name
*av_get_channel_description
av_channel_layout_extract_channel
av_get_standard_channel_layout
