#define AVUTIL_HWCONTEXT_H
enum AVHWDeviceType ;
typedef struct AVHWDeviceInternal AVHWDeviceInternal;
typedef struct AVHWDeviceContext  AVHWDeviceContext;
typedef struct AVHWFramesInternal AVHWFramesInternal;
typedef struct AVHWFramesContext  AVHWFramesContext;
*av_hwdevice_ctx_alloc;
av_hwdevice_ctx_init;
av_hwdevice_ctx_create;
*av_hwframe_ctx_alloc;
av_hwframe_ctx_init;
av_hwframe_get_buffer;
av_hwframe_transfer_data;
enum AVHWFrameTransferDirection ;
av_hwframe_transfer_get_formats;
typedef struct AVHWFramesConstraints  AVHWFramesConstraints;
*av_hwdevice_hwconfig_alloc;
*av_hwdevice_get_hwframe_constraints;
av_hwframe_constraints_free;
