static const HWContextType *hw_table[] = ;
static const AVClass hwdevice_ctx_class = ;
hwdevice_ctx_free
*av_hwdevice_ctx_alloc
av_hwdevice_ctx_init
static const AVClass hwframe_ctx_class = ;
hwframe_ctx_free
*av_hwframe_ctx_alloc
hwframe_pool_prealloc
av_hwframe_ctx_init
av_hwframe_transfer_get_formats
transfer_data_alloc
av_hwframe_transfer_data
av_hwframe_get_buffer
*av_hwdevice_hwconfig_alloc
*av_hwdevice_get_hwframe_constraints
av_hwframe_constraints_free
av_hwdevice_ctx_create
