av_image_fill_max_pixsteps
static inline
image_get_linesize
av_image_get_linesize
av_image_fill_linesizes
av_image_fill_pointers
avpriv_set_systematic_pal2
av_image_alloc
typedef struct ImgUtils  ImgUtils;
static const AVClass imgutils_class = ;
av_image_check_size
av_image_check_sar
av_image_copy_plane
av_image_copy
av_image_fill_arrays
av_image_get_buffer_size
av_image_copy_to_buffer
