#define AVUTIL_SAMPLEFMT_H
enum AVSampleFormat ;
*av_get_sample_fmt_name;
av_get_sample_fmt;
av_get_alt_sample_fmt;
av_get_packed_sample_fmt;
av_get_planar_sample_fmt;
*av_get_sample_fmt_string;
av_get_bytes_per_sample;
av_sample_fmt_is_planar;
av_samples_get_buffer_size;
av_samples_fill_arrays;
av_samples_alloc;
av_samples_alloc_array_and_samples;
av_samples_copy;
av_samples_set_silence;
