typedef struct SampleFmtInfo  SampleFmtInfo;
static const SampleFmtInfo sample_fmt_info[AV_SAMPLE_FMT_NB] = ;
*av_get_sample_fmt_name
av_get_sample_fmt
av_get_alt_sample_fmt
av_get_packed_sample_fmt
av_get_planar_sample_fmt
char *av_get_sample_fmt_string (char *buf, int buf_size, enum AVSampleFormat sample_fmt)
av_get_bytes_per_sample
av_sample_fmt_is_planar
av_samples_get_buffer_size
av_samples_fill_arrays
av_samples_alloc
av_samples_alloc_array_and_samples
av_samples_copy
av_samples_set_silence
