#define AVUTIL_THREADMESSAGE_H
typedef struct AVThreadMessageQueue AVThreadMessageQueue;
typedef enum AVThreadMessageFlags  AVThreadMessageFlags;
av_thread_message_queue_alloc;
av_thread_message_queue_free;
av_thread_message_queue_send;
av_thread_message_queue_recv;
av_thread_message_queue_set_err_send;
av_thread_message_queue_set_err_recv;
av_thread_message_queue_set_free_func(void *msg));
av_thread_message_flush;
