struct AVThreadMessageQueue ;
av_thread_message_queue_alloc
av_thread_message_queue_set_free_func(void *msg))
av_thread_message_queue_free
#if HAVE_THREADS
av_thread_message_queue_send_locked
av_thread_message_queue_recv_locked
av_thread_message_queue_send
av_thread_message_queue_recv
av_thread_message_queue_set_err_send
av_thread_message_queue_set_err_recv
#if HAVE_THREADS
free_func_wrap
av_thread_message_flush
