#define AVUTIL_TIMECODE_H
#define AV_TIMECODE_STR_SIZE 16
enum AVTimecodeFlag ;
typedef struct  AVTimecode;
av_timecode_adjust_ntsc_framenum2;
av_timecode_get_smpte_from_framenum;
*av_timecode_make_string;
*av_timecode_make_smpte_tc_string;
*av_timecode_make_mpeg_tc_string;
av_timecode_init;
av_timecode_init_from_string;
av_timecode_check_frame_rate;
