#define AVUTIL_VERSION_H
AV_VERSION_INT ((a)<<16 | (b)<<8 | (c))
AV_VERSION_DOT a ##.## b ##.## c
AV_VERSION AV_VERSION_DOT(a, b, c)
AV_VERSION_MAJOR ((a) >> 16)
AV_VERSION_MINOR (((a) & 0x00FF00) >> 8)
AV_VERSION_MICRO ((a) & 0xFF)
#define LIBAVUTIL_VERSION_MAJOR  55
#define LIBAVUTIL_VERSION_MINOR  34
#define LIBAVUTIL_VERSION_MICRO 100
AV_VERSION_INT
AV_VERSION
#define LIBAVUTIL_BUILD         LIBAVUTIL_VERSION_INT
AV_STRINGIFY
#define FF_API_VDPAU                    (LIBAVUTIL_VERSION_MAJOR < 56)
#define FF_API_XVMC                     (LIBAVUTIL_VERSION_MAJOR < 56)
#define FF_API_OPT_TYPE_METADATA        (LIBAVUTIL_VERSION_MAJOR < 56)
#define FF_API_DLOG                     (LIBAVUTIL_VERSION_MAJOR < 56)
#define FF_API_VAAPI                    (LIBAVUTIL_VERSION_MAJOR < 56)
#define FF_API_FRAME_QP                 (LIBAVUTIL_VERSION_MAJOR < 56)
#define FF_API_PLUS1_MINUS1             (LIBAVUTIL_VERSION_MAJOR < 56)
#define FF_API_ERROR_FRAME              (LIBAVUTIL_VERSION_MAJOR < 56)
#define FF_API_CRC_BIG_TABLE            (LIBAVUTIL_VERSION_MAJOR < 56)
#define FF_API_PKT_PTS                  (LIBAVUTIL_VERSION_MAJOR < 56)
