u32 fm_tx_set_stereo_mono(struct fmdev *fmdev, u16 mode)
static u32 set_rds_text(struct fmdev *fmdev, u8 *rds_text)
static u32 set_rds_data_mode(struct fmdev *fmdev, u8 mode)
static u32 set_rds_len(struct fmdev *fmdev, u8 type, u16 len)
u32 fm_tx_set_rds_mode(struct fmdev *fmdev, u8 rds_en_dis)
u32 fm_tx_set_radio_text(struct fmdev *fmdev, u8 *rds_text, u8 rds_type)
u32 fm_tx_set_af(struct fmdev *fmdev, u32 af)
u32 fm_tx_set_region(struct fmdev *fmdev, u8 region)
u32 fm_tx_set_mute_mode(struct fmdev *fmdev, u8 mute_mode_toset)
static u32 set_audio_io(struct fmdev *fmdev)
static u32 enable_xmit(struct fmdev *fmdev, u8 new_xmit_state)
u32 fm_tx_set_pwr_lvl(struct fmdev *fmdev, u8 new_pwr_lvl)
u32 fm_tx_set_preemph_filter(struct fmdev *fmdev, u32 preemphasis)
u32 fm_tx_get_tune_cap_val(struct fmdev *fmdev)
u32 fm_tx_set_freq(struct fmdev *fmdev, u32 freq_to_set)
