#define _SISUSB_H_
#define SISUSB_NEW_CONFIG_COMPAT
#define SISUSB_VERSION		0
#define SISUSB_REVISION		0
#define SISUSB_PATCHLEVEL	8
#define INCL_SISUSB_CON		1
#define SISUSB_MINOR		133
#define SISUSB_IBUF_SIZE  0x01000
#define SISUSB_OBUF_SIZE  0x10000
#define NUMOBUFS 8
#define SISUSB_CORRECT_ENDIANNESS_PACKET(p)		\
do  while(0)
#define SISUSB_CORRECT_ENDIANNESS_PACKET(p)
struct sisusb_usb_data;
struct sisusb_urb_context ;
struct sisusb_usb_data ;
#define to_sisusb_dev(d) container_of(d, struct sisusb_usb_data, kref)
#define SU_URB_BUSY   1
#define SU_URB_ALLOC  2
#define SISUSB_EP_GFX_IN	0x0e
#define SISUSB_EP_GFX_OUT	0x0e
#define SISUSB_EP_GFX_BULK_OUT	0x01
#define SISUSB_EP_GFX_BULK_IN	0x02
#define SISUSB_EP_GFX_LBULK_OUT	0x03
#define SISUSB_EP_UNKNOWN_04	0x04
#define SISUSB_EP_BRIDGE_IN	0x0d
#define SISUSB_EP_BRIDGE_OUT	0x0d
#define SISUSB_TYPE_MEM		0
#define SISUSB_TYPE_IO		1
struct sisusb_packet  __attribute__ ((__packed__));
#define CLEARPACKET(packet) memset(packet, 0, 10)
#define SISUSB_PCI_MEMBASE	0xd0000000
#define SISUSB_PCI_MMIOBASE	0xe4000000
#define SISUSB_PCI_IOPORTBASE	0x0000d000
#define SISUSB_PCI_PSEUDO_MEMBASE	0x10000000
#define SISUSB_PCI_PSEUDO_MMIOBASE	0x20000000
#define SISUSB_PCI_PSEUDO_IOPORTBASE	0x0000d000
#define SISUSB_PCI_PSEUDO_PCIBASE	0x00010000
#define SISUSB_PCI_MMIOSIZE	(128*1024)
#define SISUSB_PCI_PCONFSIZE	0x5c
#define AROFFSET	0x40
#define ARROFFSET	0x41
#define GROFFSET	0x4e
#define SROFFSET	0x44
#define CROFFSET	0x54
#define MISCROFFSET	0x4c
#define MISCWOFFSET	0x42
#define INPUTSTATOFFSET 0x5A
#define PART1OFFSET	0x04
#define PART2OFFSET	0x10
#define PART3OFFSET	0x12
#define PART4OFFSET	0x14
#define PART5OFFSET	0x16
#define CAPTUREOFFSET	0x00
#define VIDEOOFFSET	0x02
#define COLREGOFFSET	0x48
#define PELMASKOFFSET	0x46
#define VGAENABLE	0x43
#define SISAR		SISUSB_PCI_IOPORTBASE + AROFFSET
#define SISARR		SISUSB_PCI_IOPORTBASE + ARROFFSET
#define SISGR		SISUSB_PCI_IOPORTBASE + GROFFSET
#define SISSR		SISUSB_PCI_IOPORTBASE + SROFFSET
#define SISCR		SISUSB_PCI_IOPORTBASE + CROFFSET
#define SISMISCR	SISUSB_PCI_IOPORTBASE + MISCROFFSET
#define SISMISCW	SISUSB_PCI_IOPORTBASE + MISCWOFFSET
#define SISINPSTAT	SISUSB_PCI_IOPORTBASE + INPUTSTATOFFSET
#define SISPART1	SISUSB_PCI_IOPORTBASE + PART1OFFSET
#define SISPART2	SISUSB_PCI_IOPORTBASE + PART2OFFSET
#define SISPART3	SISUSB_PCI_IOPORTBASE + PART3OFFSET
#define SISPART4	SISUSB_PCI_IOPORTBASE + PART4OFFSET
#define SISPART5	SISUSB_PCI_IOPORTBASE + PART5OFFSET
#define SISCAP		SISUSB_PCI_IOPORTBASE + CAPTUREOFFSET
#define SISVID		SISUSB_PCI_IOPORTBASE + VIDEOOFFSET
#define SISCOLIDXR	SISUSB_PCI_IOPORTBASE + COLREGOFFSET - 1
#define SISCOLIDX	SISUSB_PCI_IOPORTBASE + COLREGOFFSET
#define SISCOLDATA	SISUSB_PCI_IOPORTBASE + COLREGOFFSET + 1
#define SISCOL2IDX	SISPART5
#define SISCOL2DATA	SISPART5 + 1
#define SISPEL		SISUSB_PCI_IOPORTBASE + PELMASKOFFSET
#define SISVGAEN	SISUSB_PCI_IOPORTBASE + VGAENABLE
#define SISDACA		SISCOLIDX
#define SISDACD		SISCOLDATA
struct sisusb_info ;
struct sisusb_command ;
#define SUCMD_GET	0x01
#define SUCMD_SET	0x02
#define SUCMD_SETOR	0x03
#define SUCMD_SETAND	0x04
#define SUCMD_SETANDOR	0x05
#define SUCMD_SETMASK	0x06
#define SUCMD_CLRSCR	0x07
#define SUCMD_HANDLETEXTMODE 0x08
#define SUCMD_SETMODE	0x09
#define SUCMD_SETVESAMODE 0x0a
#define SISUSB_COMMAND		_IOWR(0xF3,0x3D,struct sisusb_command)
#define SISUSB_GET_CONFIG_SIZE	_IOR(0xF3,0x3E,__u32)
#define SISUSB_GET_CONFIG	_IOR(0xF3,0x3F,struct sisusb_info)
