static int cvm_oct_fill_hw_skbuff(int pool, int size, int elements)
static void cvm_oct_free_hw_skbuff(int pool, int size, int elements)
static int cvm_oct_fill_hw_memory(int pool, int size, int elements)
static void cvm_oct_free_hw_memory(int pool, int size, int elements)
int cvm_oct_mem_fill_fpa(int pool, int size, int elements)
void cvm_oct_mem_empty_fpa(int pool, int size, int elements)
