void hfs_bnode_read(struct hfs_bnode *node, void *buf,
int off, int len)
u16 hfs_bnode_read_u16(struct hfs_bnode *node, int off)
u8 hfs_bnode_read_u8(struct hfs_bnode *node, int off)
void hfs_bnode_read_key(struct hfs_bnode *node, void *key, int off)
void hfs_bnode_write(struct hfs_bnode *node, void *buf, int off, int len)
void hfs_bnode_write_u16(struct hfs_bnode *node, int off, u16 data)
void hfs_bnode_write_u8(struct hfs_bnode *node, int off, u8 data)
void hfs_bnode_clear(struct hfs_bnode *node, int off, int len)
void hfs_bnode_copy(struct hfs_bnode *dst_node, int dst,
struct hfs_bnode *src_node, int src, int len)
void hfs_bnode_move(struct hfs_bnode *node, int dst, int src, int len)
void hfs_bnode_dump(struct hfs_bnode *node)
void hfs_bnode_unlink(struct hfs_bnode *node)
static inline int hfs_bnode_hash(u32 num)
struct hfs_bnode *hfs_bnode_findhash(struct hfs_btree *tree, u32 cnid)
static struct hfs_bnode *__hfs_bnode_create(struct hfs_btree *tree, u32 cnid)
void hfs_bnode_unhash(struct hfs_bnode *node)
struct hfs_bnode *hfs_bnode_find(struct hfs_btree *tree, u32 num)
void hfs_bnode_free(struct hfs_bnode *node)
struct hfs_bnode *hfs_bnode_create(struct hfs_btree *tree, u32 num)
void hfs_bnode_get(struct hfs_bnode *node)
void hfs_bnode_put(struct hfs_bnode *node)
