#define __ATHDEFS_H__
#define A_ERROR			(-1)
#define A_DEVICE_NOT_FOUND	1
#define A_NO_MEMORY		2
#define A_MEMORY_NOT_AVAIL	3
#define A_NO_FREE_DESC		4
#define A_BAD_ADDRESS		5
#define A_WIN_DRIVER_ERROR	6
#define A_REGS_NOT_MAPPED	7
#define A_EPERM			8
#define A_EACCES		0
#define A_ENOENT		10
#define A_EEXIST		11
#define A_EFAULT		12
#define A_EBUSY			13
#define A_EINVAL		14
#define A_EMSGSIZE		15
#define A_ECANCELED		16
#define A_ENOTSUP		17
#define A_ECOMM			18
#define A_EPROTO		19
#define A_ENODEV		20
#define A_EDEVNOTUP		21
#define A_NO_RESOURCE		22
#define A_HARDWARE		23
#define A_PENDING		24
#define A_EBADCHANNEL		25
#define A_DECRYPT_ERROR		26
#define A_PHY_ERROR		27
#define A_CONSUMED		28
