#define __GMBOXIF_H__
#define AR6K_GMBOX_CREDIT_COUNTER       1
#define AR6K_GMBOX_CREDIT_SIZE_COUNTER  2
#define HCI_UART_COMMAND_PKT 0x01
#define HCI_UART_ACL_PKT     0x02
#define HCI_UART_SCO_PKT     0x03
#define HCI_UART_EVENT_PKT   0x04
typedef PREPACK struct  POSTPACK BT_HCI_ACL_HEADER;
typedef PREPACK struct  POSTPACK BT_HCI_SCO_HEADER;
typedef PREPACK struct  POSTPACK BT_HCI_COMMAND_HEADER;
typedef PREPACK struct  POSTPACK BT_HCI_EVENT_HEADER;
#define MBOX_SIG_HCI_BRIDGE_MAX      8
#define MBOX_SIG_HCI_BRIDGE_BT_ON    0
#define MBOX_SIG_HCI_BRIDGE_BT_OFF   1
#define MBOX_SIG_HCI_BRIDGE_BAUD_SET 2
#define MBOX_SIG_HCI_BRIDGE_PWR_SAV_ON    3
#define MBOX_SIG_HCI_BRIDGE_PWR_SAV_OFF   4
