#define _WMIX_H_
typedef PREPACK struct  POSTPACK WMIX_CMD_HDR;
typedef enum  WMIX_COMMAND_ID;
typedef enum  WMIX_EVENT_ID;
typedef PREPACK struct  POSTPACK WMIX_DSETOPENREQ_EVENT;
typedef PREPACK struct  POSTPACK WMIX_DSETCLOSE_EVENT;
typedef PREPACK struct  POSTPACK WMIX_DSETDATAREQ_EVENT;
typedef PREPACK struct  POSTPACK WMIX_DSETOPEN_REPLY_CMD;
typedef PREPACK struct  POSTPACK WMIX_DSETDATA_REPLY_CMD;
typedef PREPACK struct  POSTPACK WMIX_GPIO_OUTPUT_SET_CMD;
typedef PREPACK struct  POSTPACK WMIX_GPIO_REGISTER_SET_CMD;
typedef PREPACK struct  POSTPACK WMIX_GPIO_REGISTER_GET_CMD;
typedef PREPACK struct  POSTPACK WMIX_GPIO_INTR_ACK_CMD;
typedef PREPACK struct  POSTPACK WMIX_GPIO_INTR_EVENT;
typedef PREPACK struct  POSTPACK WMIX_GPIO_DATA_EVENT;
typedef PREPACK struct  POSTPACK WMIX_HB_CHALLENGE_RESP_CMD;
#define WMIX_HB_CHALLENGE_RESP_EVENT WMIX_HB_CHALLENGE_RESP_CMD
typedef PREPACK struct  POSTPACK WMIX_DBGLOG_CFG_MODULE_CMD;
typedef PREPACK struct  POSTPACK WMIX_PROF_CFG_CMD;
typedef PREPACK struct  POSTPACK WMIX_PROF_ADDR_SET_CMD;
typedef PREPACK struct  POSTPACK WMIX_PROF_COUNT_EVENT;
