#define HAVE_DLFCN_H 1
#define HAVE_ERRNO_H 1
#define HAVE_GMTIME_R 1
#define HAVE_INT16_T 1
#define HAVE_INT32_T 1
#define HAVE_INT64_T 1
#define HAVE_INT8_T 1
#define HAVE_INTPTR_T 1
#define HAVE_INTTYPES_H 1
#define HAVE_LOCALTIME_R 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UINT16_T 1
#define HAVE_UINT32_T 1
#define HAVE_UINT64_T 1
#define HAVE_UINT8_T 1
#define HAVE_UINTPTR_T 1
#define HAVE_UNISTD_H 1
#define HAVE_USLEEP 1
#define LT_OBJDIR ".libs/"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_NAME "sqlite"
#define PACKAGE_STRING "sqlite 3.8.10.2"
#define PACKAGE_TARNAME "sqlite"
#define PACKAGE_VERSION "3.8.10.2"
#define STDC_HEADERS 1
#define HAVE_EDITLINE 0
#if !HAVE_EDITLINE
#undef HAVE_EDITLINE
#define HAVE_READLINE 0
#if !HAVE_READLINE
#undef HAVE_READLINE
#define SQLITE_OS_UNIX 1
#if !SQLITE_OS_UNIX
#undef SQLITE_OS_UNIX
#define SQLITE_OS_WIN 0
#if !SQLITE_OS_WIN
#undef SQLITE_OS_WIN
#define SQLITE_THREADSAFE 1
#if !SQLITE_THREADSAVE
#undef SQLITE_THREADSAVE
#define SQLITE_THREAD_OVERRIDE_LOCK -1
#if !SQLITE_THREAD_OVERRIDE_LOCK
#undef SQLITE_THREAD_OVERRIDE_LOCK
#define SQLITE_TEMP_STORE 1
#if !SQLITE_THREAD_OVERRIDE_LOCK
#undef SQLITE_THREAD_OVERRIDE_LOCK
