#define pr_fmt(fmt) KBUILD_MODNAME ": " fmt
enum reg_v3 ;
static void nc_set_amp_power(int power)
static int nc_init_card(void)
static int nc_enable_audiodac(int value)
static int nc_power_up_pb(unsigned int port)
static int nc_power_up_cp(unsigned int port)
static int nc_power_down(void)
static int nc_power_down_pb(unsigned int device)
static int nc_power_down_cp(unsigned int device)
static int nc_set_pcm_voice_params(void)
static int nc_set_pcm_audio_params(int sfreq, int word_size, int num_channel)
static int nc_set_selected_output_dev(u8 value)
static int nc_audio_init(void)
static int nc_set_audio_port(int status)
static int nc_set_voice_port(int status)
static int nc_set_mute(int dev_id, u8 value)
static int nc_set_vol(int dev_id, int value)
static int nc_set_selected_input_dev(u8 value)
static int nc_get_mute(int dev_id, u8 *value)
static int nc_get_vol(int dev_id, int *value)
static void hp_automute(enum snd_jack_types type, int present)
static void nc_pmic_irq_cb(void *cb_data, u8 intsts)
static int nc_jack_enable(void)
struct snd_pmic_ops snd_pmic_ops_nc = ;
