ABItem::ABItem(QTreeWidget *treeWidget)
: QTreeWidgetItem(treeWidget)
void ABItem::setContact(const QString &contact)
void ABItem::setAddress(const QString &address)
void ABItem::setPhoneNumber(const QString &number)
void ABItem::remove()
