#if HAVE_ALTIVEC_H
#if HAVE_ALTIVEC
#if HAVE_BIGENDIAN
GET_PERM
LOAD_PIX
GET_PERM
LOAD_PIX
sad16_x2_altivec
sad16_y2_altivec
sad16_xy2_altivec
sad16_altivec
sad8_altivec
sse8_altivec
sse16_altivec
hadamard8_diff8x8_altivec
hadamard8_diff16x8_altivec
hadamard8_diff16_altivec
ff_me_cmp_init_ppc
