inline int ip6_rcv_finish( struct sk_buff *skb)
int ipv6_rcv(struct sk_buff *skb, struct net_device *dev, struct packet_type *pt, struct net_device *orig_dev)
static int ip6_input_finish(struct sk_buff *skb)
int ip6_input(struct sk_buff *skb)
int ip6_mc_input(struct sk_buff *skb)
