typedef struct yasm_preproc_nasm  yasm_preproc_nasm;
yasm_symtab *nasm_symtab;
static yasm_linemap *cur_lm;
static yasm_errwarns *cur_errwarns;
int tasm_compatible_mode = 0;
int tasm_locals;
const char *tasm_segment;
typedef struct preproc_dep  preproc_dep;
STAILQ_HEAD *preproc_deps;
static int done_dep_preproc;
yasm_preproc_module yasm_nasm_LTX_preproc;
nil_listgen_init
nil_listgen_cleanup
nil_listgen_output
nil_listgen_line
nil_listgen_uplevel
nil_listgen_downlevel
static ListGen nil_list = ;
nasm_efunc
nasm_preproc_create
nasm_preproc_destroy
nasm_preproc_get_line
nasm_preproc_add_dep
nasm_preproc_get_included_file
nasm_preproc_add_include_file
nasm_preproc_predefine_macro
nasm_preproc_undefine_macro
nasm_preproc_define_builtin
nasm_preproc_add_standard
yasm_preproc_module yasm_nasm_LTX_preproc = ;
tasm_preproc_create
yasm_preproc_module yasm_tasm_LTX_preproc = ;
