void pack_uint32_t(int pack, uint32_t *num)
void pack_uint16_t(int pack, uint16_t *num)
void pack_usb_device(int pack, struct usb_device *udev)
void pack_usb_interface(int pack __attribute__((unused)),
struct usb_interface *udev __attribute__((unused)))
static ssize_t usbip_xmit(int sockfd, void *buff, size_t bufflen, int sending)
ssize_t usbip_recv(int sockfd, void *buff, size_t bufflen)
ssize_t usbip_send(int sockfd, void *buff, size_t bufflen)
int usbip_send_op_common(int sockfd, uint32_t code, uint32_t status)
int usbip_recv_op_common(int sockfd, uint16_t *code)
int usbip_set_reuseaddr(int sockfd)
int usbip_set_nodelay(int sockfd)
int usbip_set_keepalive(int sockfd)
int tcp_connect(char *hostname, char *service)
