#define ELP_DMA       6
#define ELP_RX_PCBS   4
#define ELP_MAX_CARDS 4
#define	PORT_COMMAND	0x00
#define	PORT_STATUS	0x02
#define	PORT_AUXDMA	0x02
#define	PORT_DATA	0x04
#define	PORT_CONTROL	0x06
#define ELP_IO_EXTENT	0x10
#define	ATTN	0x80
#define	FLSH	0x40
#define DMAE	0x20
#define DIR	0x10
#define	TCEN	0x08
#define	CMDE	0x04
#define	HSF2	0x02
#define	HSF1	0x01
#define	HSF_PCB_ACK	HSF1
#define	HSF_PCB_NAK	HSF2
#define	HSF_PCB_END	(HSF2|HSF1)
#define	HSF_PCB_MASK	(HSF2|HSF1)
#define	HRDY	0x80
#define	HCRE	0x40
#define	ACRF	0x20
#define	DONE	0x08
#define	ASF3	0x04
#define	ASF2	0x02
#define	ASF1	0x01
#define	ASF_PCB_ACK	ASF1
#define	ASF_PCB_NAK	ASF2
#define	ASF_PCB_END	(ASF2|ASF1)
#define	ASF_PCB_MASK	(ASF2|ASF1)
#define	DMA_BRST	0x01
#define	MAX_PCB_DATA	62
#define	TIMEOUT	300
enum ;
typedef unsigned char         byte;
typedef unsigned short int    word;
typedef unsigned long int     dword;
struct Memconf ;
struct Rcv_pkt ;
struct Xmit_pkt ;
struct Rcv_resp ;
struct Xmit_resp ;
struct Netstat ;
struct Selftest ;
struct Info ;
struct Memdump ;
typedef struct  pcb_struct;
#define RECV_STATION	0x00
#define RECV_BROAD	0x01
#define RECV_MULTI	0x02
#define RECV_PROMISC	0x04
#define NO_LOOPBACK	0x00
#define INT_LOOPBACK	0x08
#define EXT_LOOPBACK	0x10
#define DMA_BUFFER_SIZE  1600
#define BACKLOG_SIZE      4
typedef struct  elp_device;
