#define SIS900_TOTAL_SIZE 0x100
enum sis900_registers ;
enum sis900_command_register_bits ;
enum sis900_configuration_register_bits ;
enum sis900_eeprom_access_reigster_bits ;
enum sis900_interrupt_register_bits ;
enum sis900_interrupt_enable_reigster_bits ;
#define MAX_DMA_RANGE	7
#define TxMXDMA_shift   	20
#define RxMXDMA_shift    20
enum sis900_tx_rx_dma;
#define TX_FILL_THRESH   16
#define TxFILLT_shift   	8
#define TxDRNT_shift    	0
#define TxDRNT_100      	48
#define TxDRNT_10		16
enum sis900_transmit_config_register_bits ;
#define RxDRNT_shift     1
#define RxDRNT_100	16
#define RxDRNT_10		24
enum sis900_reveive_config_register_bits ;
#define RFAA_shift      28
#define RFADDR_shift    16
enum sis900_receive_filter_control_register_bits ;
enum sis900_reveive_filter_data_mask ;
enum sis900_eeprom_address ;
enum sis900_eeprom_command ;
enum sis96x_eeprom_command ;
enum sis900_pci_registers ;
enum sis900_cfgpmc_register_bits ;
enum sis900_pmesp_bits ;
enum sis900_cfgpmcsr_register_bits ;
enum sis900_power_management_control_register_bits ;
#define MIIread         0x6000
#define MIIwrite        0x5002
#define MIIpmdShift     7
#define MIIregShift     2
#define MIIcmdLen       16
#define MIIcmdShift     16
enum sis900_buffer_status ;
enum sis900_tx_buffer_status ;
enum sis900_rx_bufer_status ;
enum mii_registers ;
enum sis_mii_registers ;
enum ics_mii_registers ;
enum amd_mii_registers ;
enum mii_control_register_bits ;
enum mii_status_register_bits ;
#define		MII_ID1_OUI_LO		0xFC00
#define		MII_ID1_MODEL		0x03F0
#define		MII_ID1_REV		0x000F
enum mii_nway_register_bits ;
enum mii_stsout_register_bits ;
enum mii_stsics_register_bits ;
enum mii_stssum_register_bits ;
enum sis900_revision_id ;
enum sis630_revision_id ;
#define FDX_CAPABLE_DUPLEX_UNKNOWN      0
#define FDX_CAPABLE_HALF_SELECTED       1
#define FDX_CAPABLE_FULL_SELECTED       2
#define HW_SPEED_UNCONFIG		0
#define HW_SPEED_HOME		1
#define HW_SPEED_10_MBPS        	10
#define HW_SPEED_100_MBPS       	100
#define HW_SPEED_DEFAULT        	(HW_SPEED_100_MBPS)
#define CRC_SIZE                4
#define MAC_HEADER_SIZE         14
#if defined(CONFIG_VLAN_8021Q) || defined(CONFIG_VLAN_8021Q_MODULE)
#define MAX_FRAME_SIZE  (1518 + 4)
#define MAX_FRAME_SIZE  1518
#define TX_BUF_SIZE     (MAX_FRAME_SIZE+18)
#define RX_BUF_SIZE     (MAX_FRAME_SIZE+18)
#define NUM_TX_DESC     16
#define NUM_RX_DESC     16
#define TX_TOTAL_SIZE	NUM_TX_DESC*sizeof(BufferDesc)
#define RX_TOTAL_SIZE	NUM_RX_DESC*sizeof(BufferDesc)
#define SIS630_VENDOR_ID        0x1039
#define SIS630_DEVICE_ID        0x0630
