static const AVClass audio_data_class = ;
calc_ptr_alignment
ff_sample_fmt_is_planar
ff_audio_data_set_channels
ff_audio_data_init
*ff_audio_data_alloc
ff_audio_data_realloc
ff_audio_data_free
ff_audio_data_copy
ff_audio_data_combine
ff_audio_data_drain
ff_audio_data_add_to_fifo
ff_audio_data_read_from_fifo
