#define AVRESAMPLE_VERSION_H
#define LIBAVRESAMPLE_VERSION_MAJOR  3
#define LIBAVRESAMPLE_VERSION_MINOR  1
#define LIBAVRESAMPLE_VERSION_MICRO  0
AV_VERSION_INT
AV_VERSION
#define LIBAVRESAMPLE_BUILD        LIBAVRESAMPLE_VERSION_INT
AV_STRINGIFY
