static int __is_tr_translated(struct thash_data *trp, u64 rid, u64 va)
static int __is_tr_overlap(struct thash_data *trp, u64 rid, u64 sva, u64 eva)
void machine_tlb_purge(u64 va, u64 ps)
void local_flush_tlb_all(void)
int vhpt_enabled(struct kvm_vcpu *vcpu, u64 vadr, enum vhpt_ref ref)
struct thash_data *vsa_thash(union ia64_pta vpta, u64 va, u64 vrr, u64 *tag)
struct thash_data *__vtr_lookup(struct kvm_vcpu *vcpu, u64 va, int type)
static void vhpt_insert(u64 pte, u64 itir, u64 ifa, u64 gpte)
void mark_pages_dirty(struct kvm_vcpu *v, u64 pte, u64 ps)
void thash_vhpt_insert(struct kvm_vcpu *v, u64 pte, u64 itir, u64 va, int type)
struct thash_data *vhpt_lookup(u64 va)
u64 guest_vhpt_lookup(u64 iha, u64 *pte)
static void vtlb_purge(struct kvm_vcpu *v, u64 va, u64 ps)
static void vhpt_purge(struct kvm_vcpu *v, u64 va, u64 ps)
void vtlb_insert(struct kvm_vcpu *v, u64 pte, u64 itir, u64 va)
int vtr_find_overlap(struct kvm_vcpu *vcpu, u64 va, u64 ps, int type)
void thash_purge_entries(struct kvm_vcpu *v, u64 va, u64 ps)
void thash_purge_entries_remote(struct kvm_vcpu *v, u64 va, u64 ps)
u64 translate_phy_pte(u64 *pte, u64 itir, u64 va)
void  thash_purge_and_insert(struct kvm_vcpu *v, u64 pte, u64 itir,
u64 ifa, int type)
void thash_purge_all(struct kvm_vcpu *v)
struct thash_data *vtlb_lookup(struct kvm_vcpu *v, u64 va, int is_data)
void thash_init(struct thash_cb *hcb, u64 sz)
u64 kvm_get_mpt_entry(u64 gpfn)
u64 kvm_lookup_mpa(u64 gpfn)
u64 kvm_gpa_to_mpa(u64 gpa)
int fetch_code(struct kvm_vcpu *vcpu, u64 gip, IA64_BUNDLE *pbundle)
void kvm_init_vhpt(struct kvm_vcpu *v)
void kvm_init_vtlb(struct kvm_vcpu *v)
