#define MAX_CHILD_ARGS 64
ffserver_save_avoption;
vreport_config_error;
report_config_error;
ERROR report_config_error(config->filename, config->line_num,\
AV_LOG_ERROR, &config->errors, __VA_ARGS__)
WARNING report_config_error(config->filename, config->line_num,\
AV_LOG_WARNING, &config->warnings, __VA_ARGS__)
resolve_host
ffserver_get_arg
ffserver_parse_acl_row
add_codec
ffserver_set_codec
ffserver_opt_preset
*ffserver_guess_format
vreport_config_error
report_config_error
ffserver_set_int_param
ffserver_set_float_param
ffserver_save_avoption
ffserver_save_avoption_int
ffserver_parse_config_global
ffserver_parse_config_feed
ffserver_parse_config_stream
ffserver_parse_config_redirect
ffserver_parse_ffconfig
#undef ERROR
#undef WARNING
ffserver_free_child_args
