unsigned short TxRate_iwconfig;
static int          msglevel                =MSG_LEVEL_INFO;
void MACvReadAllRegs (unsigned long dwIoBase, unsigned char *pbyMacRegs)
bool MACbIsRegBitsOn (unsigned long dwIoBase, unsigned char byRegOfs, unsigned char byTestBits)
bool MACbIsRegBitsOff (unsigned long dwIoBase, unsigned char byRegOfs, unsigned char byTestBits)
bool MACbIsIntDisable (unsigned long dwIoBase)
unsigned char MACbyReadMultiAddr (unsigned long dwIoBase, unsigned int uByteIdx)
void MACvWriteMultiAddr (unsigned long dwIoBase, unsigned int uByteIdx, unsigned char byData)
void MACvSetMultiAddrByHash (unsigned long dwIoBase, unsigned char byHashIdx)
void MACvResetMultiAddrByHash (unsigned long dwIoBase, unsigned char byHashIdx)
void MACvSetRxThreshold (unsigned long dwIoBase, unsigned char byThreshold)
void MACvGetRxThreshold (unsigned long dwIoBase, unsigned char *pbyThreshold)
void MACvSetTxThreshold (unsigned long dwIoBase, unsigned char byThreshold)
void MACvGetTxThreshold (unsigned long dwIoBase, unsigned char *pbyThreshold)
void MACvSetDmaLength (unsigned long dwIoBase, unsigned char byDmaLength)
void MACvGetDmaLength (unsigned long dwIoBase, unsigned char *pbyDmaLength)
void MACvSetShortRetryLimit (unsigned long dwIoBase, unsigned char byRetryLimit)
void MACvGetShortRetryLimit (unsigned long dwIoBase, unsigned char *pbyRetryLimit)
void MACvSetLongRetryLimit (unsigned long dwIoBase, unsigned char byRetryLimit)
void MACvGetLongRetryLimit (unsigned long dwIoBase, unsigned char *pbyRetryLimit)
void MACvSetLoopbackMode (unsigned long dwIoBase, unsigned char byLoopbackMode)
bool MACbIsInLoopbackMode (unsigned long dwIoBase)
void MACvSetPacketFilter (unsigned long dwIoBase, unsigned short wFilterType)
void MACvSaveContext (unsigned long dwIoBase, unsigned char *pbyCxtBuf)
void MACvRestoreContext (unsigned long dwIoBase, unsigned char *pbyCxtBuf)
bool MACbCompareContext (unsigned long dwIoBase, unsigned char *pbyCxtBuf)
bool MACbSoftwareReset (unsigned long dwIoBase)
bool MACbSafeSoftwareReset (unsigned long dwIoBase)
bool MACbSafeRxOff (unsigned long dwIoBase)
bool MACbSafeTxOff (unsigned long dwIoBase)
bool MACbSafeStop (unsigned long dwIoBase)
bool MACbShutdown (unsigned long dwIoBase)
void MACvInitialize (unsigned long dwIoBase)
void MACvSetCurrRx0DescAddr (unsigned long dwIoBase, unsigned long dwCurrDescAddr)
void MACvSetCurrRx1DescAddr (unsigned long dwIoBase, unsigned long dwCurrDescAddr)
void MACvSetCurrTx0DescAddrEx (unsigned long dwIoBase, unsigned long dwCurrDescAddr)
void MACvSetCurrAC0DescAddrEx (unsigned long dwIoBase, unsigned long dwCurrDescAddr)
void MACvSetCurrTXDescAddr (int iTxType, unsigned long dwIoBase, unsigned long dwCurrDescAddr)
void MACvTimer0MicroSDelay (unsigned long dwIoBase, unsigned int uDelay)
void MACvOneShotTimer0MicroSec (unsigned long dwIoBase, unsigned int uDelayTime)
void MACvOneShotTimer1MicroSec (unsigned long dwIoBase, unsigned int uDelayTime)
void MACvSetMISCFifo (unsigned long dwIoBase, unsigned short wOffset, unsigned long dwData)
bool MACbTxDMAOff (unsigned long dwIoBase, unsigned int idx)
void MACvClearBusSusInd (unsigned long dwIoBase)
void MACvEnableBusSusEn (unsigned long dwIoBase)
bool MACbFlushSYNCFifo (unsigned long dwIoBase)
bool MACbPSWakeup (unsigned long dwIoBase)
void MACvSetKeyEntry (unsigned long dwIoBase, unsigned short wKeyCtl, unsigned int uEntryIdx,
unsigned int uKeyIdx, unsigned char *pbyAddr, unsigned long *pdwKey, unsigned char byLocalID)
void MACvDisableKeyEntry (unsigned long dwIoBase, unsigned int uEntryIdx)
void MACvSetDefaultKeyEntry (unsigned long dwIoBase, unsigned int uKeyLen,
unsigned int uKeyIdx, unsigned long *pdwKey, unsigned char byLocalID)
void MACvDisableDefaultKey (unsigned long dwIoBase)
void MACvSetDefaultTKIPKeyEntry (unsigned long dwIoBase, unsigned int uKeyLen,
unsigned int uKeyIdx, unsigned long *pdwKey, unsigned char byLocalID)
void MACvSetDefaultKeyCtl (unsigned long dwIoBase, unsigned short wKeyCtl, unsigned int uEntryIdx, unsigned char byLocalID)
