#define AVFORMAT_FLV_H
#define FLV_AUDIO_SAMPLESSIZE_OFFSET 1
#define FLV_AUDIO_SAMPLERATE_OFFSET  2
#define FLV_AUDIO_CODECID_OFFSET     4
#define FLV_VIDEO_FRAMETYPE_OFFSET   4
#define FLV_AUDIO_CHANNEL_MASK    0x01
#define FLV_AUDIO_SAMPLESIZE_MASK 0x02
#define FLV_AUDIO_SAMPLERATE_MASK 0x0c
#define FLV_AUDIO_CODECID_MASK    0xf0
#define FLV_VIDEO_CODECID_MASK    0x0f
#define FLV_VIDEO_FRAMETYPE_MASK  0xf0
#define AMF_END_OF_OBJECT         0x09
#define KEYFRAMES_TAG
#define KEYFRAMES_TIMESTAMP_TAG
#define KEYFRAMES_BYTEOFFSET_TAG
enum ;
enum FlvTagType ;
enum ;
enum ;
enum ;
enum ;
enum ;
enum ;
enum ;
typedef enum  AMFDataType;
