#if CONFIG_NETWORK
frac_init
frac_add
ff_choose_timebase
ff_choose_chroma_location
avformat_alloc_output_context2
validate_codec_tag
init_muxer
init_pts
write_header_internal
avformat_init_output
avformat_write_header
#define AV_PKT_FLAG_UNCODED_FRAME 0x2000
#define UNCODED_FRAME_PACKET_SIZE (INT_MIN / 3 * 2 + (int)sizeof(AVFrame))
#if FF_API_COMPUTE_PKT_FIELDS2 && FF_API_LAVF_AVCTX
FF_DISABLE_DEPRECATION_WARNINGS
compute_muxer_pkt_fields
FF_ENABLE_DEPRECATION_WARNINGS
write_packet
check_packet
prepare_input_packet
do_packet_auto_bsf
av_write_frame
#define CHUNK_START 0x1000
ff_interleave_add_packet(AVFormatContext *, AVPacket *, AVPacket *))
interleave_compare_dts
ff_interleave_packet_per_dts
*ff_interleaved_peek
interleave_packet
av_interleaved_write_frame
av_write_trailer
av_get_output_timestamp
ff_write_chained
av_write_uncoded_frame_internal
av_write_uncoded_frame
av_interleaved_write_uncoded_frame
av_write_uncoded_frame_query
