ff_tls_init
ff_tls_deinit
int ff_network_inited_globally;
ff_network_init
ff_network_wait_fd
ff_network_wait_fd_timeout
ff_network_close
#if HAVE_WINSOCK2_H
ff_neterrno
ff_is_multicast_address
ff_poll_interrupt
ff_socket
ff_listen
ff_accept
ff_listen_bind
ff_listen_connect
match_host_pattern
ff_http_match_no_proxy
