ogm_chapter
ff_vorbis_stream_comment
ff_vorbis_comment
struct oggvorbis_private ;
fixup_vorbis_headers
vorbis_cleanup
vorbis_update_metadata
vorbis_header
vorbis_packet
const struct ogg_codec ff_vorbis_codec = ;
