#define AVFORMAT_RDT_H
typedef struct RDTDemuxContext RDTDemuxContext;
*ff_rdt_parse_open;
ff_rdt_parse_close;
ff_rdt_calc_response_and_checksum;
ff_register_rdt_dynamic_payload_handlers;
ff_rdt_subscribe_rule;
ff_rdt_parse_header;
ff_rdt_parse_packet;
ff_real_parse_sdp_a_line;
