struct PayloadContext ;
xiph_close_context
xiph_handle_packet
get_base128
parse_packed_headers
xiph_parse_fmtp_pair
xiph_parse_sdp_line
RTPDynamicProtocolHandler ff_theora_dynamic_handler = ;
RTPDynamicProtocolHandler ff_vorbis_dynamic_handler = ;
