typedef struct AdaptationSet  AdaptationSet;
typedef struct WebMDashMuxContext  WebMDashMuxContext;
*get_codec_name
get_duration
write_header
write_footer
subsegment_alignment
bitstream_switching
write_representation
check_matching_width
check_matching_height
check_matching_sample_rate
free_adaptation_sets
parse_filename
write_adaptation_set
to_integer
parse_adaptation_sets
webm_dash_manifest_write_header
webm_dash_manifest_write_packet
webm_dash_manifest_write_trailer
OFFSET offsetof(WebMDashMuxContext, x)
static const AVOption options[] = ;
#if CONFIG_WEBM_DASH_MANIFEST_MUXER
static const AVClass webm_dash_class = ;
AVOutputFormat ff_webm_dash_manifest_muxer = ;
